// SPDX-License-Identifier: LicenseRef-PolyFormNoncommercial-1.0.0
// expertOnly: 仅 performance_expert_mode（顶栏「高级」）为 true 时露出
export const UI_TABS = [
  { key: 'model', label: '模型' },
  { key: 'dataset', label: '数据参数' },
  { key: 'training', label: '训练' },
  { key: 'network', label: '网络' },
  { key: 'optimizer', label: '优化器' },
  { key: 'preview', label: '预览/验证' },
  { key: 'speed', label: '加速' },
  { key: 'frontier', label: '先锋', expertOnly: true },
  { key: 'advanced', label: '高级', expertOnly: true },
];

export const TRAINING_TYPES = [
  { id: 'sdxl-lora', group: 'LoRA', label: 'SDXL' },
  { id: 'anima-lora', group: 'LoRA', label: 'Anima' },
  { id: 'newbie-lora', group: 'LoRA', label: 'Newbie' },
  { id: 'krea2-lora', group: 'LoRA', label: 'Krea-2' },
  { id: 'minimax-h3-lora', group: 'LoRA', label: 'MiniMax H3' },
  { id: 'flux2-lora', group: 'LoRA', label: 'FLUX.2 Klein' },
  { id: 'zimage-lora', group: 'LoRA', label: 'Z-Image' },
  { id: 'wan22-ti2v-lora', group: 'LoRA', label: 'Wan2.2 TI2V-5B' },
  { id: 'wan22-t2v-a14b-lora', group: 'LoRA', label: 'Wan2.2 T2V-A14B' },
  { id: 'ltx23-lora', group: 'LoRA', label: 'LTX-2.3' },
  { id: 'ltx25-lora', group: 'LoRA', label: 'LTX-2.5' },
  { id: 'boogu-lora', group: 'LoRA', label: 'Boogu-Image' },
  { id: 'boogu-edit-lora', group: 'Edit 模型', label: 'Boogu-Image Edit' },
  { id: 'anima-edit-model', group: 'Edit 模型', label: 'Anima' },
  { id: 'concept-edit', group: '概念编辑', label: '概念编辑训练', hidden: true, disabled: true, disabledReason: '该训练类型暂未开放启动。' },
  // 以下旧入口保留但隐藏（existing configs 兼容）
  { id: 'sdxl-ileco', group: 'LoRA 概念编辑', label: 'SDXL iLECO', hidden: true },
  { id: 'sdxl-addift', group: 'LoRA 概念编辑', label: 'SDXL ADDifT', hidden: true },
  { id: 'sdxl-multi-addift', group: 'LoRA 概念编辑', label: 'SDXL Multi-ADDifT', hidden: true },
  { id: 'anima-ileco', group: 'LoRA 概念编辑', label: 'Anima iLECO', hidden: true },
  { id: 'anima-addift', group: 'LoRA 概念编辑', label: 'Anima ADDifT', hidden: true },
  { id: 'anima-multi-addift', group: 'LoRA 概念编辑', label: 'Anima Multi-ADDifT', hidden: true },
  { id: 'sdxl-turbo-lora', group: '专项训练', label: 'SDXL Turbo / LCM LoRA' },
  { id: 'lab-distiller', group: '专项训练', label: 'LAB Distiller' },
  { id: 'anima-few-step-lora', group: '专项训练', label: 'Anima Few-step LoRA' },
  { id: 'newbie-few-step-lora', group: '专项训练', label: 'Newbie Few-step LoRA' },
  { id: 'flux-lora', group: 'LoRA', label: 'FLUX' },
  { id: 'lumina-lora', group: 'LoRA', label: 'Lumina', hidden: true },
  { id: 'qwen-image-lora', group: 'LoRA', label: 'Qwen Image', hidden: true },
  { id: 'hunyuan-dit-lora', group: 'LoRA', label: 'HunyuanDiT', hidden: true },
  { id: 'sd-lora', group: 'LoRA', label: 'SD 1.5' },
  { id: 'sd-ileco', group: 'LoRA 概念编辑', label: 'SD 1.5 iLECO', hidden: true },
  { id: 'sd-addift', group: 'LoRA 概念编辑', label: 'SD 1.5 ADDifT', hidden: true },
  { id: 'sd-multi-addift', group: 'LoRA 概念编辑', label: 'SD 1.5 Multi-ADDifT', hidden: true },
  { id: 'sdxl-finetune', group: 'Finetune', label: 'SDXL' },
  { id: 'anima-finetune', group: 'Finetune', label: 'Anima' },
  { id: 'krea2-finetune', group: 'Finetune', label: 'Krea-2' },
  { id: 'boogu-finetune', group: 'Finetune', label: 'Boogu-Image' },
  { id: 'ltx23-finetune', group: 'Finetune', label: 'LTX-2.3' },
  { id: 'ltx25-finetune', group: 'Finetune', label: 'LTX-2.5' },
  { id: 'flux2-finetune', group: 'Finetune', label: 'FLUX.2 Klein' },
  { id: 'zimage-finetune', group: 'Finetune', label: 'Z-Image' },
  { id: 'wan22-finetune', group: 'Finetune', label: 'Wan2.2 TI2V-5B' },
  { id: 'minimax-h3-finetune', group: 'Finetune', label: 'MiniMax H3' },
  { id: 'lumina-finetune', group: 'Finetune', label: 'Lumina', hidden: true },
  { id: 'sd-dreambooth', group: 'Finetune', label: 'SD DreamBooth' },
  { id: 'sd-controlnet', group: 'ControlNet', label: 'SD 1.5' },
  { id: 'sdxl-controlnet', group: 'ControlNet', label: 'SDXL' },
  { id: 'anima-controlnet', group: 'ControlNet', label: 'Anima' },
  { id: 'sd-textual-inversion', group: 'Textual Inversion', label: 'SD 1.5 TI' },
  { id: 'sdxl-textual-inversion', group: 'Textual Inversion', label: 'SDXL TI' },
  { id: 'yolo', group: '其他模型训练', label: 'YOLO 模型训练' },
  { id: 'aesthetic-scorer', group: '其他模型训练', label: '美学评分模型训练' },
];

export const VISIBLE_TRAINING_TYPES = TRAINING_TYPES.filter((type) => !type.hidden);
