// SPDX-License-Identifier: LicenseRef-PolyFormNoncommercial-1.0.0
// desc 文案表 —— 适配器（LoRA/LyCORIS 变体、容量、初始化、结构叠加）。
// 推荐范围依据：backend launcher/api/domain/schemas/sdxl_lora.py（dim 推荐 4-128、alpha=dim/2）、
// training_wiki/network_dim|network_alpha 口径、schemaCommon 能力矩阵审计注释。
export default {
  network_module: ['训练网络模块决定适配器实现路线。建议 networks.lora（兼容性最好）；lora_fa/vera/tlora/flexrank 为实验变体；lycoris.kohya 是旧入口。', 'Network module picks the adapter implementation. networks.lora has the best compatibility; lora_fa/vera/tlora/flexrank are experimental; lycoris.kohya is the legacy entry.'],
  network_dim: ['LoRA rank：低秩子空间维度，决定可学习容量与文件体积。推荐范围：4–128；角色/复杂风格 32–64 起步，简单概念 8–16 即可。', 'LoRA rank: low-rank subspace size driving capacity and file size. Recommended: 4-128; start at 32-64 for characters/styles, 8-16 for simple concepts.'],
  network_alpha: ['缩放系数：有效学习率 ≈ lr × alpha/rank。推荐范围：rank 或 rank/2（如 rank=32 时 alpha=16–32）；高 rank 可降低比值求稳。', 'Scaling factor: effective LR is about lr x alpha/rank. Recommended: alpha = rank or rank/2 (e.g. 16-32 when rank=32); lower the ratio at high rank.'],
  network_dropout: ['对 LoRA 输出按神经元随机置零的正则。推荐范围：0（默认）或 ≤0.1；过大伤收敛。', 'Randomly zeroes LoRA output units as regularization. Recommended: 0 (default) or at most 0.1.'],
  conv_dim: ['Conv 层的 rank（作用卷积投影）。推荐范围：与 network_dim 相同或减半；仅影响含 Conv 的目标层。', 'Rank for Conv layers. Recommended: equal to network_dim or half; applies only to Conv targets.'],
  conv_alpha: ['Conv 层缩放系数。推荐范围：与 conv_dim 对齐（=dim 或 dim/2）。', 'Alpha scaling for Conv layers. Recommended: match conv_dim (=dim or dim/2).'],
  dropout: ['LyCORIS 主 dropout 概率。推荐范围：0–0.1，默认 0。', 'Main LyCORIS dropout probability. Recommended: 0-0.1, default 0.'],
  rank_dropout: ['按 rank/输出维度随机丢弃的概率（LoKr 等变体）。推荐范围：0 默认；≤0.1 试验。', 'Per-rank/output-dim dropout for LoKr-style variants. Default 0; experiment within 0.1.'],
  module_dropout: ['按整个模块随机丢弃的概率。推荐范围：0 默认；≤0.1 试验，过大明显伤收敛。', 'Whole-module random drop probability. Default 0; try within 0.1 max.'],
  lokr_rank_dropout: ['LoKr 按 rank 维度随机丢弃概率。推荐范围：0 默认；≤0.1 试验。', 'LoKr per-rank dropout. Default 0; experiment within 0.1.'],
  lokr_module_dropout: ['LoKr 按整个模块随机丢弃概率。推荐范围：0 默认。', 'LoKr whole-module dropout. Default 0.'],
  lora_rank_dropout: ['LoRA rank 级随机丢弃。推荐范围：0 默认；≤0.1 试验。', 'Rank-level dropout for LoRA. Default 0; up to 0.1 experimentally.'],
  lora_dropout: ['标准 LoRA dropout。推荐范围：0 默认；小数据集防过拟合可用 ≤0.1。', 'Standard LoRA dropout. Default 0; use up to 0.1 on tiny datasets.'],
  dim_from_weights: ['从已加载的 network_weights 自动推断 rank/dim，忽略手填值。建议续训旧 LoRA 且不确定原参数时开启。', 'Infer rank/dim from loaded network_weights instead of manual values. Useful when resuming unknown checkpoints.'],
  train_norm: ['额外把归一化层（LayerNorm/RMSNorm）纳入训练。建议角色一致性微调时试验，常规保持关闭。', 'Also train normalization layers (LayerNorm/RMSNorm). Try for character fidelity; keep off normally.'],
  lokr_train_norm: ['LoKr 同时训练归一化层参数。建议仅在风格迁移类任务试验，默认关闭。', 'Train norm layers alongside LoKr. Experimental; off by default.'],
  scale_weight_norms_alias: null,
  lokr_factor: ['LoKr Kronecker 分解因子：越大越省参数越弱表达。-1 表示无穷大因子（最省）。推荐范围：4（常用起点）～8；-1 极限压缩。', 'LoKr Kronecker factor: larger means fewer parameters and less expressivity; -1 = infinity (smallest). Recommended: 4 to start, up to 8; -1 for extreme compression.'],
  decompose_both: ['LoKr 额外分解较小侧矩阵，进一步省参数但更慢。建议默认关闭，参数预算极紧时开。', 'Additionally decompose the smaller LoKr side matrix to save parameters at speed cost. Keep off unless parameter-bound.'],
  full_matrix: ['强制 LoKr 走完整矩阵路径（放弃分解收益换稳定）。建议排查 LoKr 数值问题时临时开启。', 'Force LoKr onto the full-matrix path, trading savings for stability. Use temporarily when debugging numerics.'],
  unbalanced_factorization: ['LoKr 分解时交换较大侧，改变参数分布形态。建议默认关闭；属实验开关。', 'Swap which LoKr side gets factorized, changing parameter shape. Experimental; keep off.'],
  lokr_no_materialize_forward: ['前向直接用 Kronecker 因子计算而不实体化整块权重，省显存可能更慢。建议显存紧张且用 LoKr 时试验。', 'Compute LoKr forward from factors without materializing full weights: saves VRAM, may be slower. Worth trying when VRAM-bound on LoKr.'],
  lokr_no_materialize_strategy: ['免实体化前向的实现选择：auto 按启发式选路，legacy 旧行为。建议 auto。', 'Implementation for non-materialized LoKr forward. auto heuristic recommended over legacy.'],

  // ── 结构变体（向导「叠加增强」） ──
  dora_enabled: ['DoRA 把权重分解为方向+幅度联合训练，表达力强于同 rank LoRA 但稍慢。建议在原生 LoRA 基础上叠加使用；与 LyCORIS 族互斥（注入链短路）。', 'DoRA decomposes weights into direction+magnitude for higher expressivity than plain LoRA at a small speed cost. Stack on native LoRA only; mutually exclusive with LyCORIS families.'],
  dora_wd: [
    { zh: '叠加在标准 LoRA 路线上的权重分解增强（方向+幅度），比标准 LoRA 表达力强但稍慢。本类型的 DoRA 主入口就是这个开关（向导中的「叠加 DoRA」开关读写它），后端会将其归一为 use_dora/dora_enabled 并强制 bypass_mode=False。推荐范围：小数据集或需要更强概念绑定（如角色脸）时开启。', en: 'Weight-decomposed DoRA rider on the standard LoRA route: stronger than plain LoRA but slightly slower. This toggle is the DoRA entry for this type (the wizard switch writes it); the backend normalizes it to use_dora/dora_enabled and forces bypass_mode=False. Recommended: enable for stronger concept binding (character faces) or small datasets.', only: 'dora_enabled' },
    { zh: 'DoRA 权重分解别名开关：后端将其归一为 use_dora/dora_enabled=true 的原生 DoRA 注入，并强制 bypass_mode=False。与 LyCORIS 族互斥（注入链短路）。推荐范围：需要更强概念绑定时开启。', en: 'Alias switch normalized by the backend to use_dora/dora_enabled=true with bypass_mode forced off; mutually exclusive with LyCORIS families. Enable for stronger concept binding.' },
  ],
  bypass_mode: [{ zh: '旁路模式：绕过部分注入逻辑直接训练。注意本类型下 DoRA 叠加会强制将其关闭（后端行为），二者不可同开。建议保持 false。', en: 'Bypass mode skips part of the injection logic. DoRA stacking forces this off server-side; they cannot combine. Keep false.' }],
  rs_lora_enabled: ['RS-LoRA 让 alpha 随 rank 缩放（α/√r），高 rank 更稳。推荐范围：rank ≥64 想提稳时开启；低 rank 收益有限。', 'RS-LoRA scales alpha by sqrt(rank) for stability at high rank. Enable for rank >=64; little gain below.'],
  lora_plus_enabled: ['LoRA+ 给 B 矩阵更高学习率，加快上层适配。推荐搭配 lr 倍率 16 使用；小数据集慎用易过拟合。', 'LoRA+ trains the B matrix with a higher LR for faster upper adaptation. Pair with ratio 16; careful on small datasets.'],
  lora_plus_lr_ratio: ['LoRA+ 中 B 相对 A 的学习率倍率。推荐范围：16（论文常用）；1 等价关闭。', 'LR ratio of B vs A in LoRA+. Recommended: 16 (paper value); 1 disables.'],
  lora_fa_enabled: ['LoRA-FA 冻结 A 只训 B，显著省优化器显存。建议显存吃紧时开启，容量略降。', 'LoRA-FA freezes A and trains only B, cutting optimizer memory at slight capacity cost. Enable when VRAM-bound.'],
  vera_enabled: ['VeRA 用共享随机矩阵+少量可学习向量，参数量远小于 LoRA。建议超轻量适配试验用，效果上限低于 LoRA。', 'VeRA shares frozen random matrices with tiny learnable vectors: far fewer params than LoRA with lower ceiling. For ultra-light adapters.'],
  vera_d_initial: ['VeRA 可学习缩放向量初值。建议保持 0.1。', 'Initial value of VeRA learnable scaling vector. Keep 0.1.'],
  vera_prng_key: ['VeRA 共享随机矩阵的种子；同 seed 才能复现/加载。建议保持 0 不动。', 'PRNG seed for VeRA shared matrices; must match to load/reproduce. Keep 0.'],
  mora_enabled: ['MoRA 用 r×r 方阵替代 BA 分解，参数 r²。非 A1111 原生格式，导出为专用矩阵。建议实验性使用。', 'MoRA replaces BA with an r x r square matrix (r^2 params); exports a dedicated format, not A1111-native. Experimental.'],
  delta_lora_enabled: ['Delta-LoRA 把 ΔBA 差异写入冻结底模，增强长训效果。建议默认关闭；长训且验证过稳定性再试。', 'Delta-LoRA folds the BA delta into the frozen base each step. Keep off by default; try on long validated runs.'],
  adalora_enabled: ['AdaLoRA 按 SVD 敏感度动态分配各层 rank 预算。适合异构层重要性差异大的任务；训练稍慢。', 'AdaLoRA redistributes rank budget by SVD sensitivity across layers; slower but adapts capacity.'],
  adalora_init_rank: ['AdaLoRA 初始 rank，0 = 1.5× 目标 rank。建议 0 让其自动。', 'AdaLoRA starting rank; 0 uses 1.5x target. Keep 0 for automatic.'],
  adalora_target_rank: ['AdaLoRA 最终目标 rank；0 沿用全局 network_dim。建议 0 保持一致。', 'Final AdaLoRA target rank; 0 follows network_dim. Keep 0 for consistency.'],
  adalora_beta1: ['敏感度 EMA 衰减系数。建议保持 0.85。', 'Sensitivity EMA decay. Keep 0.85.'],
  adalora_beta2: ['不确定性 EMA 衰减系数。建议保持 0.85。', 'Uncertainty EMA decay. Keep 0.85.'],
  adalora_mask_interval: ['每隔多少步更新一次 rank mask。推荐范围：100（默认）附近；过频抖动。', 'Steps between rank-mask updates. Recommended: ~100; too frequent oscillates.'],
  adalora_orth_reg_weight: ['正交正则权重，防 rank collapse。推荐范围：0.5（默认）附近。', 'Orthogonality regularization weight preventing rank collapse. Recommended: ~0.5.'],
  adalora_total_steps: ['预算调度总步数；0 自动取 max_train_steps。建议 0。', 'Total steps for budget scheduling; 0 follows max_train_steps. Keep 0.'],
  hydralora_enabled: ['HydraLoRA 多分支共享 A、多专家 B，配路由。适合多概念混合任务；显存略增。', 'HydraLoRA shares A across multiple expert B branches with routing; suits multi-concept mixes at some extra VRAM.'],
  hydralora_num_experts: ['HydraLoRA 专家分支数。推荐范围：2–4（默认 4 可减半省显存）。', 'Number of HydraLoRA expert branches. Recommended: 2-4.'],
  hydralora_top_k: ['每个样本激活的专家数。推荐范围：2（默认）以内。', 'Experts activated per sample. Recommended: 2 or fewer.'],
  hydralora_routing: ['专家路由策略。建议保持 top_k。', 'Expert routing strategy. Keep top_k.'],
  hydralora_sparse_top_k: ['只计算被选中专家（省算力）。建议开启当 top_k < 专家数时。', 'Compute only selected experts to save FLOPs. Enable when top_k < expert count.'],
  hydralora_balance_loss_weight: ['分支平衡损失权重，防止路由塌缩到单分支。推荐范围：0.01–0.1；0 关闭。', 'Load-balancing loss weight against routing collapse. Recommended: 0.01-0.1; 0 disables.'],
  krona_enabled: ['KronA 用 Kronecker 分解 ΔW，参数少于同 rank LoRA。建议显存紧且要保容量时试验。', 'KronA factorizes deltas via Kronecker products for fewer params than same-rank LoRA. Try under tight VRAM.'],
  krona_factor_in: ['KronA in 侧分解因子，0 用默认 4。建议 0。', 'KronA input-side factor; 0 uses default 4. Keep 0.'],
  krona_factor_out: ['KronA out 侧分解因子，0 用默认 64。建议 0。', 'KronA output-side factor; 0 uses default 64. Keep 0.'],
  krona_weight_decompose: ['在 KronA 上叠加 DoRA 幅度分解。建议与 dora_enabled 二选一，避免双重分解语义混乱。', 'Add DoRA magnitude decomposition on KronA. Choose either this or the main DoRA toggle, not both.'],
  krona_allora: ['KronA 模块级 ALLoRA 梯度归一化。建议实验性开启。', 'Module-level ALLoRA gradient normalization for KronA. Experimental.'],
  krona_allora_eta: ['ALLoRA 梯度缩放强度。建议保持 2。', 'ALLoRA gradient scaling strength. Keep 2.'],
  cdka_enabled: ['CDKA（不对称 Kronecker + alpha 缩放）改进 KronA。建议与 KronA 同场景试验。', 'CDKA: asymmetric Kronecker design with alpha scaling, improving KronA. Same use cases as KronA.'],
  cdka_alpha: ['CDKA 缩放分子：scale=alpha/sqrt(in)。推荐范围：16（默认）附近。', 'CDKA scaling numerator: alpha/sqrt(in). Recommended: ~16.'],
  cdka_factor_in: ['CDKA in 因子 r2，0 用默认 8。建议 0。', 'CDKA input factor r2; 0 defaults to 8. Keep 0.'],
  cdka_factor_out: ['CDKA out 因子 r1，0 用默认 2。建议 0。', 'CDKA output factor r1; 0 defaults to 2. Keep 0.'],
  cdka_weight_decompose: ['CDKA 上叠加 DoRA 幅度分解。建议实验性开启并与基线对比。', 'DoRA magnitude decomposition on CDKA. Experimental; compare with baseline.'],
  cdka_allora: ['CDKA 模块级 ALLoRA 归一化。建议实验性使用。', 'Module-level ALLoRA normalization for CDKA. Experimental.'],
  dokr_enabled: ['DoKr = LoKr 的 Kronecker 方向 + DoRA 幅度组合。建议想要 LoKr 参数量又嫌其弱时试验。', 'DoKr combines LoKr Kronecker directions with DoRA magnitude. Try when LoKr feels weak at its parameter count.'],
  dokr_alpha: ['DoKr Kronecker 缩放分子。建议保持 1.0。', 'DoKr Kronecker scaling numerator. Keep 1.0.'],
  dokr_mode: ['DoKr 训练门控：full 全训；style 仅幅度；structure 仅方向。建议 full 起步。', 'DoKR gating: full trains both; style magnitude-only; structure direction-only. Start with full.'],
  dokr_factor_in: ['DoKr in 侧分解因子偏好，0 用默认 8。建议 0。', 'DoKr input-side factor preference; 0 defaults to 8. Keep 0.'],
  dokr_factor_out: ['DoKr out 侧分解因子偏好，0 用默认 8。建议 0。', 'DoKr output-side factor preference; 0 defaults to 8. Keep 0.'],
  dokr_decompose_factor: ['w2 低秩分解 rank，0 表示完整 w2。建议 0。', 'Low-rank split for w2; 0 keeps w2 intact. Keep 0.'],
  gdlokr_mode: ['GDLoKr 广义方向模式选择。建议保持 full 与 DoKr 一致对照。', 'GDLoKr generalized-direction mode. Keep full to mirror DoKr.'],
  gdlokr_factor: ['GDLoKr 共享 Kronecker 因子，0 自动平衡。建议 0。', 'Shared GDLoKr Kronecker factor; 0 auto-balances. Keep 0.'],
  gdlokr_alpha: ['GDLoKr 缩放分子。建议保持 1.0。', 'GDLoKr scaling numerator. Keep 1.0.'],
  ed_lora_enabled: ['ED-LoRA 把文本 embedding 分解为随机+类别分量，强化文本对齐。适合文字驱动强概念任务。', 'ED-LoRA splits text embeddings into random+class components for tighter text alignment. Suits text-driven concepts.'],
  ed_lora_num_layers: ['参与分解的 text encoder 层数。推荐范围：6–24（默认 12）。', 'Text-encoder layers involved in decomposition. Recommended: 6-24 (default 12).'],
  ed_lora_num_concepts: ['概念分量数量（多概念预留）。建议保持 1。', 'Concept components count. Keep 1 for now.'],
  ed_lora_alpha: ['V_class 缩放因子。推荐范围：1.0（默认）。', 'V_class scaling factor. Recommended: 1.0.'],
  ed_lora_decomp_dim: ['Embedding 分解维度。推荐范围：32–256（默认 64）。', 'Embedding decomposition dimension. Recommended: 32-256 (default 64).'],
  ed_lora_sequence_length: ['Token 序列长度，CLIP 标准 77。建议保持 77 除非模型不同。', 'Token sequence length; CLIP standard is 77. Keep unless your model differs.'],
  merge_ed_lora_fusion: ['导出/合并时启用梯度下降式权重融合（比直接相加更少对齐损失）。不进训练循环，只影响合并产物。建议多 adapter 合并时开启。', 'Gradient-descent weight fusion at merge/export time (less alignment drift than plain add); never touches the training loop. Enable for multi-adapter merges.'],
  ed_lora_fusion_steps: ['每次融合的梯度下降步数。推荐范围：30（默认）附近。', 'Gradient steps per fusion merge. Recommended: ~30.'],
  ed_lora_fusion_lr: ['融合优化器学习率。建议保持默认 1e-3。', 'Fusion optimizer learning rate. Keep default 1e-3.'],
  ed_lora_fusion_rank: ['融合产物 rank。推荐范围：4（默认）附近。', 'Rank of the fused artifact. Recommended: ~4.'],
  reslora_enabled: ['ResLoRA 在 block 间加残差 shortcut，高 rank 提升质量。推荐范围：rank ≥32 时试验；需配套 alpha* 微调。', 'ResLoRA adds cross-block residual shortcuts, helping high ranks. Try from rank >=32 with tuned alpha*.'],
  reslora_mode: ['shortcut 合并模式（block_shortcut 等）。建议保持默认。', 'Shortcut merging mode. Keep default.'],
  reslora_window: ['残差 shortcut 回看的 block 数，1 近似无操作。推荐范围：2（默认）。', 'Blocks the shortcut looks back across; 1 is near no-op. Recommended: 2.'],
  reslora_alpha_star: ['input/middle shortcut 合并系数。建议保持 1.0。', 'Merge coefficient for input/middle shortcuts. Keep 1.0.'],
  tc_lora_enabled: ['TC-LoRA 用 hypernetwork 以时间条件生成 LoRA 权重。适合去噪过程自适应；训练更重。', 'TC-LoRA generates LoRA weights via a timestep-conditioned hypernetwork: adaptive but heavier to train.'],
  tc_lora_generation_mode: ['生成门控模式，当前运行时仅支持 gated。建议保持 gated。', 'Generation gating mode; only gated is supported now. Keep gated.'],
  tc_lora_hidden_dim: ['hypernetwork 隐层宽度。推荐范围：64–128（默认 128 可减半省显存）。', 'Hypernetwork hidden width. Recommended: 64-128.'],
  tc_lora_cond_dim: ['全局条件码宽度。建议保持 64。', 'Width of the global condition code. Keep 64.'],
  tc_lora_time_embed_dim: ['时间嵌入宽度。建议保持 64。', 'Timestep embedding width. Keep 64.'],
  tc_lora_cond_channels: ['条件 latent/control 通道数。建议与所用条件结构一致，默认 16。', 'Channels of condition latents/control. Match your conditioning; default 16.'],
  tc_lora_condition_enabled: ['启用 condition-y 编码器（额外条件输入）。建议有控制图输入时才开。', 'Enable the condition-y encoder for extra conditioning inputs. Only with control inputs.'],
  tensorring_lora_enabled: ['T-LoRA（Tensor-Ring）单步 fused 分解 W*=W0T+Δ。实验路线，建议小规模验证后再用。', 'Tensor-Ring LoRA with single-step fused decomposition W*=W0T+delta. Validate on small runs first.'],
  tensorring_factor: ['2-mode 分解尺寸 f，0 自动取 in/out 公约数。建议 0。', '2-mode decomposition size; 0 auto-picks from in/out GCD. Keep 0.'],
  tensorring_tr_rank: ['TensorRing residual rank，0 关闭该支路。建议 0。', 'TensorRing residual rank; 0 disables the branch. Keep 0.'],
  tensorring_trm_rank: ['TRM 变换 rank；0 或 ≤rank 退化为低秩 I+UV 形式。建议 0。', 'TRM transform rank; 0 or <=rank degrades to low-rank I+UV form. Keep 0.'],
  flexrank_lora_enabled: ['FlexRank 每步随机采样激活 rank，等效正则。建议过拟合倾向时试验。', 'FlexRank samples the active rank each step, acting as regularization. Try when overfitting.'],
  flexrank_lora_rank_range_min: ['FlexRank 采样激活 rank 下界；上界沿用 network_dim。推荐范围：dim 的 25%–50%。', 'Lower bound of sampled active rank (upper bound = network_dim). Recommended: 25-50% of dim.'],
  tlora_min_rank: ['T-LoRA 动态 rank 下界。建议保持 1。', 'Dynamic rank lower bound for T-LoRA. Keep 1.'],
  tlora_rank_schedule: ['动态 rank 调度策略（constant/linear/geometric，后端支持集）。建议 constant 起步。', 'Dynamic-rank schedule (constant/linear/geometric per backend). Start with constant.'],
  tlora_orthogonal_init: ['对 lora_down 用正交初始化提升早期稳定。建议默认关闭，不稳定时试开。', 'Orthogonal init for lora_down improves early stability. Off by default; try when unstable.'],
  pissa_init: ['PiSSA 用 SVD 主奇异分量初始化 LoRA，收敛更快更好。建议中大数据集开启；导出兼容性见导出模式选项。', 'PiSSA initializes LoRA from leading SVD components for faster convergence. Good for medium/large datasets; check export mode for compatibility.'],
  pissa_method: ['PiSSA 分解算法：rsvd 随机化快，svd 精确慢。建议保持 rsvd。', 'PiSSA factorization algorithm: fast randomized rsvd vs exact svd. Keep rsvd.'],
  pissa_niter: ['rSVD 幂迭代次数，越大越准越慢。建议保持 2。', 'Power iterations for randomized SVD; more is accurate but slower. Keep 2.'],
  pissa_oversample: ['rSVD 过采样维度。建议保持 8。', 'Oversampling dimension for randomized SVD. Keep 8.'],
  pissa_apply_conv2d: ['PiSSA 同样作用于 1x1 Conv。建议网络含 Conv 目标且追求一致时开启。', 'Apply PiSSA init to 1x1 Convs too. Enable for consistent treatment when Conv targets exist.'],
  pissa_export_mode: ['PiSSA 模型存为标准 LoRA 的导出方式（底模是否吸收残差）。建议 lora_compatible 保证通用加载。', 'How PiSSA models export to standard LoRA (whether the base absorbs residuals). lora_compatible loads anywhere.'],
  adapter_init_strategy: ['统一初始化入口：default 标准 LoRA；pissa/olora/loftq 特殊初始化（仍走请求管线，不加新入口）。建议 default，需要快速收敛换 pissa。', 'Unified init entry: default standard; pissa/olora/loftq special inits inside the request pipeline. Keep default; pick pissa for faster convergence.'],
  loftq_bits: ['LoftQ 量化位宽（fake-quant 初始化，不是持久 4bit 底座）。推荐范围：4（默认）或 8。', 'LoftQ quantization bits (fake-quant init, not a persistent 4-bit base). Recommended: 4 or 8.'],
  loftq_quant_type: ['量化粒度：rowwise 按输出通道，tensorwise 整张量。建议 rowwise（默认，精度更好）。', 'Quant granularity: per-output-channel rowwise vs whole-tensor tensorwise. rowwise keeps better accuracy.'],
  adapter_init_export_mode: ['特殊初始化产物的导出方式：auto 在最终保存时转成可直接加载到原底模的 LoRA。建议 auto。', 'Export handling for special inits: auto converts to a base-loadable LoRA at save time. Keep auto.'],
  olora_enabled: ['OLoRA 正交初始化路线。建议与 PiSSA 同类场景二选一试验。', 'OLoRA orthogonal-init variant. Compare head-to-head with PiSSA for your case.'],

  // ── 目标层 ──
  lora_target_linear: ['限定 LoRA 注入的 Linear 层列表（留空=全量 attention+MLP 常规集合）。建议留空走默认；精调时排除干扰层。', 'Restrict LoRA target Linear modules (empty = standard attention+MLP set). Leave empty; prune noisy layers for fine control.'],
  target_modules: ['LyCORIS 目标模块选择。建议保持默认全集，缩小目标用于排查冲突。', 'Target module selection for LyCORIS. Keep the default full set; narrow it for debugging.'],
  lora_layer_no_conv: ['不含 Conv 层（只训 Linear）。建议纯注意力学习时开启以减少文件体积。', 'Skip Conv layers entirely. Enable to slim files when learning attention-only behavior.'],
  enable_block_weights: ['按 U-Net 编码器/中部/解码器分层设置学习率权重（down/mid/up 三段 JSON）。仅 networks.* 模块生效。建议默认关闭，分区过拟/欠拟时用。', 'Assign per-section LR weights across encoder/mid/decoder via down/mid/up tables. Works with networks.* only; use to fix section-level fit issues.'],
  down_lr_weight: ['U-Net 下段（encoder）逐层 LR 权重表。建议 0–1 之间；低于阈值的 block 视为置零。', 'Per-layer LR weights for the encoder section, 0-1; below threshold counts as zeroed.'],
  mid_lr_weight: ['U-Net 中部 LR 权重。建议 0–1。', 'Mid-section LR weight, 0-1.'],
  up_lr_weight: ['U-Net 上段（decoder）逐层 LR 权重表。建议 0–1。', 'Per-layer LR weights for the decoder section, 0-1.'],
  block_lr_zero_threshold: ['权重低于该阈值时该 block 完全置零（跳过训练）。建议 0 默认；想真正关掉某段给 0.01。', 'Blocks whose weight falls below this are fully zeroed. Give 0.01 to hard-disable a section.'],

  // ── 文本编码器 / UNet 选择 ──
  train_text_encoder: [{ zh: '同时微调 CLIP 文本编码器（运行时默认语义）；关闭则仅训练 U-Net/DiT。触发词理解差、词汇绑定弱时建议开启，TE 学习率另设为 UNet 的 1/2～1/10。', en: 'Fine-tune the CLIP text encoder as well (runtime-default semantics); off trains U-Net/DiT only. Enable when trigger-word binding is weak and set TE LR to 1/2-1/10 of UNet.' }],
  network_train_unet_only: ['只训练 U-Net/DiT 主干（TE 冻结）。建议概念视觉为主、无需新词绑定时开启（多数 LoRA 场景）。', 'Train the U-Net/DiT backbone only (TE frozen). Standard for most LoRA goals focused on visuals rather than new vocabulary.'],
  network_train_text_encoder_only: ['只训练文本编码器（主干冻结）。建议仅做词汇/风格语言绑定时开启。', 'Train the text encoder only (backbone frozen). For vocabulary/language binding experiments only.'],

  // ── Anima 注入面 ──
  anima_train_self_attn: ['把 Self-Attention（q/k/v/out）注入 LoRA。建议保持开启（默认 true），是概念学习主力。', 'Inject LoRA into Self-Attention (q/k/v/out). Keep on; primary learning surface.'],
  anima_train_cross_attn: ['把 Cross-Attention 注入 LoRA，强化图文对齐。建议文本绑定弱时保持开启。', 'Inject Cross-Attention to strengthen image-text alignment. Keep on when text binding is weak.'],
  anima_train_mlp: ['把 MLP（layer1/2）注入 LoRA，增加容量。建议数据多时开启，小数据易过拟合。', 'Inject MLP layers for extra capacity. Good with larger datasets; can overfit tiny ones.'],
  anima_train_adaln: ['把 AdaLN modulation 投影注入 LoRA。常用于角色/风格层权重，建议保持开启（默认 true）。', 'Inject AdaLN modulation projections; common for character/style weight. Keep on (default).'],
  anima_self_attn_lr: ['Self-Attention 分组独立学习率，覆盖主 LR。推荐范围：0 沿用主 LR；分组失衡时可单独降至一半。', 'Standalone Self-Attention group LR; 0 follows the base LR. Keep 0 unless a group misbehaves.'],
  anima_cross_attn_lr: ['Cross-Attention 分组独立学习率，覆盖主 LR。推荐范围：0 沿用主 LR；文本影响过强时降至一半。', 'Standalone Cross-Attention LR; 0 follows base. Halve it if text influence dominates.'],
  anima_mlp_lr: ['MLP 分组独立学习率，覆盖主 LR。推荐范围：0 沿用主 LR 即可。', 'Standalone MLP-group LR; 0 follows base.'],
  anima_mod_lr: ['AdaLN Modulation 分组独立学习率，覆盖主 LR。推荐范围：0 沿用主 LR。', 'Standalone AdaLN-modulation LR; 0 follows base.'],
  anima_llm_adapter_lr: ['LLM Adapter 分组独立学习率（需开 anima_train_llm_adapter）。推荐范围：0 沿用主 LR。', 'Standalone LLM-adapter LR (applies when anima_train_llm_adapter is on); 0 follows base.'],
  alpha_self_attn: ['Self-Attention 组 alpha 缩放。建议保持 1。', 'Alpha scaling for the Self-Attention group. Keep 1.'],
  alpha_cross_attn: ['Cross-Attention 组 alpha。建议保持 1。', 'Alpha scaling for the Cross-Attention group. Keep 1.'],
  alpha_mlp: ['MLP 组 alpha。建议保持 1。', 'Alpha scaling for the MLP group. Keep 1.'],
  alpha_adaln: ['AdaLN 调制组 alpha。建议保持 1。', 'Alpha scaling for the AdaLN group. Keep 1.'],
  alpha_llm_adapter: ['LLM Adapter 组 alpha。建议保持 1。', 'Alpha scaling for the LLM-adapter group. Keep 1.'],
};
