// SPDX-License-Identifier: LicenseRef-PolyFormNoncommercial-1.0.0
// desc 文案表 —— 高级/专家区（二）：表征对齐、遗忘防护、蒸馏诊断、分布式、缓存引擎、
// 模块 offload、极端落盘、LoKr/量化导出、监控与 SafeGuard、DPO/偏好。
export default {
  // ── REPA / 表征对齐族 ──
  repa_target_provider: ['REPA 对齐目标提供方：dinov2/jina 等视觉编码器；none 且无 target 时 fail-closed（不做伪对齐）。建议有明确目标编码器再选。', 'Provider of REPA alignment targets (DINOv2/Jina vision encoders); none fails closed rather than faking alignment. Pick only with a real encoder available.'],
  repa_mode: ['REPA 对齐模式（absolute 直接对齐 / relational 关系结构）。建议 absolute 起步。', 'REPA alignment mode: absolute direct matching vs relational structure. Start with absolute.'],
  repa_loss_type: ['对齐损失类型：cosine 只看方向（默认）更稳；mse 看幅度。建议 cosine。', 'Alignment loss: cosine direction-only (stable default) vs mse magnitude-aware. Prefer cosine.'],
  repa_loss_weight: ['REPA 额外对齐 loss 权重；0 近似不生效。建议从小权重 0.1–0.5 试。', 'Auxiliary alignment weight; 0 disables in practice. Probe from 0.1-0.5.'],
  repa_gram_weight: ['relational 臂的 Gram 权重；0 回落主权重。建议 0 起步。', 'Gram-term weight for the relational arm; 0 falls back to the main weight. Start 0.'],
  repa_gram_spatial_norm: ['token L2 归一后再算 Gram。建议保持 true（默认）。', 'L2-normalize tokens before Gram computation. Keep true.'],
  repa_capture_modules_auto: ['目标模块为空时按模型族自动选单层 mid hook。建议保持 true（默认）。', 'Auto-picks a single mid-layer hook per family when targets are empty. Keep true.'],
  repa_capture_max_layers: ['最多挂几个 DiT hook；loss 只用最后一层。建议 1（默认）。', 'Max DiT hooks attached; loss uses the last one. Keep 1.'],
  repa_encode_every_n_steps: ['每 N 步才执行 VAE decode+编码器，控制开销；1=每步最贵。推荐范围：4（16G 推荐档）。', 'Runs encoder/VAE decode every N steps to bound cost (1 = every step). Recommended: 4 on 16 GB.'],
  repa_encoder_device: ['DINOv2/Jina 权重所在设备。推荐范围：默认 cpu 省显存；显存富余时选 cuda 更快。', 'Device hosting the DINOv2/Jina weights. Recommended: cpu to save VRAM (default); cuda when headroom allows.'],
  repa_encoder_image_size: ['编码器输入边长；0 用各自默认（dino≈224/jina≈512）。建议 0。', 'Encoder input edge; 0 keeps per-model defaults (dino~224, jina~512). Keep 0.'],
  repa_projection_dim: ['对齐前投影维；0 不投影或按后端默认。建议 0。', 'Projection width before aligning; 0 uses backend default. Keep 0.'],
  repa_token_pool_size: ['对齐/Gram 前池化到 ≤N×N（16≈256 tokens）。建议 16。', 'Pools tokens to at most N x N before alignment/Gram (16 ~ 256 tokens). Keep 16.'],
  repa_patch_size: ['DiT patch 大小（relational pool 用，anima 通常 2）。建议 2。', 'DiT patch size used by relational pooling; anima usually 2.'],
  repa_log_memory: ['首次真正计算 REPA loss 时打印 shape/pool 显存日志。建议保持 true 便于评估开销。', 'Logs shapes and memory on first real REPA loss. Keep true to gauge overhead.'],
  repa_allow_text_fallback: ['允许用 text embedding 冒充对齐目标的 legacy 行为。建议关闭（伪对齐无益）。', 'Legacy fallback aligning against text embeddings — fake signal. Keep off.'],
  softrepa_enabled: ['SoftREPA：按 schedule 渐进软化的表征对齐。建议与 REPA 二选一对比。', 'SoftREPA ramps alignment strength over a schedule; compare head-to-head with plain REPA.'],
  softrepa_min_weight: ['schedule 起始权重。建议 0 从零渐入。', 'Schedule starting weight. Ramp from 0.'],
  softrepa_max_weight: ['schedule 结束权重。建议 ≤1。', 'Schedule ending weight. At most about 1.'],
  softrepa_schedule: ['权重随进度调度方式（linear 等）。建议 linear。', 'How weight follows progress; linear works well.'],
  softrepa_sigma_min: ['仅在该 σ 窗口内对齐的下界。建议 0 全程。', 'Lower bound of the alignment sigma window. 0 covers all.'],
  softrepa_sigma_max: ['σ 窗口上界。建议 1 全程。', 'Upper bound of the sigma window. 1 covers all.'],
  reft_enabled: ['ReFT（Representation Fine-Tuning）：干预中间层表征而非权重，参数极少。建议仅作实验性探测使用。', 'ReFT steers intermediate representations instead of weights. Experimental; enable only to probe this low-parameter route.'],
  reft_rank: ['干预低秩维度。推荐范围：8（默认）附近。', 'Rank of the intervention subspace. Recommended: ~8.'],
  reft_init_scale: ['干预矩阵初始缩放。建议 0 保证从零介入。', 'Initial scale of intervention matrices; start from 0.'],

  // ── 遗忘防护 / 重要性采样 ──
  dop_enabled: ['DOP 差异输出保留：约束输出不偏离基座，防灾难遗忘。建议概念易被冲掉时开启。', 'DOP anchors outputs near the base model to prevent catastrophic forgetting. Enable when concepts wash out.'],
  dop_weight: ['DOP 正则权重。推荐范围：0.1（默认）；过大压制新概念。', 'DOP regularization weight. Recommended: 0.1; higher strangles new concepts.'],
  dop_interval: ['每 N 步应用一次 DOP（1=每步）。建议 1。', 'Apply DOP every N steps. Keep 1.'],
  dop_start_step: ['从此步开始应用 DOP（0=立即）。建议 0。', 'First step where DOP applies. Keep 0.'],
  dop_target: ['作用位置：output 最终噪声预测 / features 中间特征。建议 output。', 'Where DOP acts: final output or intermediate features. Keep output.'],
  dop_detach_reference: ['对参考侧 detach 防梯度回传基座。安全旋钮建议保持 true。', 'Detaches the reference side so gradients never reach the base. Safety toggle, keep true.'],
  coreset_enabled: ['Coreset 按 loss 历史把样本分级 easy/hard/toxic 做重要性采样。建议数据质量参差时开启。', 'Coreset grades samples easy/hard/toxic from loss history for importance sampling. Helps uneven-quality datasets.'],
  coreset_classify_after: ['累计多少步后开始分级。建议 500（默认）附近。', 'Steps before grading begins. Around 500.'],
  coreset_auto_classify_after: ['自动重分级的间隔步数。建议 50。', 'Re-grading interval in steps. Keep 50.'],
  coreset_easy_threshold: ['easy 判定的 loss 阈值。建议 0.1（默认）附近。', 'Loss threshold marking a sample easy. Around 0.1.'],
  coreset_hard_loss_threshold: ['hard 判定的 loss 阈值倍数。建议 1.5（默认）。', 'Loss multiple marking hard samples. Keep 1.5.'],
  coreset_toxic_std_threshold: ['toxic 判定的标准差倍数。建议 3（默认）。', 'Std-dev multiple flagging toxic outliers. Keep 3.'],
  coreset_easy_weight: ['easy 样本采样权重。建议 1 保持参与。', 'Sampling weight for easy samples. Keep 1.'],
  coreset_hard_weight: ['hard 样本采样权重。建议 1–2 强调困难。', 'Weight for hard samples. 1-2 emphasizes them.'],
  coreset_toxic_weight: ['toxic 样本权重；0 表示直接跳过。建议 0 屏蔽异常样本。', 'Toxic-sample weight; 0 skips them entirely. Keep 0.'],
  coreset_report_enabled: ['输出分级报告便于审查异常样本。建议保持 true。', 'Writes the grading report for auditing bad samples. Keep on.'],
  coreset_report_every_n_epochs: ['每 N epoch 写一次报告。建议 1。', 'Report cadence in epochs. Keep 1.'],
  coreset_report_top_k: ['报告列出 top-k 样本数。建议 20。', 'Rows listed per report. Keep 20.'],
  hard_negative_mining_enabled: ['只回传 loss 最高的 top-k% 样本梯度，聚焦难例。建议难例拖累整体时开启。', 'Backprops only the top-k% highest-loss samples to focus on hard cases. Use when easy samples dilute learning.'],
  hard_negative_mining_ratio: ['保留 top-k% 困难样本比例。推荐范围：0.5（保留 50%，默认）。', 'Fraction of hardest samples kept. Recommended: 0.5.'],
  hard_negative_mining_mode: ['挖掘模式：topk 按比例 / threshold 按阈值。建议 topk。', 'Mining mode: top-k fraction or threshold-based. topk simpler.'],
  hard_negative_mining_threshold_multiplier: ['threshold 模式的阈值系数（threshold = mean × k）。建议 1.2。', 'Threshold multiplier over mean loss in threshold mode. Keep 1.2.'],
  hard_negative_mining_warmup_steps: ['前 N 步不启用让训练先稳定。建议 100。', 'Warm-up steps before mining kicks in. Keep 100.'],
  lisa_enabled: ['LISA 稀疏激活：周期性只激活部分参数子集训练。建议大 adapter 省显存试验。', 'LISA periodically activates only a subset of parameters, cutting optimizer memory on big adapters.'],
  lisa_active_ratio: ['每轮激活的参数比例。推荐范围：0.2（默认）附近。', 'Activated fraction per cycle. Recommended: ~0.2.'],
  lisa_interval: ['每隔 N 步重采样激活集。建议 1（默认）。', 'Resampling cadence of active subsets. Keep 1.'],
  pcgrad_enabled: ['PCGrad 把冲突梯度投影到正交方向，多任务/多轴损失时减冲突。建议组合多损失时开。', 'PCGrad projects conflicting gradients orthogonally; useful with several combined losses.'],
  pcgrad_reduction: ['投影前的梯度归约方式 mean/sum。建议 mean。', 'Reduction before projection. mean is standard.'],
  pcgrad_conflict_threshold: ['余弦相似度低于该值视为冲突（0=全部投影）。建议 0。', 'Cosine below this counts as conflict (0 = project all). Keep 0.'],
  forgetting_probe_enabled: ['监测训练中的概念遗忘信号并报告。建议长训多概念开启观察。', 'Monitors concept-forgetting signals during training and reports them. Useful on long multi-concept runs.'],
  forgetting_probe_interval: ['每隔多少优化步探测一次。建议 50。', 'Probe cadence in optimizer steps. Keep 50.'],
  forgetting_probe_num_anchors: ['对比用锚点样本数。建议 4。', 'Anchor samples used for comparison. Keep 4.'],
  grad_cosine_enabled: ['梯度方向余弦监测（纯诊断）。建议诊断期开。', 'Gradient-cosine monitoring, purely diagnostic.'],
  fim_scan_enabled: ['Fisher 信息矩阵扫描：估计各层敏感度辅助 rank 分配。建议调 rank 布局前跑一次。', 'FIM scan estimates per-layer sensitivity to guide rank allocation. Run before redesigning ranks.'],
  fim_scan_calib_steps: ['反传校准步数。建议 8（默认）。', 'Calibration backward steps for the scan. Keep 8.'],
  fim_scan_r_min: ['扫描建议 rank 下界。建议 8。', 'Lower bound of suggested ranks. Keep 8.'],
  fim_scan_r_max: ['rank 上界。建议 64。', 'Upper bound of suggested ranks. Keep 64.'],
  fim_scan_suggest_ratio: ['标记为 suggested 的层占比。建议 0.5。', 'Fraction of layers flagged as suggested. Keep 0.5.'],
  fera_enabled: ['FERA 特征探测分支。建议实验性开启观察。', 'FERA feature-probe branch. Experimental observation only.'],
  fera_gate_init: ['FERA 门控初值。建议 0。', 'Initial FERA gate value. Keep 0.'],
  fractional_grad_damping_enabled: ['分数阶梯度阻尼：对历史梯度做分数阶平滑。实验特性建议默认关闭。', 'Fractional-order damping smooths gradients over history. Experimental; off by default.'],
  fractional_grad_damping_order: ['阻尼阶数 α∈(0,1]，越小越平滑。建议 0.5。', 'Order alpha in (0,1]; smaller smooths more. Keep 0.5.'],
  fractional_grad_damping_window: ['历史窗口长度。建议 4（默认）。', 'History window length. Keep 4.'],

  // ── LayerSync / SRA2-HASTE / 多维引导 ──
  layersync_enabled: ['LayerSync 层自对齐：同网络浅层对齐深层（无外挂编码器）。可能略增激活显存。建议语义漂移明显时试。', 'LayerSync self-aligns shallow layers to deeper ones without an external encoder, costing a bit of activation VRAM. Try when semantics drift.'],
  layersync_weight: ['辅助对齐权重；>0 才生效。推荐范围：从 0.2 试起。', 'Auxiliary weight; effective above 0 (try 0.2).'],
  layersync_every_n_steps: ['每 N 步算一次以控税（1=每步）。建议 1–4。', 'Compute every N steps to bound overhead (1 = each step). 1-4 sensible.'],
  layersync_student_block: ['student 块索引（0-based 较浅层），-1 自动取约 1/3 深度。建议 -1。', 'Student block index; -1 auto-picks ~1/3 depth. Keep -1.'],
  layersync_teacher_block: ['teacher 块索引（须 > student），-1 自动约 2/3 深度。建议 -1。', 'Teacher block index (must exceed student); -1 auto ~2/3 depth. Keep -1.'],
  sra2_haste_enabled: ['SRA2-HASTE 中间层表征对齐 + HASTE 自适应调度。建议与 REPA 族二选一。', 'SRA2-HASTE aligns mid-layer representations with an adaptive schedule; choose one family among alignment aids.'],
  sra2_haste_base_weight: ['对齐损失基础权重。建议 1（默认）。', 'Base weight of the alignment loss. Keep 1.'],
  sra2_haste_loss_type: ['对齐损失类型：cosine/l2/l1。建议 cosine。', 'Alignment loss type; cosine is robust.'],
  sra2_haste_start_step: ['从此优化步开始生效。建议 0。', 'First step the loss applies. Keep 0.'],
  sra2_haste_stop_step: ['-1 不提前结束；≥0 到此停。建议 -1。', '-1 runs to completion; >=0 stops there. Keep -1.'],
  sra2_haste_decay_start_step: ['开始衰减的步数；-1 不衰减。建议 -1。', 'Step where decay begins; -1 disables decay. Keep -1.'],
  sra2_haste_decay_end_step: ['衰减到 min_weight 的终点步。建议 -1 配合上项。', 'Step where decay reaches min weight; pairs with decay start.'],
  sra2_haste_min_weight: ['衰减下限权重。建议 0。', 'Floor after decay. Keep 0.'],
  sra2_haste_plateau_patience: ['平台早停耐心；0 关闭。建议 0。', 'Patience for plateau early-stop; 0 disables. Keep 0.'],
  sra2_haste_min_relative_improvement: ['判定改进的最小相对阈值。建议 0。', 'Minimum relative improvement counted. Keep 0.'],
  sra2_haste_normalize_targets: ['对齐前归一化 target。建议保持 true（默认）。', 'Normalizes targets before aligning. Keep true.'],
  sra2_haste_stop_grad_target: ['target 侧 stop-gradient。建议保持 true。', 'Stops gradient into the target side. Keep true.'],
  multi_aspect_guidance_enabled: ['多维审美引导：style/character 等 scorer 加权引导。建议审美向任务开启。', 'Multi-aspect guidance weights style/character scorers into the objective. For aesthetics-driven goals.'],
  multi_aspect_guidance_weight: ['总引导损失权重。建议 0 起步小值试探。', 'Total guidance weight. Probe upward from small values.'],
  multi_aspect_guidance_default_scorer: ['未指定自定义 scorer 时使用的默认评分器。建议 latent_style_contras 默认。', 'Scorer used when no custom one is set. latent_style_contras default is reasonable.'],
  multi_aspect_guidance_adaptive_weights: ['按维度自适应加权各 scorer。建议保持 true。', 'Adapts scorer weights per aspect automatically. Keep true.'],
  multi_aspect_guidance_min_t: ['计入引导的 σ 下界。建议 0。', 'Lower σ bound applying guidance. Keep 0.'],
  multi_aspect_guidance_max_t: ['计入引导的 σ 上界。建议 1。', 'Upper σ bound applying guidance. Keep 1.'],

  // ── Loss 状态机 / 数据集智能融合 ──
  loss_state_enabled: ['逐图 Loss 状态机：跨 epoch 跟踪每个样本状态并合入难度权重。建议排查坏图时开启。', 'Per-image loss state machine folded into difficulty weighting; great for hunting bad images.'],
  loss_state_fusion_mode: ['状态结果与权重的融合模式（loss 主导等）。建议 loss 默认。', 'How state verdicts fuse into weights; loss-led default.'],
  loss_state_aesthetic_weight: ['审美分融合强度。建议 0 关闭起步。', 'Aesthetic-score fusion strength; start 0.'],
  loss_state_num_bins: ['时间步分桶数。建议 32（默认）。', 'Timestep bins for state tracking. Keep 32.'],
  loss_state_warmup_window: ['升温窗口长度。建议 3。', 'Warm-up window length. Keep 3.'],
  loss_state_healthy_quantile: ['健康残差分位线。建议 0.4。', 'Quantile marking healthy residuals. Keep 0.4.'],
  loss_state_plateau_slope: ['判定饱和的斜率阈值。建议 0.001。', 'Slope threshold marking saturation. Keep 0.001.'],
  loss_state_lrugged_hits: ['平坦高位阈值（残差高位占比）。建议 0.9。', 'High-residual share marking flat-lining. Keep 0.9.'],
  loss_state_lrugged_votes: ['退化确认票数。建议 3。', 'Confirmations before declaring degradation. Keep 3.'],
  loss_state_lost_votes: ['卡死追加票数。建议 2。', 'Extra votes to declare stuck. Keep 2.'],
  loss_state_watching_rise_epochs: ['观察确认所需 epoch 数。建议 1。', 'Epochs of watch time before confirming. Keep 1.'],

  // ── 模块级 Offload / 极端落盘 ──
  module_offload_enabled: ['模块级 Offload 总开关：按比例把冻结 Linear/Conv 常驻 CPU。建议显存不足且块交换不够用时开启。', 'Master switch moving a share of frozen Linear/Conv modules to CPU. Next lever when block swap is not enough.'],
  module_offload_profile_enabled: ['启用预设 offload 配置（否则手动子项）。建议保持 true 走预设。', 'Use the preset profile instead of manual subfields. Keep true.'],
  module_offload_profile: ['预设档：balanced 平衡；aggressive 更省更慢；conservative 快但省得少；custom 手动。建议 balanced。', 'Offload preset: balanced, aggressive (leaner slower), conservative (faster), custom. Keep balanced.'],
  module_offload_enhanced: ['增强调度版模块 offload。建议 balanced 档不够时再开。', 'Enhanced scheduling variant of module offload. Try when the preset falls short.'],
  module_offload_ratio: ['参与 offload 的可管理模块占比 0-100（不是目标显存占比）。推荐范围：30–70 试探。', 'Share of manageable modules offloaded (not a VRAM target). Probe 30-70%.'],
  module_offload_backbone_ratio: ['主干覆盖比例 0-100，留空继承总比例。建议留空。', 'Override share for backbone modules; empty inherits the global ratio. Leave empty.'],
  module_offload_text_encoder_ratio: ['TE 覆盖比例 0-100，留空继承总比例。建议留空。', 'Override share for text encoders; empty inherits global. Leave empty.'],
  module_offload_min_param_mb: ['只有参数大于此值的模块才 offload，避免小包传输开销。建议 10 MB（默认）。', 'Only modules above this size get offloaded to avoid tiny transfers. Keep 10 MB.'],
  module_offload_include_patterns: ['只 offload 名称匹配这些模式（逗号分隔）的模块。建议精确定位大层时使用。', 'Comma-separated name patterns restricting what gets offloaded. For surgical control.'],
  module_offload_exclude_patterns: ['排除不参与 offload 的模块名模式。建议保护关键层时使用。', 'Name patterns excluded from offloading. Protect sensitive layers here.'],
  module_offload_prefetch_enabled: ['提前预取下一个要用的模块减少等待。建议保持 true（默认）。', 'Prefetches the next module ahead of use. Keep true.'],
  module_offload_prefetch_mode: ['预取实现：experimental 是当前唯一支持模式。建议保持。', 'Prefetch implementation; experimental is the only mode today.'],
  module_offload_verify_state: ['每次传输后校验模块状态（明显降速）。建议仅排查数值问题时开。', 'Verifies module state after each transfer, notably slower. Debugging aid only.'],
  tiered_residency_spill_enabled: ['极端内存模式：冻结底座权威副本放磁盘换 RAM，实测 Anima 约 1.9 倍步时。建议仅在内存不足的机器上作兜底开启。', 'Spills frozen-base masters to disk trading RAM for IO (~1.9x step time measured on Anima). Enable only as a last resort on RAM-starved machines.'],
  tiered_residency_spill_root: ['落盘目录：强烈建议 NVMe SSD；机械盘/U 盘必负收益。留空用系统临时目录。', 'Spill folder: NVMe SSD strongly advised; HDD/USB always loses. Empty uses system temp.'],
  tiered_residency_spill_allow_backbone: ['允许 DiT 主干块真正落盘——省 RAM 大头。关闭时只落 VAE/TE 收效甚微。', 'Lets DiT blocks actually spill: the main RAM win. Without it savings are marginal.'],
  tiered_residency_spill_active_eviction: ['权重拷入显存后立即归还内存页（防写页面文件、护 SSD 寿命的关键开关）。建议开启配套使用。', 'Returns host pages right after upload, avoiding pagefile churn and SSD wear. Enable alongside spilling.'],
  tiered_residency_spill_page_lookahead: ['提前几块预读内存页（缺页 4KB 同步很贵）。推荐范围：2（默认）～4。', 'Blocks of read-ahead for page faults. Recommended: 2-4.'],
  tiered_residency_spill_allow_text_encoders: ['文本编码器也参与落盘（读得少代价低）。建议保持 true。', 'Includes TE weights in spilling; cheap since reads are rare. Keep true.'],
  tiered_residency_spill_allow_vae: ['VAE 参与落盘（只在编解码用到）。建议保持 true。', 'Includes VAE weights; touched only during encode/decode. Keep true.'],
  tiered_residency_spill_prefer_copy: ['慢盘模型+快盘落盘目录时开场复制到快盘（宁可写一次别每块都读慢盘）。建议该场景才开。', 'Copies slow-disk models onto the fast spill drive once instead of reading the slow disk every block. Only for that scenario.'],
  tiered_residency_spill_min_free_gb: ['磁盘至少保留空闲 GB，不足回落内存防写满。建议 4–16 视盘容量。', 'Free GB the disk must keep; otherwise fall back to RAM. 4-16 by drive size.'],
  tiered_residency_spill_cleanup: ['训练结束删除落盘文件（关掉会残留几 GB）。建议保持 true。', 'Deletes spill files at train end or leaves GBs behind. Keep true.'],

  // ── 无损缓存替换引擎 ──
  lossless_cache_replacement_mode: ['磁盘缓存引擎布局：off=每文件 npz/safetensors 原路径；shard 整片少文件适合 HDD。建议默认 off。', 'Cache engine layout: off keeps per-file stores; sharded layout suits HDDs. Default off.'],
  lossless_cache_replacement_read_mode: ['读取模式：prefetch_thread 后台线程预取（默认）/mmap 直读等。建议 prefetch_thread。', 'Read path: background-thread prefetch (default) vs mmap direct. Keep prefetch_thread.'],
  lossless_cache_replacement_prefetch_depth: ['prefetch 队列深度。建议 2（默认）。', 'Prefetch queue depth. Keep 2.'],
  lossless_cache_replacement_strict: ['读取时校验 CRC32/fingerprint，不符自动重建。建议保持 true 防脏缓存。', 'CRC32/fingerprint checks rebuild corrupt caches automatically. Keep true.'],
  lossless_cache_replacement_fallback_to_raw: ['sidecar 缺失损坏时回落原版 npz。建议保持 true 提高鲁棒。', 'Falls back to original npz when sidecars are missing/broken. Keep true.'],
  lossless_cache_replacement_decoded_payload_cache: ['解码后的 latent 载荷驻留内存减少重复 IO。建议内存充足且重复跑同集时开启。', 'Keeps decoded latents resident to cut repeat IO. Good with spare RAM and repeated passes.'],
  lossless_cache_replacement_decoded_payload_cache_max_bytes: ['载荷池字节上限；0 不限制。建议设上限防 OOM（如 32GB 内存给 16e9）。', 'Byte cap for the payload pool (0 unlimited). Set a cap to avoid OOM.'],

  // ── 图片解码后端 ──
  image_decode_backend: ['图片解码后端：pil 最兼容；pil_lru 按 mtime/大小缓存已解码 RGB。建议大数据集 SSD 上 pil_lru。', 'Image decoder: pil safest; pil_lru caches decoded RGB keyed by mtime/size. pil_lru shines on big local sets.'],
  image_decode_cache_size: ['每个 worker 的解码 LRU 容量（张数），0 关闭。建议 64–256 按内存。', 'Per-worker decoded-image LRU entries; 0 disables. 64-256 by free RAM.'],

  // ── 导出/量化杂项 ──
  export_comfy_int8_engine: ['Comfy INT8 引擎实现：convrot 真旋转 group-RHT（默认，精度更好）；rowwise 无旋转更快。建议 convrot。', 'Comfy INT8 engine: convrot real rotation (better fidelity) vs rowwise no-rotation (faster). Prefer convrot.'],
  export_comfy_int8_groupsize: ['ConvRot group size，必须是 4 的幂。建议 256（默认）。', 'ConvRot group size, power of four. Keep 256.'],
  layer_precision_policy: ['分层精度策略：保护输入输出/时间调制/Norm 等敏感层。建议 sensitive_bf16 默认。', 'Which sensitive layers keep higher precision (I/O, time-mod, norms). sensitive_bf16 recommended.'],
  layer_precision_default: ['普通候选层默认格式。建议 int8_convrot 平衡档。', 'Default format for ordinary quantizable layers. int8_convrot balances quality.'],
  layer_precision_sensitivity_mode: ['层敏感度评估方式：weight 有界重建误差 / activation_geometry 能量聚合 / off。建议 off 起步。', 'Sensitivity estimator for layer choices. Start off; enable when tuning precision maps.'],
  tuneqdm_warmup_steps: ['scale 参数组 LR 线性升温暖步（0→1 乘子），防初期抖动破坏量化底座；0 不升温。建议 500（默认）。', 'Linear LR warmup (0->1 multiplier) for scale groups protecting quantized bases; 0 disables. Keep 500.'],
  rank_comp_enabled: ['低秩精度回补：用冻结低秩分支补回 4bit 量化误差（r16 约 0.4% 主干显存）。建议量化底模质量受损时开启。', 'Low-rank compensation restores accuracy lost to 4-bit bases (~0.4% backbone VRAM at r16). Enable when quantization visibly hurts.'],
  rank_comp_rank: ['回补秩：越大越准越占显存（r16 削误差约 32%，r64 约 65%）。推荐范围：16–64。', 'Compensation rank: r16 removes ~32% error, r64 ~65%, costing more VRAM. Range 16-64.'],
  rank_comp_activation_weighted: ['按通道激活能量加权的分解（最小化输出误差而非权重误差，实测再削约 16 个百分点），需缓存在场否则自动降级。建议量化底模质量受损时开启。', 'Activation-energy-weighted factorization minimizing output error (~16 points better). Recommended on; auto-degrades without caches in place.'],
  rank_comp_calibration_batches: ['激活加权用多少个缓存样本估通道能量。建议 8（默认）。', 'Cached samples used to estimate channel energy. Keep 8.'],
  rank_comp_calibration_ridge: ['能量估计 ridge 正则防除零。建议 1e-3。', 'Ridge term stabilizing energy inversion. Keep 1e-3.'],
  rank_comp_niter: ['rSVD 幂迭代次数。建议 4（默认）。', 'Power iterations for randomized SVD. Keep 4.'],
  rank_comp_oversample: ['rSVD 过采样列数提高小奇异值精度。建议 8（默认）。', 'Oversampling columns improving small-singular-value accuracy. Keep 8.'],
  rank_comp_refine_iters: ['低秩↔量化残差交替拟合轮数（2 轮后收益递减）。建议 2。', 'Alternating refinement rounds; diminishing returns past 2.'],
  rank_comp_export_sidecar: ['另存 *.rank_comp.safetensors sidecar（不写入 LoRA，否则加载到未量化基座会画坏）。建议需要分发补偿权重时开启。', 'Exports the compensator as a separate *.rank_comp.safetensors (never bake into LoRA — it breaks on unquantized bases).'],

  // ── 监控/诊断/SafeGuard ──
  advanced_monitoring_enabled: ['训练过程高级监控指标采集。建议排查期开启，平时关省开销。', 'Collects advanced runtime metrics. On while debugging, off for throughput.'],
  advanced_stats_enabled: ['额外统计信息输出。建议诊断期开启。', 'Extra statistics in logs. Diagnostic use.'],
  deep_diagnostics_enabled: ['深度诊断模式（更多日志/探针）。建议仅在排查疑难时开启。', 'Deep diagnostics add verbose probes; enable only while chasing hard bugs.'],
  layer_monitor_enabled: ['逐层激活/梯度监测。建议定位某层异常时开启。', 'Per-layer activation/gradient monitoring for locating misbehaving blocks.'],
  layer_monitor_interval: ['每 N 个优化步采样一次。建议 3。', 'Sampling cadence in optimizer steps. Keep 3.'],
  layer_monitor_max_layers: ['每轮最多统计层数，0 不限。建议 10 控制日志量。', 'Layers tracked per round; cap log volume around 10.'],
  layer_monitor_mode: ['sampled 抽样统计轻量；exact 全量准而慢。建议 sampled。', 'sampled is light; exact is exact but slow. Keep sampled.'],
  layer_monitor_sample_size: ['sampled 模式每层抽样元素数。建议 4096。', 'Elements sampled per layer in sampled mode. Keep 4096.'],
  layer_monitor_sparsity_epsilon: ['绝对值低于 ε 计为稀疏元素。建议 1e-8。', 'Threshold below which elements count as sparse. Keep 1e-8.'],
  runtime_features_detail: ['运行时统计输出详细度（off 关闭）。建议 off，排查时选档。', 'Verbosity of runtime stats; off normally, pick a level while debugging.'],
  step_phase_profile_enabled: ['训练步各阶段耗时 profiling。建议性能分析期开启。', 'Profiles per-phase step timings for performance work.'],
  safeguard_enabled: ['SafeGuard：拦截 NaN/Inf 与异常 loss spike 保护训练。建议长训无人值守开启。', 'SafeGuard intercepts NaN/Inf and loss spikes. Worth it on unattended long runs.'],
  safeguard_nan_check_interval: ['每 N 步检查一次 NaN/Inf。建议 1（默认）最及时。', 'NaN/Inf check cadence. 1 is most responsive.'],
  safeguard_loss_window_size: ['spike 判定滚动窗口大小。建议 20（默认）。', 'Rolling window for spike detection. Keep 20.'],
  safeguard_loss_spike_threshold: ['loss 超过滚动均值多少倍判 spike 并跳过该 step。建议 5（默认）。', 'Multiple of rolling mean treated as a spike and skipped. Keep 5.'],
  safeguard_max_nan_count: ['连续 NaN 达该次数停止训练。建议 3（默认）。', 'Consecutive NaN events before aborting. Keep 3.'],
  safeguard_auto_reduce_lr: ['触发保护时自动降学习率。建议反复轻微 spike 时开启。', 'Auto-lowers LR when protection triggers. Useful for recurring mild spikes.'],
  safeguard_lr_reduction_factor: ['自动降 LR 的倍率。建议 0.5（默认）减半。', 'LR multiplier applied on guard trips. Halving (0.5) is typical.'],
  safeguard_safe_state_interval: ['每 N 步保存可回滚安全快照（含动量，拖速）。建议 100（默认）平衡。', 'Rollback snapshot cadence including momentum state. 100 balances cost.'],
  lulynx_experimental_core_enabled: ['启用 Lulynx 核心组件集中管理（SafeGuard/EMA/ResourceManager）。建议需要其中任一能力时开启。', 'Enables the Lulynx core hub managing SafeGuard/EMA/ResourceManager together. Turn on when you need any of them.'],
  lulynx_resource_manager_enabled: ['监控显存占用按节奏清理缓存防碎片累积。建议碎片性 OOM 时开启。', 'Periodically clears caches against fragmentation OOM. Enable for fragmentation issues.'],
  lulynx_resource_log_interval: ['资源日志间隔步数。建议 25（默认）。', 'Resource-log cadence in steps. Keep 25.'],
  lulynx_smart_rank_enabled: ['SmartRank：周期性压缩低能量 rank 通道瘦身。建议过拟合或文件过大时试。', 'SmartRank periodically prunes low-energy rank channels. Try for overfitting or oversized files.'],
  lulynx_smart_rank_keep_ratio: ['保留 rank 通道比例（0.75=裁最弱 25%）。推荐范围：0.75–0.9。', 'Share of rank channels kept (0.75 drops weakest 25%). Recommended: 0.75-0.9.'],
  lulynx_ln_guard: ['LNGuard：对可学习 Norm 参数施加基线锚定防漂移（无可训 Norm 时安全空转）。建议风格漂移明显时开。', 'LNGuard anchors learnable norm parameters against drift (safe no-op without trainable norms). Try when style drifts.'],
  lulynx_ln_lambda: ['Norm 参数均方漂移权重。建议 0.01 小锚定。', 'Mean-square drift weight for norms. Light anchoring at 0.01.'],
  lulynx_freq_texture_enabled: ['latent 频域纹理损失参与 loss 拆分。建议纹理任务精细化时开。', 'Latent frequency-domain texture loss as an aux objective for texture-heavy goals.'],
  lulynx_freq_texture_weight: ['频域纹理损失权重。建议 0 起步小值试探。', 'Texture-loss weight. Probe from small values.'],
  lulynx_freq_texture_highpass_sigma: ['高低频分离的高斯模糊 sigma。建议 2（默认）。', 'Gaussian sigma separating high/low bands. Keep 2.'],
  lulynx_freq_texture_min_t: ['计入的 raw σ 下界。建议 0 全程。', 'Lower raw-sigma bound included. 0 covers all.'],
  lulynx_freq_texture_max_t: ['计入的 raw σ 上界。建议 1 全程。', 'Upper raw-sigma bound included. 1 covers all.'],
  lulynx_latent_anchor_enabled: ['Latent 感知锚：多尺度梯度匹配做感知约束。建议细节丢失时试。', 'Latent perceptual anchor via multi-scale gradient matching. Try when detail decays.'],
  lulynx_latent_anchor_weight: ['感知锚损失权重。建议 0 起步小值试探。', 'Anchor loss weight. Probe from small values.'],
  lulynx_latent_anchor_grad_scales: ['多尺度金字塔深度。建议 3（默认）。', 'Pyramid depth for multi-scale matching. Keep 3.'],
  lulynx_latent_anchor_perceptor: ['感知特征后端选择。建议 latent_msgrad 默认。', 'Feature backend for anchoring. latent_msgrad default.'],
  lulynx_latent_anchor_min_t: ['计入的 raw σ 下界。建议 0。', 'Lower raw-sigma bound. Keep 0.'],
  lulynx_latent_anchor_max_t: ['计入的 raw σ 上界。建议 1。', 'Upper raw-sigma bound. Keep 1.'],
  lulynx_svd_gradient_filter_enabled: ['双侧低秩投影重构梯度（优化器状态仍全尺寸，非 GaLore）。建议实验性开启。', 'Reconstructs gradients through low-rank double projections; optimizer state stays full-size (not GaLore). Experimental.'],
  lulynx_svd_gradient_filter_rank: ['过滤子空间 rank。建议 64（默认）。', 'Subspace rank for gradient filtering. Keep 64.'],
  lulynx_svd_gradient_filter_scale: ['过滤梯度缩放因子。建议 1 不缩放。', 'Scale applied to filtered gradients. Keep 1.'],
  lulynx_svd_gradient_filter_update_interval: ['每 N 步重算投影基。建议 100。', 'Basis refresh interval in steps. Keep 100.'],
  lulynx_svd_gradient_filter_warmup_steps: ['前 N 步用全梯度热身。建议 0。', 'Full-gradient warmup steps before filtering. Keep 0.'],
  lulynx_weight_noise_enabled: ['LoRA 权重噪声：每个优化步向权重注入扰动作正则。建议过拟合抑制试验用。', 'Injects noise into LoRA weights every step as regularization. Anti-overfitting experiment.'],
  lulynx_weight_noise_sigma: ['噪声强度：relative 模式为相对 RMS 倍率。建议 0.0125（默认）附近。', 'Noise scale; relative mode multiplies RMS. Around default 0.0125.'],
  lulynx_weight_noise_mode: ['噪声注入模式 relative/absolute。建议 relative 对规模稳健。', 'relative scales with weight RMS; absolute is fixed. relative is more robust.'],
  lulynx_weight_noise_bound_norm: ['加噪后把范数缩回原值抑制长期漂移。建议开启配合长训。', 'Restores tensor norms after noising to curb drift. Pair with long runs.'],
  lulynx_weight_noise_log_every: ['每 N 步写一次指标；0 关闭。建议 50。', 'Metric logging cadence; 0 silences. Keep 50.'],
  smart_rank_enabled: ['SmartRank 动态区间：在 [min,max] 内周期调整有效 rank。建议容量自适应试验。', 'SmartRank adjusts effective rank within [min,max] periodically. Capacity-adaptive experiment.'],
  smart_rank_interval: ['评估调整间隔步数。建议 50。', 'Evaluation cadence in steps. Keep 50.'],
  smart_rank_min: ['动态 rank 下界。建议 4。', 'Dynamic rank floor. Keep 4.'],
  smart_rank_max: ['动态 rank 上界。建议不超过 network_dim×2。', 'Dynamic rank ceiling; within ~2x network_dim.'],
  ant_enabled: ['ANT 自适应时间步采样：per-σ-bin loss EMA 驱动采样分布。建议收敛不均时试。', 'ANT reshapes timestep sampling from per-bin loss EMA. Try when some bands lag.'],
  ant_num_bins: ['sigma 分桶数量。建议 50（默认）。', 'Sigma bins for the controller. Keep 50.'],
  ant_blend: ['loss-driven 与 uniform 采样混合比（1=纯自适应）。建议 0.7。', 'Blend between adaptive and uniform sampling (1 fully adaptive). Keep 0.7.'],
  ant_temperature: ['采样权重平坦度：>1 更平 <1 更尖。建议 1（默认）。', 'Flattens (>1) or sharpens (<1) sampling weights. Keep 1.'],
  ant_ema_decay: ['per-bin loss EMA 衰减。建议 0.95。', 'EMA decay of per-bin losses. Keep 0.95.'],
  ant_warmup_updates: ['前 N 次 update 返回 uniform 等统计稳定。建议 30。', 'Uniform updates until statistics stabilize. Keep 30.'],
  bp_low_enabled: ['BP-low：高噪声 step 降分辨率反传省显存。建议高噪段主导的大分辨率训练试。', 'BP-low downsamples backward passes at high noise to save VRAM. Fits high-res runs dominated by high sigma.'],
  bp_low_factor: ['下采样倍数（2=半分辨率）。推荐范围：2–4。', 'Downsampling factor (2 = half resolution). Range 2-4.'],
  bp_low_noise_threshold: ['仅 σ 高于该值时启用下采样。建议 0.5。', 'Enable downsampling above this sigma. Keep 0.5.'],
  bp_low_scale: ['σ 量纲：1.0 raw [0,1]；1000 为 legacy 千分制。建议与所用调度一致。', 'Sigma units: 1.0 raw [0,1], 1000 legacy scale. Match your schedule.'],
  bp_low_schedule: ['step 硬阈值 / cosine 平滑过渡。建议 step 简单可控。', 'Hard threshold vs cosine ramp. step is simplest.'],
  sigma_depth_schedule_enabled: ['按 RF σ 调度本步 DiT 计算深度，跳过的 block 走恒等旁路不断梯度。与 Aircon 正交。建议速度实验开启。', 'Depth scheduling by sample sigma; skipped blocks pass through identity without breaking grads. Orthogonal to Aircon.'],
  sigma_depth_schedule_mode: ['hard_depth 硬上限 / soft_prob 软概率跳过。建议 hard_depth 可预期。', 'Hard depth cap vs probabilistic skipping. hard_depth is more predictable.'],
  sigma_depth_schedule_alpha: ['sigmoid 斜率，越大深度随 σ 变化越陡。建议 8（默认）。', 'Sigmoid steepness of depth-vs-sigma mapping. Keep 8.'],
  sigma_depth_schedule_beta: ['sigmoid 中心（RF σ∈[0,1]）。建议 0.35。', 'Center of the sigmoid in RF sigma. Keep 0.35.'],
  sigma_depth_schedule_min_blocks_kept: ['始终计算的前 N 个 block（护浅层）。建议 4。', 'Always-computed leading blocks. Keep 4.'],
  dit_compute_reducer_strategy: ['DiT BlockSkip：按计划跳过部分 block 计算。建议 none 起步，测速对照再开。', 'Planned skipping of DiT blocks for speed experiments. Start none, A/B first.'],
  dit_compute_reducer_skip_ratio: ['推导跳过频率的比例（0-0.95）。建议 0.25 以内保守。', 'Ratio driving skip frequency. Stay conservative <=0.25.'],
  dit_compute_reducer_skip_every: ['每 N 个候选 block 跳 1 个（0 关闭）。建议 0 用比例控制。', 'Skip one of every N candidate blocks (0 off). Ratio control preferred.'],
  dit_compute_reducer_min_block: ['小于该索引的前层永不跳过。建议 1。', 'Leading blocks exempt from skipping. Keep 1.'],
  dit_compute_reducer_warmup_steps: ['前 N 步完整前向热身。建议 4。', 'Full-forward warmup steps. Keep 4.'],

  // ── DPO / 偏好 ──
  dpo_enabled: ['DPO/Flow-DPO 偏好对齐：真正生效还需 dpo_weight>0。有 rejected_latents 真 pair 走四路 margin（更慢）；无 pair 走弱代理扰动路径。建议先备好偏好数据。', 'DPO/Flow-DPO preference alignment needs dpo_weight > 0 to engage; real rejected-latent pairs use four-way margins, otherwise a weak perturbation proxy applies. Prepare data first.'],
  dpo_weight: ['DPO 损失总闸权重（weight>0 才生效）。建议 0.1–0.5 起步。', 'Master DPO weight (must exceed 0). Start 0.1-0.5.'],
  dpo_beta: ['偏好温度/强度 β。建议 1（默认）。', 'Preference temperature beta. Keep 1.'],
  dpo_anchor_alpha: ['policy≈ref 的全局 MSE 正则；0 关。建议 0 起步。', 'MSE anchor keeping policy near ref; 0 disables. Start 0.'],
  dpo_logprob_scale: ['弱代理路径的 σ_dpo² 尺度。建议 1（默认）。', 'Variance scale of the weak-proxy density. Keep 1.'],
  dpo_rejected_perturb: ['自构造 rejected 目标的扰动幅度。建议 0.1（默认）。', 'Perturbation strength synthesizing rejected targets. Keep 0.1.'],
  dpo_rejected_latent_required: ['开启后缺 rejected 文件直接报错而非静默跳过。建议严格流程开启。', 'Errors out when rejected files are missing instead of silently skipping. Enable for strict pipelines.'],

  // ── 分布式补充 ──
  clear_dataset_npz_before_train: ['worker 训练前清空旧 .npz 缓存强制重建。建议仅在数据变更后开一次，平时关闭。', 'Workers wipe stale .npz caches before training. Toggle once after dataset edits.'],
};
