// SPDX-License-Identifier: LicenseRef-PolyFormNoncommercial-1.0.0
// desc 文案表 —— 高级/专家区（四）：EasyControl/IP、像素空间、区域聚焦、SDS-LoRA、
// LR Finder、压缩伴生、杂项 select/boolean 收尾。
export default {
  easy_control_channels: ['Legacy EasyControl 控制输入通道数（3=RGB）。建议与条件图一致，默认 3。', 'Input channels of legacy EasyControl conditioning (3 = RGB). Match your condition images.'],
  easy_control_scale: ['Legacy 控制强度：越高越服从控制图。推荐范围：0.5–1。', 'Legacy control strength; higher obeys the control image more. Recommended: 0.5-1.'],
  easycontrol_v2_enabled: ['EasyControl v2 双流条件控制（Anima faithful 路线）。建议有控制图需求时开启。', 'EasyControl v2 dual-stream conditioning on the Anima faithful route. Enable for control-image goals.'],
  easycontrol_v2_control_kind: ['控制类型/条件流形态（reference_latent 参考图 latent 等）。建议 reference_latent 默认。', 'Kind of control stream (reference_latent default). Keep unless your pipeline differs.'],
  easycontrol_v2_cond_channels: ['条件 latent/token 的最后一维，必须与缓存结构一致。建议 16（默认）。', 'Last-dim size of condition latents/tokens; must match cache layout. Keep 16.'],
  easycontrol_v2_cond_lora_rank: ['条件分支 LoRA rank。推荐范围：8（默认）附近。', 'LoRA rank of the condition branch. Recommended: ~8.'],
  easycontrol_v2_drop_p: ['训练时随机丢弃整个条件的概率（CFG 鲁棒性）。建议 0.1（默认）。', 'Probability of dropping the whole condition per sample (CFG robustness). Keep 0.1.'],
  easycontrol_v2_scale: ['条件流缩放强度。建议 1（默认）。', 'Scale of injected condition streams. Keep 1.'],
  easycontrol_v2_cond_noise_max: ['条件 latent 加噪上限；0 不加噪。建议 0。', 'Max noise on condition latents; 0 keeps them clean. Keep 0.'],
  easycontrol_v2_match_target_bucket: ['把条件图对齐训练 bucket 尺寸。建议条件图比例杂乱时开启。', 'Aligns condition images to training buckets. Enable for ragged condition aspect ratios.'],

  // ── 像素空间 ──
  pixel_space_enabled: ['绕过 VAE 直接在像素空间监督。实验路线，显存消耗大。建议仅特殊研究用途。', 'Supervises directly in pixel space bypassing the VAE: experimental and VRAM-hungry. Research use only.'],
  pixel_space_augmentation_enabled: ['像素侧数据增强（配合像素空间训练）。建议与 pixel_space_enabled 配套使用。', 'Pixel-side augmentation paired with pixel-space training.'],
  pixel_space_input_channels: ['像素输入通道数，通常 3=RGB。建议 3。', 'Pixel input channels, normally 3 for RGB. Keep 3.'],
  pixel_space_loss_type: ['像素损失类型：mse/l1/lpips/hybrid。建议 hybrid 兼顾结构与感知。', 'Pixel-space loss flavor: mse/l1/lpips/hybrid. hybrid balances structure and perception.'],

  // ── 区域聚焦 ──
  region_focus_coverage_balance: ['目标区域像素占比过低时提高该区域 loss 权重（不删步）。建议小主体大数据集开启。', 'Boosts loss weight when target regions are tiny relative to the frame (no step dropping). Good for small subjects.'],
  region_focus_coverage_target: ['低于该像素占比启动 boost。建议 0.05（默认）附近。', 'Coverage ratio below which boosting starts. Around default 0.05.'],
  region_focus_coverage_max_boost: ['低覆盖 boost 上限倍率。建议 2（默认）。', 'Upper bound of coverage boosting. Keep 2.'],
  region_focus_strength: ['区域权重相对 1.0 偏差的放大强度；1=按表原样。建议 1。', 'Amplifies deviations of region weights from 1.0; 1 uses tables as-is. Keep 1.'],
  region_focus_decay: ['聚焦强度随训练进度线性衰减到 floor。建议保持 true（默认）后期稳住整体。', 'Linearly decays focus toward the floor as training progresses. Keep true.'],
  region_focus_floor: ['进度末尾的强度倍率下限。建议 0.25。', 'Floor multiplier reached at end of training. Keep 0.25.'],

  // ── SDS-LoRA / LR Finder ──
  sds_lora_enabled: ['SDS-LoRA：双分支产出各向同性梯度 + warmup SVD 重参数化。建议实验性开启。', 'SDS-LoRA produces isotropic gradients via dual branches with SVD re-parameterization after warmup. Experimental.'],
  sds_lora_warmup_steps: ['SVD 重参数化前的 plain-LoRA 预热步。建议 10（默认）。', 'Plain-LoRA warmup steps before re-parameterization. Keep 10.'],
  sds_lora_refresh_phases: ['全程 QR 刷新阶段数。建议 5（默认）。', 'Number of QR refresh phases across the run. Keep 5.'],
  sds_lora_clear_optimizer_state: ['重参数时清理一次优化器动量防旧动量污染。建议保持 true（默认）。', 'Clears optimizer momentum at re-parameterization to avoid stale bias. Keep true.'],
  lr_finder_enabled: ['LR Finder：训练前扫描学习率区间找敏感带（工具向）。建议新底模/新规模首跑前用一次。', 'LR Finder sweeps a learning-rate band before training to locate a good range. Run once on new bases/scales.'],
  lr_finder_start_lr: ['扫描起始 LR。建议 1e-7（默认）。', 'Starting LR of the sweep. Keep 1e-7.'],
  lr_finder_end_lr: ['扫描结束 LR。建议 0.1（默认）覆盖到发散区。', 'Ending LR of the sweep; default reaches the diverging regime. Keep 0.1.'],
  lr_finder_num_steps: ['扫描步数，越多曲线越平滑越慢。建议 100（默认）。', 'Steps in the sweep; more is smoother but slower. Keep 100.'],

  // ── 压缩伴生适配器 ──
  compression_companion_enabled: ['压缩前加载冻结 recovery adapter 补偿精度损失（bake 或 sidepath）。无 path 默认 fail-closed。建议 FP8 底模质量敏感时开启。', 'Loads a frozen recovery adapter before compression to restore fidelity (baked or side-path); fails closed without one. Use when FP8 bases lose visible quality.'],
  compression_companion_type: ['伴生适配器类型标识。建议 lora 默认。', 'Adapter kind of the recovery companion. lora default.'],
  compression_companion_mode: ['合并模式：merge_into_base 烘焙进底座并重置可训槽；sidepath_frozen 冻结旁路不占训练槽。建议 merge_into_base。', 'merge_into_base bakes it into the base; sidepath_frozen keeps it aside without consuming a train slot. Prefer merge_into_base.'],
  compression_companion_missing_policy: ['缺 path 时策略：fail 硬失败（默认更安全）；downgrade_t1 关 companion 保留压缩并警告。建议 fail。', 'When no path exists: fail hard (safer default) or downgrade_t1 to keep compression with a warning. Keep fail.'],
  compression_companion_auto_bootstrap: ['无有效 path 时 prepare 前最多做一次 product-fp8 residual 拟合并写回 path。建议默认关闭按需开。', 'Fits a product-fp8 residual once to synthesize a missing companion path. Off by default; opt in deliberately.'],
  compression_companion_bootstrap_rank: ['自举 residual LoRA rank。建议 4（默认）。', 'Rank of the bootstrapped residual adapter. Keep 4.'],
  compression_companion_bootstrap_max_layers: ['自举覆盖层数上限；0 全部相交 Linear。建议 0。', 'Cap on bootstrapped layers; 0 covers all intersecting Linears. Keep 0.'],
  compression_companion_scale: ['merge/sidepath 时的缩放系数。建议 1（默认）。', 'Scaling applied when merging or side-loading the companion. Keep 1.'],

  // ── 杂项收尾 ──
  cached_collate_mode: ['缓存数据 Collate 模式（仅影响 Anima/Newbie cache-first 数据集）：auto 自动选择。建议 auto。', 'Collate mode over cached data (Anima/Newbie cache-first only). auto is fine.'],
  checkpoint_policy: ['梯度检查点策略：auto 自动权衡 / full 全量 / offloaded 卸载版 / selective 选择性。建议 auto。', 'Checkpointing policy: auto balances, full maximizes savings, offloaded pages to CPU, selective targets specific blocks. Keep auto.'],
  data_backend: ['数据后端：auto/caption 当前都走 CaptionDataset 实现。建议 auto 保持跟随。', 'Data backend selection; auto/caption currently share the CaptionDataset implementation. Keep auto.'],
  data_transfer_profile_enabled: ['采样 CPU/GPU tensor 传输耗时（诊断）。建议性能分析期开启。', 'Profiles CPU/GPU tensor transfer timings. For performance analysis.'],
  data_transfer_profile_mode: ['传输计时模式：event 用 CUDA events 低同步开销。建议 event。', 'Timing mode using CUDA events with minimal sync cost. Keep event.'],
  data_transfer_profile_window: ['每累计多少次传输输出一次汇总。建议 50（默认）。', 'Transfers aggregated per summary line. Keep 50.'],
  dora_mode: ['DoRA 训练门控：full 方向+幅度全训；style 仅幅度；structure 仅方向。建议 full 完整体验。', 'DoRA gating: full trains both factors, style magnitude-only, structure direction-only. full recommended.'],
  dora_variant: ['DoRA 方案：classic 标准；lulynx_stopgrad_dora 为前向等价的 stop-gradient 工程变体。建议 classic。', 'classic standard DoRA vs lulynx stop-gradient engineering variant with identical forward values. Keep classic.'],
  enable_inference_accel: ['可选加速预览出图（Spectrum/SmoothCache 跳算）。预览质量略降。建议长训想省时间时开启。', 'Speeds preview sampling via Spectrum/SmoothCache compute skipping at slight quality cost. Enable for long runs.'],
  experimental_attention_profile_window: ['窗口注意力的每 token 历史窗口长度（token 数非步数）；0 表示完整注意力。建议 50–100 起步。', 'Sliding-window attention span in tokens (0 = full attention). Probe from 50-100.'],
  experimental_attention_profile_torch_max_tokens: ['纯 PyTorch O(n²) 回退路径的序列上限，防止长序列误跑爆显存。建议 2048（默认）。', 'Sequence cap for the plain-PyTorch O(n^2) fallback against VRAM blowups. Keep 2048.'],
  fg_lora_rank_conserve_budget: ['orthogonal 重分配时保证总 rank 数不超过传统均匀分配。建议保持 true（默认）省参。', 'Keeps total rank within the uniform-allocation budget during orthogonal reallocation. Keep true.'],
  fg_lora_rank_min: ['FG-LoRA 分配的单层最小 rank。建议 4（默认）。', 'Minimum rank assigned per layer. Keep 4.'],
  fg_lora_rank_max: ['单层最大 rank，高分层趋近此值。建议 32（默认）附近。', 'Maximum rank per layer that high-score layers approach. Keep ~32.'],
  fg_lora_rank_policy: ['rank 在层间的分配策略（uniform 均匀等）。建议 uniform 起步。', 'How ranks distribute across layers. Start uniform.'],
  fg_lora_rank_profile: ['沿深度的 rank 曲线形状（center_peak 中部峰值等）。建议 center_peak 默认。', 'Depth profile shape of rank allocation; center_peak matches typical U-Net importance.'],
  fused_projection_memory_mode: ['融合投影权重的显存模式：keep_original 最兼容。建议 keep_original。', 'Memory handling for fused projection weights; keep_original is most compatible.'],
  loss_precision: ['Loss 计算精度策略：fp32_loss 当前稳定路径。建议 fp32_loss 保持。', 'Precision policy for loss computation; fp32_loss is the stable path today. Keep it.'],
  lycoris_algo: ['LyCORIS 具体算法（LoCon/LoHa/LoKr/IA3/Diag-Oft 等后端原生集）。按容量/速度需求选择，建议 LoCon 起步。', 'Concrete LyCORIS algorithm from the natively supported set. LoCon is a sensible start.'],
  max_timestep: ['训练允许的最大 timestep（截断高噪段）。建议留空全范围；只想学细节时下调。', 'Upper timestep bound trimming the high-noise range. Empty covers all; lower to focus on detail.'],
  min_timestep: ['训练允许的最小 timestep（截断低噪段）。建议留空全范围。', 'Lower timestep bound trimming the low-noise range. Empty covers all.'],
  mode_scale: ['mode 权重策略的缩放系数（EDM2 mode weighting）。建议留空关闭。', 'Mode-weighting scale (EDM2 style). Leave empty to disable.'],
  quant_train_convrot: ['keep_w8 时对匹配层做真 group-RHT 旋转（与 Comfy convrot 导出一致）。建议需要导出兼容时开启。', 'Applies true group-RHT rotation in keep_w8 mode matching Comfy convrot exports. Enable for export compatibility.'],
  staged_resolution_ratio_512: ['阶段分辨率训练中 512 档样本占比 %（最大边不足时忽略该档）。推荐范围：五档合计 100，512 档给 20 左右。', 'Share (%) of 512-tier samples in staged-resolution training; ratios should sum to 100.'],
  staged_resolution_ratio_768: ['768 档占比 %（最大边不足时忽略该档）。推荐范围：30 左右。', 'Share (%) of the 768 tier; ignored below that edge.'],
  staged_resolution_ratio_1024: ['1024 档占比 %（两种基准管线都会用到）。推荐范围：50 左右为主力档。', 'Share (%) of the 1024 tier used by both 1024/2048 pipelines.'],
  staged_resolution_ratio_1536: ['1536 档占比 %（仅 2048 基准管线用到）。推荐范围：30 以内。', 'Share (%) of the 1536 tier, only under the 2048 pipeline.'],
  staged_resolution_ratio_2048: ['2048 档占比 %（仅 2048 基准管线用到）。推荐范围：50 以内，显存吃紧再调低。', 'Share (%) of the 2048 tier, only under the 2048 pipeline.'],
  stochastic_depth_enabled: ['随机深度训练：随机跳过部分 DiT block 提速并正则化。建议速度实验开启观察收敛。', 'Randomly skips DiT blocks during training for speed plus regularization. Watch convergence when enabled.'],
  stochastic_depth_survival_prob: ['每层被保留的概率。推荐范围：0.8（默认）；过低伤收敛。', 'Probability each layer survives. Recommended: 0.8.'],
  stochastic_depth_min_blocks_kept: ['始终保留前 N 个 block 防网络过浅。建议 4（默认）。', 'Leading blocks never skipped. Keep 4.'],
  training_quantization_enabled: ['训练量化别名开关（与 quantization_enabled 同义入口）。建议用主开关即可。', 'Alias entry mirroring quantization_enabled. Prefer the primary switch.'],
  training_quantization_type: ['训练量化类型别名（兼容字段）。建议与主字段保持一致即可，勿单独另设值。', 'Alias of the main quantization-type field. Recommended: mirror the primary switch and leave this alone.'],
  anima_ema_feat_align_enabled: ['JLT EMA 特征自蒸馏：EMA-of-LoRA 影子 + 特征对齐。建议实验性开启对比。', 'Self-distills features against an EMA-of-LoRA shadow. Experimental comparison aid.'],
  anima_ema_feat_align_decay: ['EMA 影子衰减率。建议 0.9999（默认）。', 'Decay of the EMA shadow. Keep 0.9999.'],
  anima_ema_feat_align_weight: ['特征对齐损失权重。建议 0 关闭起步。', 'Feature-alignment loss weight. Start 0.'],
  anima_fused_qkv: ['融合 Anima Self-Attention 的 Q/K/V 投影内核提速。建议验证稳定性后开启。', 'Fused Q/K/V projection kernels for Anima self-attention. Enable after stability checks.'],
  cfm_lambda: ['对比 Flow Matching 辅助损失权重。建议 0.05（默认）小权重起步。', 'Weight of the contrastive flow-matching aux loss. Small start around 0.05.'],
  negative_semantic_regularization_enabled: ['负面语义正则：用负面提示词约束 LoRA-on/off 差异，抑制不想要的语义渗入。建议触发词误触发时试。', 'Constrains LoRA-on/off deltas under negative prompts to curb unwanted semantic bleed. Try against false triggers.'],
  negative_semantic_regularization_mode: ['当前后端实现为 lora_delta（约束负面提示词下的输出差异）。建议保持 lora_delta。', 'Only lora_delta is implemented server-side today. Keep it.'],
  negative_semantic_regularization_weight: ['负面语义正则权重。推荐范围：0.05–0.2，默认 0.1。', 'Negative-semantic regularization weight. Recommended: 0.05-0.2 (default 0.1).'],
};
