// SPDX-License-Identifier: LicenseRef-PolyFormNoncommercial-1.0.0
// desc 文案表 —— 高级/专家区（三）：Adapter Mask 剪枝、FG-LoRA、EMA、Perlin、
// 分辨率感知批量、Universal DiT、概念几何（一）。
export default {
  adapter_mask_pruning_enabled: ['训练中按 adapter rank 重要性逐步屏蔽低贡献 rank（逻辑剪枝）。建议过拟合或想瘦身时开启。', 'Masks low-contribution ranks during training based on importance scores. Useful against overfitting or for slimmer outputs.'],
  adapter_mask_pruning_ema_decay: ['weight×grad 重要性分数的 EMA 衰减。建议 0.9（默认）。', 'EMA decay for weight*grad importance. Keep 0.9.'],
  adapter_mask_pruning_interval: ['每隔多少 backward step 更新一次 mask。建议 100（默认）附近。', 'Steps between mask updates. Around the default 100.'],
  adapter_mask_pruning_min_rank: ['每个 adapter 至少保留的 rank 数。建议 1–4。', 'Minimum ranks kept per adapter. Suggested 1-4.'],
  adapter_mask_pruning_target_ratio: ['最终屏蔽的 rank 比例上限（0.5=约保留一半）。推荐范围：0–0.95，默认 0 表示不剪。', 'Final masked-ratio target (0.5 keeps about half). Recommended: probe below 0.5; default 0 prunes nothing.'],
  adapter_mask_pruning_warmup_steps: ['预热内只累计重要性不更新 mask。建议 0 或短预热。', 'Importance-only warmup before masking starts. Short or zero is fine.'],
  adapter_target_policy: ['FG-LoRA 层选择策略：all 全部层或按分数筛选。建议 all 默认，精调再筛。', 'How FG-LoRA picks target layers; all by default, scored filtering for fine control.'],
  adapter_target_policy_fraction: ['按分数保留的层比例。建议 1（默认全保留）起步。', 'Fraction of layers kept by score. Start at 1.'],
  adapter_target_policy_min_score: ['层重要性低于该阈值被过滤；0 不过滤。建议 0。', 'Filter out layers scoring below this; 0 keeps all. Keep 0.'],
  adapter_target_policy_top_k: ['直接指定保留的最重要层数；0 用比例模式。建议 0。', 'Keep exactly this many top layers; 0 uses fraction mode. Keep 0.'],
  distillation_loss_weight: ['蒸馏对齐损失的总体权重。推荐范围：1（默认）；过大压制学生自身目标。', 'Overall weight of distillation alignment loss. Recommended: 1; higher drowns the student objective.'],
  ema_enabled: ['EMA 指数滑动平均：额外维护一份平滑参数，保存时可写出 EMA 权重通常更稳；显存多一份参数副本。建议长训实验开启对比。', 'Maintains an EMA shadow of parameters for smoother checkpoints (one extra parameter copy). Worth comparing on longer runs.'],
  ema_decay: ['EMA 衰减率，越接近 1 越平滑但响应越慢。推荐范围：0.998–0.9995（默认 0.999）。', 'EMA decay; closer to 1 smooths more and reacts slower. Recommended: 0.998-0.9995.'],
  ema_update_after_step: ['从第几个优化 step 才开始更新 EMA，跳过前期噪声。建议 0 立即开始或数百步热身。', 'First optimizer step where EMA updates begin. 0 or a few hundred warmup steps both work.'],
  ema_update_every: ['每 N 个优化步更新一次 EMA。建议 1（默认）。', 'EMA update cadence in optimizer steps. Keep 1.'],
  h3_audio_loss_weight: ['音频分支损失相对视频分支的权重。推荐范围：1（默认）平衡。', 'Audio-branch loss weight relative to video. Keep 1 for balanced AV training.'],
  lora_activation_recompute_mode: ['原生 DiT LoRA 反传激活重算档位：auto 自动选择。建议 auto。', 'Activation recompute level for native DiT LoRA backward; auto decides per setup.'],
  lora2_adaptive_enabled: ['LoRA2 Adaptive：用指数衰减权重自动学习各模块最优 rank。建议容量难拍板时试验。', 'Learns per-module effective rank via exponentially-decayed weights. Try when picking ranks is hard.'],
  lora2_adaptive_decay_lambda: ['指数衰减系数 λ。建议 1.0（默认/论文值）。', 'Exponential decay lambda. Recommended: 1.0.'],
  lora2_adaptive_nu_init: ['nu 初值控制衰减速度。建议 1.0（默认）。', 'Initial nu controlling decay speed. Keep 1.0.'],
  lora2_adaptive_r_max: ['允许的最大 rank 上限。建议 ≤ network_dim 的 2 倍。', 'Maximum allowed rank; within ~2x network_dim.'],
  perlin_noise_offset_enabled: ['用 Perlin 场替代均匀 noise_offset，产生空间相关噪声正则。建议与 noise_offset 二选一对比。', 'Replaces uniform noise_offset with spatially coherent Perlin fields. Compare head-to-head with plain offset.'],
  perlin_noise_offset_scale: ['Perlin 场频率尺度，越大纹理越细。建议 4（默认）附近。', 'Perlin field frequency; higher means finer texture. Keep ~4.'],
  perlin_noise_offset_strength: ['Perlin 场叠加强度。建议 0.1（默认）附近，同 noise_offset 量级。', 'Perlin overlay strength; similar magnitude to noise_offset (~0.1).'],
  resolution_aware_batch_enabled: ['分辨率感知批量：小图自动放大 batch、大图缩小稳显存。建议混合分辨率数据集开启。', 'Scales effective batch with input resolution to steady VRAM on mixed-size datasets.'],
  resolution_aware_batch_base_resolution: ['使用原 batch 值的基准分辨率（px）。建议设为常用训练分辨率（如 1024）。', 'Resolution at which train_batch_size applies as-is. Set to your common resolution.'],
  resolution_aware_batch_max_factor: ['小图时 batch 最大放大倍数。建议 2–4。', 'Max batch upscale factor for small images. Recommended: 2-4.'],
  resolution_aware_batch_min_factor: ['大图时 batch 最小缩小倍数。建议 0.25–0.5。', 'Min batch downscale factor for large images. Recommended: 0.25-0.5.'],
  stepped_loss_enabled: ['分步损失调度：按 step 切换 loss 类型/权重表。建议课程式实验使用。', 'Switches loss type/weights by step schedule. For staged experiments.'],
  stepped_loss_schedule: ['分步损失的阶段表定义。建议从简单两段开始验证。', 'Stage table for stepped losses. Start with two simple stages.'],
  universal_dit_objective_template: ['Universal DiT 目标模板：auto 从模型证据推断，证据不足会要求确认而非猜测。建议 auto。', 'Objective template for Universal DiT; auto requires confirmation when evidence is thin rather than guessing.'],
  universal_dit_probe_mode: ['探测模式：auto 逐级执行静态检查与前向；train_smoke 额外做最小反向。建议 auto。', 'Probing depth for Universal DiT; train_smoke adds a minimal backward pass. auto suffices usually.'],
  universal_dit_target_policy: ['Linear 目标策略：attention_mlp 保守集合 / all_linear 全部 Linear / explicit 白名单。建议 attention_mlp 默认。', 'Which Linears become targets: the conservative attention+MLP set, all Linears, or an explicit whitelist. Keep attention_mlp.'],
  universal_dit_trust_remote_code: ['信任模型仓库自定义代码（trust_remote_code）。高风险，仅对来源可信且已审查的模型启用。建议关闭。', 'Honors repo-provided custom code. High risk; enable only for reviewed, trusted sources. Default off.'],

  // ── 概念几何 ──
  concept_geometry_enabled: ['Concept Geometry：按概念几何图做采样/加权，控制多概念的相对距离。建议多概念纠缠时试。', 'Concept Geometry samples/weights by concept geometry to control inter-concept distances. Try when concepts bleed together.'],
  concept_geometry_sampler_mode: ['采样模式：curriculum 课程 / density 密度驱动。建议 density_curriculum 默认。', 'Sampling mode blending curriculum and density drives. Keep the default blend.'],
  concept_geometry_density_power: ['密度指数：调节几何密度对采样的影响强度。建议 1（默认）。', 'Exponent applied to geometric density when sampling. Keep 1.'],
  concept_geometry_loss_weighting: ['用几何密度派生逐样本 loss 权重。建议实验性开启。', 'Derives per-sample loss weights from geometric density. Experimental.'],
  concept_geometry_semantic_enabled: ['prep 时用文本 embedding 增强几何结构。建议语义标签丰富时开启。', 'Enriches geometry with text embeddings during prep. Good with rich captions.'],
  concept_geometry_embedding_provider: ['Embedding 提供方：local_path 本地 / auto_download 自动下载 / api。建议 local_path 可控性最好。', 'Where text-embedding models come from: local path (most controllable), auto-download, or API.'],
  concept_geometry_embedding_backend: ['Embedding 推理后端：pytorch / onnx 扩展点。建议 pytorch。', 'Inference backend for embeddings: pytorch or the onnx extension point. Keep pytorch.'],
  concept_geometry_embedding_device: ['Embedding 计算设备：cpu/cuda。小模型 cpu 即可。建议 cpu 默认。', 'Device for embedding compute; cpu default suffices for small encoders.'],
  concept_geometry_embedding_allow_download: ['允许联网下载 Embedding 模型。离线环境务必关闭。建议默认 false。', 'Allow network downloads of embedding models. Keep off offline; default false.'],
  concept_geometry_embedding_batch_size: ['Embedding prep 的批大小。建议 8（默认）。', 'Batch size for embedding prep. Keep 8.'],
  concept_geometry_translation_enabled: ['prep 时可选翻译管线统一 caption 语言。建议多语言混杂数据集才开。', 'Optional translation pass unifying caption language during prep. Only for mixed-language sets.'],
  concept_geometry_translation_provider: ['翻译提供方：local_path/api。建议 local_path。', 'Translation provider: local path or API. Prefer local_path.'],
  concept_geometry_translation_batch_size: ['翻译 prep 批大小。建议 8。', 'Batch size for translation prep. Keep 8.'],
};
