// SPDX-License-Identifier: LicenseRef-PolyFormNoncommercial-1.0.0
// desc 文案表 —— 高级/专家区（一）：AutoController、自适应调度、编译加速、损失工程、采样探针。
// P1 层以功能说明为主，推荐范围按后端默认值与保守口径给出。
export default {
  // ── AutoController ──
  ac_enabled: ['AutoController：按训练状态自动调整学习率、早停、TE 冻结等（旧配置 lulynx_auto_controller_* 仍被识别）。建议先跑基线再开，便于归因。', 'AutoController auto-adjusts LR, early stop and TE freezing from run signals (legacy lulynx_auto_controller_* still accepted). Baseline first, then enable.'],
  ac_warmup_steps: ['控制器生效前的观察步数。推荐范围：100（默认）附近。', 'Observation steps before the controller acts. Recommended: ~100.'],
  ac_target_gsnr: ['目标梯度信噪比，驱动 LR 自动调整。推荐范围：5（默认）附近。', 'Target gradient-SNR steering automatic LR changes. Recommended: ~5.'],
  ac_enable_auto_lr_adjustment: ['按 GSNR/loss 目标自动调 LR。建议与手动 LR 二选一对照评估。', 'Auto-tunes LR toward GSNR/loss targets. Evaluate against a manual-LR baseline.'],
  ac_enable_auto_te_freeze: ['到指定步数自动冻结文本编码器。建议 TE 收敛后想省显存的长训开启。', 'Freezes TE automatically at a set step; handy late in long runs to save memory.'],
  ac_te_freeze_step: ['触发自动冻结 TE 的步数。建议设为总步数的 50–70%。', 'Step when TE auto-freeze triggers; about half your total steps works well.'],
  ac_enable_dynamic_loss_scaling: ['按梯度范数动态调整损失缩放。建议 fp16 训练不稳时开启。', 'Dynamic loss scaling driven by grad norms; helps unstable fp16 runs.'],
  ac_enable_smart_early_stopping: ['loss 长期不降时自动停止。建议长训无人值守开启防浪费。', 'Stops automatically when loss stalls for long. Good unattended-run insurance.'],
  ac_enable_smart_lr_decay: ['平台期自动降低学习率。建议配合早停一起用。', 'Decays LR on plateaus; pairs well with early stopping.'],
  ac_early_stopping_patience: ['多少步无改善触发早停。推荐范围：5（默认）～20 视噪声水平。', 'Steps without improvement before early stop. Recommended: 5-20 by noise level.'],
  ac_early_stopping_threshold: ['判定「有改善」的最小变化阈值。建议 0 默认敏感。', 'Minimum change counted as improvement. Keep default sensitivity.'],
  ac_loss_plateau_window: ['判定平台的滑动窗口步数。推荐范围：50（默认）。', 'Sliding window defining a plateau. Recommended: 50.'],
  ac_lr_decay_factor: ['触发衰减时 LR 乘的系数。推荐范围：0.5（默认）。', 'LR multiplier applied on decay. Recommended: 0.5.'],
  ac_max_decays: ['LR 最多衰减次数。建议 3。', 'Maximum number of LR decays. Keep 3.'],
  ac_clip_drift_warning: ['CLIP 分数漂移警告阈值。建议 0.03（默认）。', 'CLIP-drift warning threshold. Keep 0.03.'],
  ac_clip_drift_danger: ['CLIP 漂移干预阈值（如降 LR）。建议 0.05（默认）。', 'CLIP-drift intervention threshold (e.g. lowering LR). Keep 0.05.'],
  ac_clip_drift_consecutive: ['漂移连续出现次数放大干预置信。建议 5（默认）。', 'Consecutive drift hits before intervening. Keep 5.'],
  ac_stable_rank_collapse_threshold: ['Stable Rank 下降比例视为崩溃。建议 0.3。', 'Stable-rank drop ratio treated as collapse. Keep 0.3.'],
  ac_stable_rank_consecutive: ['rank 崩溃连续确认次数。建议默认。', 'Consecutive confirmations for rank collapse. Keep default.'],
  ac_batch_size_step: ['动态批大小每次调整的步进。建议 1 保持最小扰动。', 'Batch-size adjustment increment. Keep 1.'],

  // ── 自适应训练 / Rank / 样本挖掘 ──
  adaptive_training_interval_steps: ['控制器评估动作的最小间隔步数。建议 50（默认）。', 'Min steps between controller evaluations. Keep 50.'],
  adaptive_training_minimum_evidence: ['产生动作前需要的最少证据数。建议 3（默认）。', 'Evidence reports required before acting. Keep 3.'],
  adaptive_training_patience: ['质量分连续下降多少次触发收敛修正。建议 2（默认）。', 'Consecutive quality declines before corrective action. Keep 2.'],
  adaptive_training_max_actions: ['单次训练最多执行的动作数。建议 8（默认）。', 'Max controller actions per run. Keep 8.'],
  adaptive_training_event_history: ['内存/resume 中保留的事件条数。建议 256（默认）。', 'Events kept in memory/resume state. Keep 256.'],
  adaptive_training_metrics_enabled: ['记录 loss/区域 loss/梯度范数等指标事件流。建议保持开启（默认 true）。', 'Streams loss/region-loss/grad-norm metric events. Keep on (default).'],
  adaptive_training_metrics_interval: ['指标事件采样间隔步数。建议 1（默认）。', 'Metric event sampling cadence in steps. Keep 1.'],
  adaptive_training_objective: ['控制器优化目标（balanced 平衡等）。建议 balanced。', 'Controller objective profile; balanced fits most.'],
  adaptive_training_locked_items: ['锁定后控制器不会修改这些项。建议把已手调满意的项锁住。', 'Items the controller may never touch. Lock anything you hand-tuned deliberately.'],
  adaptive_training_rollback_on_decline: ['验证分下降时撤销最近可逆动作。建议保持 true（默认）。', 'Reverts recent reversible actions when validation drops. Keep true.'],
  adaptive_training_learning_rate_min: ['自动 LR 的下限钳制。建议 1e-8（默认）。', 'Lower clamp for automatic LR. Keep 1e-8.'],
  adaptive_training_learning_rate_max: ['自动 LR 的上限钳制。建议 1.0（默认）。', 'Upper clamp for automatic LR. Keep 1.0.'],
  adaptive_training_learning_rate_step: ['下降时乘的比例（0.01–1）。建议 0.8 温和收缩。', 'Multiplicative shrink factor per adjustment (0.01-1). Gentle 0.8 recommended.'],
  adaptive_training_region_weight_min: ['区域权重下限。建议 0.1。', 'Floor for region weights. Suggested 0.1.'],
  adaptive_training_region_weight_max: ['区域权重上限。建议 4。', 'Ceiling for region weights. Suggested 4.'],
  adaptive_training_region_weight_step: ['区域权重每次调整步长。建议 0.1。', 'Adjustment step for region weights. Suggested 0.1.'],
  adaptive_rank_mode: ['模块级动态 rank 策略：静态注入前分配；动态按梯度证据周期迁移并保留优化器状态。建议 off 起步。', 'Per-module dynamic rank policy; static assigns up front, dynamic migrates with evidence. Start off.'],
  adaptive_rank_total_budget: ['所有模块 rank 总和上限；0 按当前预算。建议 0。', 'Global cap on summed ranks; 0 keeps the current budget. Keep 0.'],
  adaptive_rank_min_rank: ['单个模块 rank 下限。建议 1–4。', 'Per-module rank floor. 1-4 sensible.'],
  adaptive_rank_max_rank: ['单个模块 rank 上限。建议不超过 network_dim。', 'Per-module rank ceiling; keep within network_dim.'],
  adaptive_rank_probe_window: ['累计多少次梯度观测形成稳定敏感度。建议 32（默认）。', 'Gradient observations needed for stable sensitivity. Keep 32.'],
  adaptive_rank_reallocation_interval: ['动态模式重评估间隔步数。建议 100（默认）。', 'Reallocation cadence in steps for dynamic mode. Keep 100.'],
  adaptive_rank_warmup_steps: ['预热内只采样不迁移。建议 0 或短预热。', 'Sample-only warmup before migrating ranks. Short or zero is fine.'],
  adaptive_rank_ema_decay: ['敏感度 EMA 衰减，高平滑低灵敏。建议 0.9（默认）。', 'Sensitivity EMA decay; higher smooths more. Keep 0.9.'],
  adaptive_rank_min_delta: ['小于该差值不迁移 rank，减少形状抖动。建议 1。', 'Skip migrations smaller than this delta to avoid shape churn. Keep 1.'],
  adaptive_sample_mining_interval: ['汇总样本 loss 的间隔步数。建议 10（默认）。', 'Steps between sample-loss aggregation passes. Keep 10.'],
  adaptive_sample_mining_top_fraction: ['标记为困难样本的比例上限。建议 0.25。', 'Fraction of samples flagged hard. Keep 0.25.'],
  adaptive_sample_mining_max_samples: ['样本状态容量（条）。建议 2048。', 'Capacity of tracked sample states. Keep 2048.'],
  adaptive_sample_mining_report_limit: ['建议报告列表长度上限。建议 32。', 'Max rows in the mining report. Keep 32.'],
  adaptive_sample_mining_ema_decay: ['困难度 EMA 衰减。建议 0.9。', 'Difficulty EMA decay. Keep 0.9.'],
  adaptive_caching_ema_momentum: ['变化率 EMA 平滑（Aircon）。建议 0.9。', 'EMA smoothing for change rates (Aircon). Keep 0.9.'],
  adaptive_loss_weighting_enabled: ['可学习 SNR gamma 替代固定 min-SNR。建议实验性开启并与固定 γ=5 对比。', 'Learnable SNR gamma replacing fixed min-SNR. Compare against fixed gamma 5.'],
  adaptive_loss_weighting_init_gamma: ['可学习 gamma 初值。建议 5（min-SNR 推荐值同源）。', 'Initial learnable gamma. Start at 5 like min-SNR.'],
  adaptive_loss_weighting_lr: ['gamma 参数的学习率。建议 1e-3 小步走。', 'LR for the learnable gamma. Small steps around 1e-3.'],

  // ── 编译加速 ──
  compile_runtime: ['torch.compile 运行策略（off 关闭等）。建议 off 起步，收益验证后再启用具体档。', 'torch.compile runtime strategy; start off until gains are validated on your model.'],
  compile_cache_enabled: ['跨 run 复用 torch.compile 编译结果。建议开启（默认 true）缩短二次启动。', 'Reuses compiled graphs across runs to shorten restarts. Keep on (default).'],
  compile_cache_root: ['编译缓存根目录（相对输出或绝对路径）。建议指向快盘。', 'Root folder for compile caches; prefer a fast disk.'],
  compile_cache_reuse: ['允许从磁盘复用已有编译缓存。建议保持 true。', 'Load existing on-disk compile caches. Keep true.'],
  dynamo_backend: ['写入 torch_compile_backend 的 Dynamo 后端。建议保持 inductor 主力选择。', 'Dynamo backend written to torch_compile_backend; inductor is the workhorse.'],
  torch_compile_mode: ['传给 torch.compile(mode=)：default 均衡；reduce-overhead 降启动开销；max-autotune 稳态最快但首次最慢。建议 default。', 'torch.compile mode: default balanced, reduce-overhead trims startup, max-autotune fastest steady-state but slowest first pass. Keep default.'],
  torch_compile_dynamic: ['允许动态 shape，牺牲部分优化换稳定。建议 true（更稳）。', 'Allows dynamic shapes trading some optimization for stability. Prefer true.'],
  torch_compile_fullgraph: ['要求整图无 graph break，失败回退。建议 false 宽容处理。', 'Demands one break-free graph, falling back otherwise. Keep false for tolerance.'],
  torch_compile_scope: ['编译作用域：空跟随 runtime；per_block 逐块；full 整图。建议留空。', 'Compile scope: empty follows runtime; per_block or full override. Leave empty.'],
  torch_compile_allow_full_with_per_block: ['高级：full 与 per_block 并存时不拦截。建议 false。', 'Expert: permit full+per_block coexistence without guard. Keep false.'],
  torch_compile_block_indices: ['指定参与编译的 block 索引列表。建议留空全量或由策略决定。', 'Explicit block indices to compile. Empty lets strategy decide.'],
  torch_compile_first_step_timeout_note: null,
  compile_shape_strategy: ['compile 输入 shape 策略：auto 自动。建议 auto。', 'Input-shape strategy for compilation. auto recommended.'],
  compile_target_strategy: ['编译目标策略：auto 按模块能力探测。建议 auto。', 'What gets compiled; auto probes module capability. Keep auto.'],
  compile_inductor_tuning: ['Inductor 融合调优档位：off 关；max_autotune 更快但首次很慢。建议 off。', 'Inductor fusion tuning level; max_autotune helps steady-state at heavy first-pass cost. Keep off.'],
  compile_anima_full_core_enabled: ['把整个 Anima DiT 编译成单图（非逐块），编译久收益大。建议长训实验再开。', 'Compiles the whole Anima DiT into a single graph: long compile, big payoff for long runs only.'],
  compile_probe_enabled: ['编译前跑短 probe 验证收益，不达标回退。建议保持 true（默认）。', 'Short probe validates compile gains before committing; falls back otherwise. Keep true.'],
  compile_probe_steps: ['probe 采样步数。建议 3（默认）。', 'Steps sampled by the probe. Keep 3.'],
  compile_probe_max_vram_increase_ratio: ['probe 显存涨幅上限（相对基线），超了判失败。建议 0.15。', 'Max VRAM growth allowed by the probe vs baseline. Keep 0.15.'],
  compile_probe_min_speedup_ratio: ['稳态加速低于该比例则回退。建议 0.03（3%）。', 'Fall back if measured speedup is below this ratio. Keep 0.03.'],
  compile_contract_strict: ['训练前强制路由安全门。建议保持 true（默认）。', 'Enforces routing safety gates before training. Keep true.'],
  compile_static_shape_drop_last: ['静态 shape 下丢弃不完整尾批保证定长。建议保持 true。', 'Drops ragged tail batches so shapes stay static. Keep true.'],
  compile_require_cache_first: ['静态/full 编译要求 latent/文本已缓存。建议保持 true。', 'Static/full compilation requires prebuilt caches. Keep true.'],
  thunder_jit_executors: ['Thunder 执行器组合：nvfuser+sdpa 是推荐组合；torchcompile executor 仅实验。建议唯一可选值即可。', 'Thunder executor set; nvfuser+sdpa is the recommended pairing, torchcompile executor stays experimental.'],
  thunder_jit_cache_enabled: ['按模型/dtype/rank/shape/执行器/RNG 契约隔离缓存。建议保持 true。', 'Caches keyed by model/dtype/rank/shape/executor/RNG contract. Keep true.'],
  thunder_jit_cache_root: ['Thunder 编译缓存根目录。建议指向快盘独立目录。', 'Cache root for Thunder artifacts on a fast disk.'],
  thunder_jit_warmup_enabled: ['训练前用代表 shape 预编译。建议首训开一次，命中缓存后可关。', 'Pre-compiles representative shapes before training. Enable once; caches cover later runs.'],
  thunder_jit_progress_enabled: ['显示编译进度/缓存命中/局部回退状态。建议保持 true 便于观察。', 'Shows compile progress, cache hits and partial fallbacks. Keep on for visibility.'],
  thunder_jit_enabled: ['旧版 Thunder 总开关，仅保留旧配置迁移。新配置请用「训练执行后端」。建议 false。', 'Legacy Thunder master switch kept for old configs; use the execution-backend selector instead. Keep false.'],
  torch_compile: ['旧版 torch.compile 开关，仅保留旧配置迁移。新配置请用「训练执行后端」。建议 false。', 'Legacy torch.compile switch kept for old configs; use the execution-backend selector instead. Keep false.'],

  // ── 损失工程（频带/感知/多尺度/线稿/Gram/LPIPS/DCT/Wavelet/对比） ──
  pattern_loss_enabled: ['Pattern Loss：按 DWT 频带（LL 低频 / LH·HL·HH 高频）分别施加损失，精细控制结构 vs 细节。建议明确想约束纹理时开启。', 'Pattern Loss applies losses per DWT band (low-freq LL vs high-freq LH/HL/HH) for structure-vs-detail control. Use to discipline textures deliberately.'],
  pattern_loss_levels: ['DWT 分解层数。推荐范围：1（默认）～4，越多越大尺度约束。', 'DWT decomposition levels. Recommended: 1-4; more means larger-scale constraints.'],
  pattern_loss_ll_type: ['低频带损失函数类型。建议 l2 保整体结构。', 'Loss type for the low-frequency band. l2 preserves global structure best.'],
  pattern_loss_ll_weight: ['低频带权重。推荐范围：1（默认）；过高会压制高频学习。', 'Low-band weight. Recommended: 1; higher suppresses high-frequency learning.'],
  pattern_loss_high_type: ['高频带损失函数类型。建议 huber 对离群纹波稳健。', 'High-band loss type; huber resists outlier ripples.'],
  pattern_loss_high_weight: ['高频带权重。推荐范围：2（默认）附近，强调细节。', 'High-band weight emphasizing detail. Recommended: ~2.'],
  pattern_loss_high_huber_c: ['高频 huber 过渡阈值。建议 0.1（默认）。', 'Huber delta for the high band. Keep 0.1.'],
  dct_frequency_enabled: ['DCT 频域损失：对高频分量加权，抑制网纹/噪点。建议纹理发飘时试。', 'DCT frequency-domain loss boosts high-frequency penalties against meshing/noise. Try when textures shimmer.'],
  dct_frequency_weight: ['DCT 损失相对主损失权重。推荐范围：0.05–0.15。', 'DCT loss weight relative to main loss. Recommended: 0.05-0.15.'],
  dct_frequency_high_weight: ['高频相对低频的权重倍数。建议 2.0（默认）。', 'High-vs-low frequency weight multiplier. Keep 2.0.'],
  dct_frequency_low_cutoff: ['前多少比例算低频 cutoff。建议 0.3（默认）。', 'Fraction treated as low-frequency cutoff. Keep 0.3.'],
  dct_frequency_min_t: ['sigma 窗口下界（0 全范围）。建议 0。', 'Lower sigma bound (0 = full range). Keep 0.'],
  dct_frequency_max_t: ['sigma 窗口上界（1 全范围）。建议 1。', 'Upper sigma bound (1 = full range). Keep 1.'],
  gram_texture_enabled: ['Gram 纹理损失：捕捉纹理统计特征防网状伪影。建议风格纹理任务开启。', 'Gram-matrix texture loss counters mesh-like artifacts by matching texture statistics.'],
  gram_texture_weight: ['Gram 损失权重。推荐范围：0.03–0.1。', 'Gram loss weight. Recommended: 0.03-0.1.'],
  gram_texture_normalize: ['除以 C×H×W 使损失与尺寸无关。建议保持 true（默认）。', 'Normalizes Gram by C*H*W so scale cancels. Keep true.'],
  gram_texture_min_t: ['sigma 窗口下界（0 全范围）。建议 0。', 'Lower sigma bound (0 = full range). Keep 0.'],
  gram_texture_max_t: ['sigma 窗口上界（1 全范围）。建议 1。', 'Upper sigma bound (1 = full range). Keep 1.'],
  lpips_latent_enabled: ['在 latent 域用 DiT 中间特征做感知相似度（类 LPIPS）。建议细节保真需求时开启。', 'Latent-space perceptual similarity from DiT mid-features, LPIPS-style. For detail fidelity goals.'],
  lpips_latent_weight: ['LPIPS latent 权重。推荐范围：0.05–0.15。', 'LPIPS-latent weight relative to main loss. Recommended: 0.05-0.15.'],
  lpips_latent_normalize_features: ['对特征做 L2 归一化更看方向不看幅度。建议保持 true（默认）。', 'L2-normalizes features so orientation matters over magnitude. Keep true.'],
  lpips_latent_min_t: ['sigma 窗口下界。建议 0。', 'Lower sigma bound. Keep 0.'],
  lpips_latent_max_t: ['sigma 窗口上界。建议 1。', 'Upper sigma bound. Keep 1.'],
  lineart_preservation_enabled: ['线稿保护损失：Sobel 提取 latent 边缘并加权保护。建议插画/线稿概念开启。', 'Line-art preservation via Sobel edge weighting inside latents. Great for illustration concepts.'],
  lineart_preservation_weight: ['线稿损失权重。推荐范围：0.05–0.2。', 'Line-art loss weight. Recommended: 0.05-0.2.'],
  lineart_preservation_edge_weight: ['边缘区域相对整体的放大倍数。建议 3.0（默认）。', 'Edge-region weight multiplier. Keep 3.0.'],
  lineart_preservation_min_t: ['sigma 窗口下界。建议 0。', 'Lower sigma bound. Keep 0.'],
  lineart_preservation_max_t: ['sigma 窗口上界。建议 1。', 'Upper sigma bound. Keep 1.'],
  wavelet_loss_enabled: ['像素空间之外叠加多尺度小波损失，稳结构提细节。建议大分辨率训练试验。', 'Adds multi-scale wavelet losses beside pixel space to steady structure and lift detail.'],
  wavelet_loss_weight: ['Wavelet 总权重。推荐范围：从很小值开始，例如 0.02–0.1。', 'Overall wavelet weight. Start small: 0.02-0.1.'],
  wavelet_loss_levels: ['小波分解层数，越高越偏大结构。推荐范围：1–4。', 'Wavelet levels; higher biases large structures. Range 1-4.'],
  wavelet_loss_base_loss: ['小波域基础损失类型。建议 l2 默认。', 'Base loss inside the wavelet domain. l2 default.'],
  wavelet_loss_high_freq_weight: ['高频子带权重。建议 2（默认）。', 'High-subband weight. Keep 2.'],
  wavelet_loss_approx_weight: ['额外约束最低频 LL 分量。推荐范围：保持 0；仅大尺度结构需要额外约束时再给小值。', 'Weight on the coarsest LL band. Recommended: keep 0 unless large-scale structure needs extra constraint.'],
  wavelet_loss_detail_boost: ['细节阶段的高频额外加权；0 关闭。建议 0 起步。', 'Extra high-frequency boost during detail phase; 0 off to start.'],
  wavelet_loss_sigma_gate: ['σ 低于该值时高频加权全开。建议 0.5（默认）。', 'Sigma below which high-frequency weighting saturates. Keep 0.5.'],
  contrastive_latent_enabled: ['对比式 latent 一致性：同一 clean latent 不同噪声对的表征拉近。建议实验性开启。', 'Contrastive consistency pulling representations of shared clean latents together across noise pairs. Experimental.'],
  contrastive_latent_weight: ['对比损失权重。推荐范围：0.05–0.2。', 'Contrastive loss weight. Recommended: 0.05-0.2.'],
  contrastive_latent_noise_pairs: ['每个样本构造的对比对数。推荐范围：1–5。', 'Noise pairs constructed per sample. Range 1-5.'],
  contrastive_latent_temperature: ['温度系数（保留参数，当前实现未使用）。建议保持默认。', 'Temperature coefficient (reserved; unused by current impl). Keep default.'],
  contrastive_latent_min_t: ['限制在中间噪声段的下界（如 0.2）。建议 0.2。', 'Lower bound confining pairs to mid noise (e.g. 0.2). Keep 0.2.'],
  contrastive_latent_max_t: ['中间噪声段上界（如 0.8）。建议 0.8。', 'Upper bound of the mid-noise window. Keep 0.8.'],
  multi_scale_supervision_enabled: ['在 DiT 中间层（4/8/12）做 student-teacher 特征监督。建议深层语义丢失时试验。', 'Student-teacher feature supervision at DiT mid-layers (4/8/12). Try when deep semantics lag.'],
  multi_scale_supervision_weight: ['多尺度监督权重。推荐范围：0.1–0.3。', 'Multi-scale supervision weight. Recommended: 0.1-0.3.'],
  multi_scale_loss_type: ['中间层特征损失类型。建议 mse 起步。', 'Feature loss type for mid layers. Start with mse.'],
  multi_scale_min_t: ['只在指定 σ 范围内应用监督的下界。建议 0。', 'Lower σ bound applying supervision. Keep 0.'],
  multi_scale_max_t: ['监督 σ 上界。建议 1。', 'Upper σ bound for supervision. Keep 1.'],
  scale_guidance_mode: ['一键引导训练侧重不同尺度（off 关闭）。建议 off 起步按需选档。', 'One-knob scale-focus guidance; off by default, choose a tier when composition needs biasing.'],

  // ── 采样探针（预览加速 seam 家族） ──
  sample_cache_seam_backend: ['预览加速方案选择：spectrum 块缓存线性外推 / smoothcache 误差引导。建议 spectrum。', 'Preview acceleration backend: Spectrum block-cache extrapolation vs SmoothCache error gating. Spectrum first.'],
  sample_cache_seam_window_size: ['线性外推使用的历史窗口长度。建议 3（默认）。', 'History window length for linear extrapolation. Keep 3.'],
  sample_spectrum_probe: ['Spectrum 块缓存外推探针（与预览加速 seam 独立的诊断）。建议诊断期开。', 'Diagnostic probe for Spectrum block-cache extrapolation, independent of the preview seam. Diagnostic use.'],
  sample_spectrum_window_size: ['Spectrum 历史窗口大小。建议 2（默认）。', 'Spectrum history window size. Keep 2.'],
  sample_spectrum_warmup_steps: ['预热步数内不做外推。建议 6。', 'Warm-up steps before extrapolation engages. Keep 6.'],
  sample_spectrum_stop_caching_step: ['-1 不提前停；≥0 从该步停缓存。建议 -1。', '-1 never stops early; >=0 halts caching at that step. Keep -1.'],
  sample_spectrum_flex_window: ['柔性窗口系数。建议 0.25（默认）。', 'Flex-window coefficient. Keep 0.25.'],
  sample_smoothcache_error_threshold: ['块间误差低于该阈值才复用缓存。建议 0.08（默认）。', 'Reuse cache only when inter-block error is under this. Keep 0.08.'],
  sample_smoothcache_probe: ['SmoothCache 误差引导探针（诊断）。建议诊断期开。', 'Error-guided SmoothCache probe for diagnostics.'],
  sample_smoothcache_warmup_steps: ['预热内不跳过任何计算。建议 2。', 'No skipping during warm-up steps. Keep 2.'],
  sample_tgate_probe: ['T-GATE 交叉注意力复用探针。建议诊断期开。', 'T-GATE cross-attn reuse probe for diagnostics.'],
  sample_tgate_skip: ['真正复用交叉注意力输出跳算。关=默认路径。建议验证 probe 后再开。', 'Actually reuses cross-attn outputs to skip compute; validate the probe first.'],
  sample_tgate_start_step: ['从此采样步开始考虑复用。建议 0。', 'Sampling step from which reuse is considered. Keep 0.'],
  sample_tgate_min_block: ['小于该索引的 block 不跳过（护浅层）。建议 0。', 'Blocks below this index are never skipped. Keep 0.'],
  sample_fsg_probe: ['FSG 频带引导探针。建议诊断期开。', 'Frequency-band guidance probe for diagnostics.'],
  sample_fsg_apply: ['关=仅探针记录；开=真正修改采样轨迹。建议先 probe 后 apply。', 'Probe-only when off; actually bends the trajectory when on. Probe first.'],
  sample_fsg_band_start: ['σ 频带起点。建议 0.45。', 'Start of the guided sigma band. Keep 0.45.'],
  sample_fsg_band_end: ['σ 频带终点。建议 0.85。', 'End of the guided sigma band. Keep 0.85.'],
  sample_fsg_k: ['FSG 阶/组数。建议 3（默认）。', 'Number of FSG orders/groups. Keep 3.'],
  sample_fsg_gamma: ['引导强度；0 关闭。建议 0 起步。', 'Guidance strength; 0 disables. Start 0.'],
  sample_fsg_d_sigma: ['σ 扰动步长。建议 0.1（默认）。', 'Sigma perturbation step. Keep 0.1.'],
};
