// SPDX-License-Identifier: LicenseRef-PolyFormNoncommercial-1.0.0
// desc 文案表 —— 家族特化（Anima/Newbie/H3/LTX-2.x/Flux2/Wan2.2/ZImage/Krea2/Boogu）、
// ControlNet/IP-Adapter/TI、向导可见杂项。
export default {
  // ── 向导杂项 ──
  performance_expert_mode: ['展开高级性能选项（编译加速、Triton 优化器、交换策略等）。建议新手关闭；调优显存/速度时再开。', 'Reveals expert performance options (compile backends, Triton optimizers, swap strategies). Keep off until tuning.'],
  dry_run: [{ zh: '默认开启：只校验数据集/配置契约并写 metadata stub，不启动真实训练。真实训练前请确认已关闭。推荐范围：试跑新配置保持 true，正式跑改 false。', en: 'On by default: validates dataset/config contracts and writes a metadata stub without launching real training. Turn off for the actual run.' }],
  batch_size: ['短测流程的批大小。当前真实短测仅允许 batch=1。推荐范围：固定 1。', 'Batch size for smoke runs; true smoke testing currently allows only 1. Keep 1.'],
  adapter_type: ['Newbie 适配器类型选择，会映射到原生 LoRA 路线。建议 lora；其余为预留入口。', 'Newbie adapter kind mapped onto the native LoRA route. Keep lora; others are reserved entries.'],
  lora_type: ['适配器类型主入口：LoRA 是基础路线。DoRA/HydraLoRA 等变体在「LoRA 结构变体」卡以独立旗标托管，勿在此重复选。建议 lora。', 'Primary adapter type; LoRA is the base route while DoRA/HydraLoRA variants live on their own toggles card. Keep lora.'],
  attn_mode: ['注意力实现：自动跟随启动环境默认；显式选择会写入 attention_backend。注意显存优化器仅在 FlashAttention 2 后端真正生效。建议 auto。', 'Attention implementation; explicit picks write through to attention_backend. Note VRAM optimizers only engage on FlashAttention 2. Keep auto.'],
  attention_backend: ['强制指定注意力后端（auto 跟随环境）。建议 auto；排查算子兼容性时再显式指定。', 'Force an attention backend (auto follows the environment). Explicit values are for compatibility debugging.'],
  flashattn: ['强制 FlashAttention 2（高级覆盖）。建议默认关闭跟随环境；长序列提速明显但需库支持。', 'Force FlashAttention 2 as an override. Off by default; strong long-sequence speedups when installed.'],
  xformers: ['强制 xformers 内存高效注意力（高级覆盖）。建议默认关闭，旧卡兜底用。', 'Force xformers memory-efficient attention as an override; mostly a legacy-GPU fallback.'],
  mem_eff_attn: ['强制省显存 attention（比 xformers 更保守的实现）。建议默认关闭。', 'Force the conservative memory-efficient attention path. Off by default.'],
  sdpa: ['强制 PyTorch SDPA 注意力（高级覆盖）。建议默认关闭。', 'Force PyTorch SDPA attention as an override. Off by default.'],
  sageattn: ['强制 SageAttention（高级覆盖）。建议默认关闭跟随启动环境，确认库可用后再强制。', 'Force SageAttention as an override; default follows the launcher environment.'],
  sdpa_backend_policy: ['SDPA 内部后端策略（cutlass/flash/mem_efficient），仅当解析为 SDPA 时生效。建议 cutlass 默认。', 'Inner SDPA backend policy; applies only when SDPA is chosen. cutlass default works well.'],
  split_attn: ['按 head 拆分 attention 计算省显存。建议显存临界时开，速度略降。', 'Splits attention across heads to trim VRAM at slight speed cost. Try when marginal on memory.'],
  model_fused_qkv: ['模型级物理 QKV/KV 打包权重加载。与 Triton QKV 同开时作为未命中回退路径。建议默认关闭。', 'Physically fused QKV/KV weight packing used as fallback when Triton QKV misses. Off by default.'],
  cross_attn_fused_kv: ['启用 SDXL cross-attn 的 fused K/V 投影内核提速。建议验证过稳定性后开启。', 'Fused K/V projection kernels for SDXL cross-attention. Enable after validating stability.'],
  te_vae_offload_strategy: ['TE/VAE 在训练生命周期中的上卡策略：phase 分阶段驻留为默认。建议 phase。', 'When TE/VAE occupy GPU across the run lifecycle; phased residency is the default.'],
  sdxl_unet_backend: ['SDXL U-Net 执行后端：diffusers 稳定默认；备选路线性能实验用。建议 diffusers。', 'SDXL U-Net execution backend; diffusers is the stable default, alternatives are performance experiments.'],
  low_vram_autotune_mode: ['Triton 低显存自动调优档位。建议默认 off 保持标准行为，显存临界时改 auto。', 'Auto-tuning level for Triton under low VRAM. off keeps stock behavior; try auto when marginal.'],
  native_runtime_profile: ['原生运行时加速档位：SDXL 支持 aggressive；Anima/Newbie 另有 DiT 快速档。低显存与实验档仅 Anima 适用。建议 standard。', 'Native-runtime speed profile: aggressive exists for SDXL; DiT fast tiers for Anima/Newbie; lean/experimental tiers are Anima-only. Keep standard.'],
  lulynx_optimization_enabled: ['系统级调度优化包：BlockSwap auto→pipeline、异步 D2H、stream-ordered 预取、TREAD/DiffCR 跳算等联动。建议追求吞吐时开启并观察稳定性。', 'System-level optimization bundle (swap pipelining, async D2H, stream-ordered prefetch, TREAD/DiffCR skipping). Enable for throughput once stable.'],
  lulynx_steady_accel: ['Anima/Newbie 稳态算子加速包（Triton inject + TC-FMT + fused RoPE）。auto 按家族能力判定。建议 auto。', 'Steady-state operator pack for Anima/Newbie (Triton inject + TC-FMT + fused RoPE); auto gates per family. Keep auto.'],
  execution_backend: ['训练执行后端：optimized 免图编译最稳；thunder 为推荐编译后端；torch.compile 备选。建议 optimized 或 thunder。', 'Execution backend: optimized runs without graph compilation; thunder is the recommended compiled path; torch_compile alternative. Prefer optimized or thunder.'],
  execution_backend_allow_fallback: ['Thunder/torch.compile 不可用或不安全时回退优化运行时。建议保持 true 保证可跑。', 'Fall back to the optimized runtime when Thunder/torch.compile is unsafe or unavailable. Keep true.'],
  turbocore_optimizer_mode: ['Lulynx Triton 优化器档位：off 标准 PyTorch step；auto 自动判定；force 强制且不可用即报错。需关 TurboCore CUDA 总开关才生效。建议 auto 起步。', 'Lulynx Triton optimizer level: off stock PyTorch, auto decides, force errors out if unsupported (requires the TurboCore CUDA master switch off). Start with auto.'],
  turbocore_data_pipeline_enabled: ['caption DataLoader 走 Rust 解码管线降 CPU/IO 瓶颈，不依赖 TurboCore 优化器开关。建议 IO 瓶颈时开启。', 'Routes caption loading through the Rust decode pipeline to ease CPU/IO bottlenecks; independent of the optimizer switch.'],
  turbocore_profile: ['TurboCore 性能档位：basic 基础；fast 自动联动 Vortex Aircon 与 fused optimizer。建议 basic 稳妥起步。', 'TurboCore profile: basic default; fast couples Vortex Aircon and fused optimizer automatically. Start basic.'],
  turbocore_prefetch_depth: ['预取队列深度，默认 2：加深隐藏延迟但占显存。推荐范围：2–4。', 'Prefetch queue depth (default 2); deeper hides latency but costs VRAM. Recommended: 2-4.'],
  turbocore_strict: ['优化内核失败时报错而非静默回退，便于调试。建议调试期开，日常关。', 'Error instead of silently falling back when optimized kernels fail. On for debugging, off otherwise.'],
  turbocore_tuned_kernel_disable: ['关闭 TurboCore 自动调优内核的全局开关。建议默认 false 保持启用。', 'Global kill-switch for autotuned TurboCore kernels. Keep false.'],
  turbocore_workspace_mb: ['kernel workspace 上限 MB，0 自动分配。建议 0。', 'Kernel workspace cap in MB; 0 allocates automatically. Keep 0.'],

  // ── Anima 特有 ──
  anima_faithful_forward: ['使用忠实原生 DiT 前向（native anima），与参考实现对齐。建议保持 true（默认）；性能实验才关。', 'Uses the faithful native Anima DiT forward matching the reference implementation. Keep true; off is for perf experiments.'],
  anima_train_llm_adapter: ['训练 LLM Adapter 附加分支（普通 Anima LoRA 不含它）。建议先跑普通 LoRA 基线再考虑，属进阶路径。', 'Trains the extra LLM-adapter branch beyond ordinary Anima LoRA. Advanced path; baseline plain LoRA first.'],
  anima_weighting_scheme: ['Loss 加权方案：留空不加权；uniform 是后端接受的 legacy 别名（等价不加权）。建议留空或按实验选择 sigma 加权族。', 'Loss weighting scheme; empty = none, uniform is an accepted legacy alias for none. Choose sigma-weighted variants deliberately.'],
  anima_model_prediction_type: ['模型预测目标：velocity 标准默认；noise/epsilon 预测加噪项；sample 预测干净样本。必须与底模一致。建议 velocity。', 'Prediction target: velocity (standard), noise/epsilon, or clean-sample. Must match your base model; keep velocity.'],
  anima_sigmoid_scale: ['sigmoid 分布的压缩系数，影响时间步集中程度。推荐范围：0.1–5，默认 1。', 'Compression factor of the sigmoid timestep distribution. Recommended: around default 1 (range 0.1-5).'],
  anima_progressive_full_finetune_enabled: ['按 schedule 逐块解冻 DiT 做 full 微调（显存随解冻增长）。建议显存充裕且 LoRA 达瓶颈时再用。', 'Progressively unfreezes DiT blocks toward full finetune as VRAM allows; use once LoRA plateaus and memory permits.'],
  anima_rematerializable_block_enabled: ['可重物化 block 原型（profile-only）。建议仅诊断分析用，不影响常规训练。', 'Rematerializable-block prototype (profile-only). For diagnostics rather than regular training.'],
  anima_rematerializable_block_mode: ['可重物化模式，当前仅 profile_only。建议保持。', 'Only profile_only exists today. Keep it.'],
  anima_mixed_loss_mask_policy: ['同一 batch 混合「有 mask/无 mask」样本时的策略：full_sample 无 mask 图整图计 loss。建议 full_sample。', 'Policy when masked and unmasked samples share a batch; full_sample treats unmasked images whole. Keep full_sample.'],
  anima_depth_expansion_enabled: ['模型扩层：加载时交错复制相邻层并把新层输出投影归零。仅支持 Anima 全参微调。建议显式想加深处才开。', 'Depth up-scaling interleaves copies of adjacent blocks with zeroed output projections; Anima full finetune only. Deliberate use only.'],
  anima_depth_expansion_target_layers: ['扩层后的目标层数，必须大于底模实际层数。推荐范围：Base 28 层可设 40。', 'Target depth after expansion; must exceed the base count (40 fits a 28-layer base).'],
  anima_depth_expansion_train_scope: ['扩层后训练范围：new_layers 只训新层最接近标准 DUS；peripheral 含输入/时间嵌入/输出层。建议 new_layers。', 'What trains after expansion: new_layers matches classic DUS; peripheral adds input/time/output shells. Keep new_layers.'],
  anima_cache_build_batch_size: ['缓存构建时一次编码的样本数。推荐范围：8（默认）起，OOM 减半。', 'Samples encoded per cache-build batch. Recommended: 8; halve on OOM.'],
  anima_cache_build_prefetch: ['缓存构建时 CPU worker 预解码下一块图像，更快但多占一份内存。建议内存充足时开启。', 'A CPU worker pre-decodes the next image chunk during cache build: faster with one extra host copy. Enable with spare RAM.'],
  anima_cache_target_resolution: ['缓存目标边长：0 跟随训练分辨率；<0 保持源图；>0 显式指定。推荐范围：0（默认）。', 'Cache-side target edge: 0 follows training resolution, negative keeps source size, positive sets explicit edge. Keep 0.'],
  anima_cache_resize_mode: ['缓存缩放模式：longest 长边对齐；shortest 短边对齐并封顶长边；freefit 不放大自由适配。建议 longest（默认）。', 'Cache resize mode: longest-edge align, shortest-edge cap, or freefit no-upscale. Keep longest.'],
  anima_cache_resize_max_edge: ['shortest 模式下长边封顶值；0 自动取 2× 目标分辨率。建议 0。', 'Long-edge cap in shortest mode; 0 auto-sets 2x target resolution. Keep 0.'],
  native_cache_mode: ['Anima 缓存模式：cache_first 用已有缓存；online_cache 冻结编码器在线补缓存；rebuild_cache 强制重建；force_cache_only 只建缓存不训。建议 cache_first。', 'Anima cache mode: reuse (cache_first), online top-up, forced rebuild, or build-only-and-exit. Keep cache_first.'],

  // ── Newbie 特有 ──
  newbie_safe_fallback: ['OOM 时自动尝试更保守的 Newbie 回退组合。建议保持 true（默认）提高存活率。', 'Automatically retries with a more conservative Newbie setup after OOM. Keep on for survival.'],
  newbie_cache_build_batch_size: ['首轮缓存构建每批编码图像数。推荐范围：8（默认），OOM 减半。', 'Images encoded per batch during first cache build. Recommended: 8; halve on OOM.'],
  newbie_cache_build_prefetch: ['首轮构建时 CPU 线程预解码下一批，与 GPU 编码重叠。建议内存充足开启。', 'CPU thread pre-decodes the next batch during first build to overlap GPU encoding. Enable with spare RAM.'],

  // ── H3 (MiniMax H3) ──
  h3_transformer_path: ['H3 Transformer（DiT 主干）权重文件路径。必填才能训练。', 'Path to the H3 transformer (DiT backbone) weights. Required for training.'],
  h3_text_encoder_path: ['Qwen3-VL 文本编码器权重路径。用于文本条件编码与缓存。', 'Path to the Qwen3-VL text encoder weights used for conditioning and caching.'],
  h3_video_vae_path: ['视频 VAE 权重路径，负责像素↔latent 转换的视频分支。', 'Video VAE weights converting pixels to latents for the video branch.'],
  h3_audio_vae_path: ['音频 VAE 权重路径（音视频联合任务需要）。', 'Audio VAE weights required for joint audio-video tasks.'],
  h3_fps: ['视频帧率，供 RoPE 时间编码使用。推荐范围：24（默认）与源素材一致。', 'Frame rate feeding RoPE temporal encoding. Match your footage; recommended ~24.'],
  h3_frame_count: ['每个训练 clip 的帧数。推荐范围：39（默认）附近；越长越吃显存。', 'Frames per training clip. Recommended: near default 39; longer clips cost more VRAM.'],
  h3_blocks_to_swap: ['交换到 CPU 的 Transformer block 数量上限（0-48）。推荐范围：16G 卡从 16 起，24G 可减半或不交换。', 'Transformer blocks kept on CPU (0-48). Recommended: start 16 on 16 GB; less or none on 24 GB.'],
  h3_block_swap_strategy: ['块交换调度：async 异步搬运掩盖延迟（推荐）；sync 同步简单稳妥。', 'Swap scheduling: async hides transfer latency (recommended); sync is simpler.'],
  h3_activation_offload_min_tensor_mb: ['激活卸载的最小张量体积阈值（MB）。推荐范围：10（默认）以上。', 'Minimum tensor size (MB) considered for activation offload. Recommended: >=10.'],
  h3_cache_latents: ['缓存视频/音频 latent 避免逐步重编码。建议保持 true（默认）。', 'Caches video/audio latents to avoid re-encoding each step. Keep true (default).'],
  h3_cache_text_encoder_outputs: ['缓存 Qwen3-VL 文本输出省 TE 显存与时间。建议 caption 固定保持 true。', 'Caches Qwen3-VL outputs to save TE memory and time. Keep true with fixed captions.'],
  h3_checkpoint_mode: ['激活检查点模式：unsloth 优化重算路径（推荐）/标准实现。', 'Activation checkpoint style: unsloth optimized recompute (recommended) vs standard.'],
  h3_partition: ['模型分区裁剪方案：fl2va_pruned 按任务裁剪非必需分支（推荐）。', 'Model partition plan; fl2va_pruned trims branches irrelevant to the task (recommended).'],
  h3_int8_gemm_mode: ['INT8 GEMM 选择模式：oracle 按层实测择优（推荐）/固定策略。', 'INT8 GEMM selection: oracle picks per-layer by measurement (recommended) vs fixed policy.'],
  h3_preserve_lora_master_dtype: ['LoRA master 权重保持 FP32 精度更新（推荐 true 防 8bit 舍入漂移）。', 'Keeps LoRA master weights in FP32 against low-bit rounding drift (recommended true).'],
  h3_depth_expansion_enabled: ['扩展 Transformer 深度（交错复制块+恒等初始化），全参微调专用。建议明确需要更深网络时才开启。', 'Expands transformer depth by interleaved copying with identity init; full-finetune feature.'],
  h3_depth_expansion_target_layers: ['扩层后的目标层数，须大于底模层数。推荐范围：按容量需求逐级加，不宜一次翻倍过多。', 'Target depth after expansion; must exceed the base count. Set by capacity needs.'],
  h3_depth_expansion_train_scope: ['扩层后的训练范围：new_layers 仅新层（接近经典 DUS）。建议 new_layers。', 'Post-expansion training scope; new_layers mirrors classic depth up-scaling. Keep new_layers.'],
  h3_timestep_shift: ['视频时间步 shift 映射，改变噪声调度重心。推荐范围：12（默认）附近微调。', 'Timestep shift mapping biasing the noise schedule for video. Tune near default 12.'],
  h3_video_sigma_shift: ['视频 σ 映射 shift，与 timestep shift 协同。推荐范围：12（默认）附近。', 'Sigma-mapping shift for video; coordinate with timestep shift. Default 12.'],
  h3_audio_sigma_shift: ['音频 σ 映射 shift。推荐范围：3（默认）附近。', 'Sigma-mapping shift for audio. Keep 3.'],
  h3_image_timestep_shift: ['单帧（图像）样本的时间步 shift。推荐范围：1（默认）附近。', 'Timestep shift for single-image samples. Keep 1.'],
  h3_cfg_scale: ['保真 CFG 强度（蒸馏模型常低 CFG）。推荐范围：1–16，默认 4 起步。', 'Faithfulness CFG strength (distilled models prefer low CFG). Probe upward from 4 within 1-16.'],
  h3_cfg_schedule: ['CFG 调度：constant 恒定；sigma 按低 σ 区间衰减。建议 constant 起步。', 'CFG schedule: constant, or decaying over low sigma. Start constant.'],
  h3_cfg_preservation_sigma_min: ['低于该 base σ 区间不做 CFG 保真（0 全程保真）。建议 0。', 'Skip CFG preservation below this base sigma (0 = everywhere). Keep 0.'],
  h3_condition_noise_clean: ['条件帧加噪洁净度：越接近 1 条件帧越干净。推荐范围：0.999（默认）附近。', 'Noising cleanliness of condition frames; closer to 1 keeps them cleaner. Keep 0.999.'],
  h3_video_only: ['只保留视频 latent 丢弃音频分支。纯视频任务建议 true 省显存。', 'Drops the audio branch keeping video latents only; saves VRAM for pure video tasks.'],
  h3_load_direct_to_device: ['transformer 张量直接装载到目标设备（swap=0 时避免整模内存镜像）。建议小内存机器开启。', 'Loads transformer tensors straight onto device avoiding a host mirror when swapping is off. Good for RAM-limited machines.'],
  h3_te_layer_streaming: ['缓存构建时逐层从 CPU 流式解码 Qwen3-VL（低显存更慢）。建议低显存构建时开。', 'Streams Qwen3-VL decode layer-by-layer from CPU during cache building: lean but slower. Use on tight VRAM.'],
  h3_prune_adaln_on_load: ['加载全量 BF16 checkpoint 时按 rank-8 SVD 裁剪 AdaLN（已剪模型上无效）。建议配合已剪枝模型使用。', 'Prunes AdaLN via rank-8 SVD when loading full BF16 checkpoints (no-op on pruned models).'],

  // ── LTX-2.x ──
  ltx23_timestep_sampling: ['flow matching 时间步采样方式，shift 重心偏移为默认。建议 shift。', 'Flow-matching timestep sampling; shift-biased is the default choice.'],
  ltx23_discrete_flow_shift: ['离散流 shift 系数。推荐范围：1.0（默认）附近。', 'Discrete-flow shift coefficient. Recommended: near 1.0.'],
  ltx23_fps: ['RoPE 使用的帧率，应与素材一致。推荐范围：24（默认），上限 60。', 'FPS used by RoPE; match source footage (default 24, max 60).'],
  ltx23_frame_stride: ['相邻采样帧之间的源帧间隔；1 逐帧，2 跳帧加倍时长覆盖。推荐范围：1（默认）。', 'Source-frame gap between sampled frames; 1 is frame-exact, 2 doubles temporal coverage. Keep 1.'],
  ltx23_target_frames: ['训练 clip 目标帧数；单图训练保持 1，视频按 8n+1 取值。推荐范围：1 或 9/17/25 等。', 'Target frames per training clip; 1 for images, else follow the 8n+1 pattern.'],
  ltx23_isolate_modalities: ['true 只做视觉任务，关闭 a2v/v2a 交叉。建议纯视觉训练保持 true（默认）。', 'Vision-only training disabling audio<->video crossings. Keep true for visual-only goals.'],
  ltx23_max_text_length: ['Gemma 文本缓存的 token 上限（2.3/2.5 共用）。推荐范围：256（默认）内。', 'Token cap for Gemma text caches shared by 2.3/2.5. Recommended: within default 256.'],
  ltx23_depth_expansion_enabled: ['交错复制 LTX 双流 block 并以恒等残差初始化新增层（输出投影归零），最终保存完整新底座。建议仅在明确要扩容量的全参微调开启。', 'Interleaves copied dual-stream blocks with identity-residual init (zeroed output projections), saving a complete new base.'],
  ltx23_depth_expansion_target_layers: ['扩层后的 block 总数，必须大于原生层数。推荐范围：22B-dev 原生 48，可升至 64–72。', 'Total blocks after expansion (48 native on 22B-dev); must exceed the original count.'],
  ltx23_depth_expansion_train_scope: ['扩层训练范围：只训新增层 / 外围模块 / 全部。建议 new_layers。', 'Post-expansion scope: new layers only, plus periphery, or everything. Keep new_layers.'],

  // ── Wan22/ZImage/Krea2/Boogu/Flux2 家族杂项 ──
  wan22_model_variant: ['Wan2.2 变体选择（14B/A14B 等），决定权重结构与缓存格式。必须与底模一致。', 'Wan2.2 variant selection determining weight layout and cache format; match your checkpoint exactly.'],
  wan22_noise_stage: ['Wan2.2 双专家噪声阶段划分（high/low）。由底模配对决定，建议保持默认。', 'High/low noise stage split across the paired experts; dictated by your checkpoint pair.'],
  wan22_timestep_sampling: ['Wan2.2 时间步采样分布。建议保持默认 shift 族。', 'Wan2.2 timestep sampling distribution; the shift family default fits most runs.'],
  zimage_timestep_sampling: ['ZImage 时间步采样分布。建议保持默认。', 'ZImage timestep sampling distribution. Keep the default.'],
  krea2_training_mode: ['Krea2 训练模式选择。建议按任务选默认档。', 'Krea2 training-mode selector; the default tier suits most tasks.'],
  krea2_vram_preset: ['Krea2 显存预设档。建议按实际显存选相邻档，不超配。', 'Krea2 VRAM preset tier; pick the tier matching actual VRAM, never above.'],
  krea2_sigma_selective_threshold: ['Krea2 σ 选择性阈值：仅特定噪声段参与计算。建议默认。', 'Selective threshold over sigma bands for Krea2 compute. Keep default.'],
  boogu_model_version: ['Boogu 底模版本声明。必须与实际文件匹配否则权重错载。', 'Boogu base-model version tag; mismatches load wrong weight layouts.'],
  boogu_task: ['Boogu 任务类型（lora/edit 等）。按目标产物选择。', 'Boogu task kind (lora/edit...). Pick by desired artifact.'],
  flux2_model_version: ['Flux2 版本声明，决定缓存与结构分支。必须与底模一致。', 'Flux2 version tag controlling structure branches and caches; must match the checkpoint.'],
  lumina_training_variant: ['Lumina 训练变体声明。与底模结构对应，保持默认即可。', 'Lumina variant tag aligned with the base architecture; defaults usually correct.'],

  // ── ControlNet / IP-Adapter / TI ──
  ip_adapter_enabled: ['IP-Adapter 图像条件注入：参考图引导生成。建议有强风格/主体参照需求时开启。', 'IP-Adapter injects reference-image conditioning for style/subject guidance.'],
  ip_adapter_scale: ['IP-Adapter 条件强度 0–1+。推荐范围：0.5–1（默认 1）。', 'Conditioning strength of IP-Adapter. Recommended: 0.5-1.'],
  ip_adapter_cond_dim: ['注入主干的条件维（SigLIP 为 1152），必须与编码器匹配。推荐范围：保持默认值不动。', 'Condition width projected into the backbone (1152 for SigLIP); must match the encoder. Keep default.'],
  ip_adapter_encoder_dim: ['图像编码器输出维，与所选 encoder 绑定。推荐范围：保持默认值不动。', 'Image-encoder output dimension tied to the chosen encoder. Leave unchanged.'],
  ip_adapter_num_image_tokens: ['每图投影 token 数。推荐范围：16（默认）。', 'Projected tokens per image. Recommended: 16.'],
  ip_adapter_cond_mode: ['条件融合方式（concat 等）。建议 concat 默认。', 'How conditions fuse into the stream; concat default.'],
  ip_num_tokens: ['IP-Adapter 注入 UNet 的 token 数量。推荐范围：16（SDXL 默认）。', 'Tokens injected into UNet by IP-Adapter. Recommended: 16 on SDXL.'],
  lllite_cond_emb_dim: ['UNet 条件 embedding 维度（ControlNet-LLLite）。推荐范围：32（默认）。', 'Condition embedding width for ControlNet-LLLite. Keep 32.'],
  lllite_mlp_dim: ['LLLite adapter MLP 瓶颈宽度。推荐范围：64（默认）。', 'MLP bottleneck width of the LLLite adapter. Keep 64.'],
  lllite_dropout: ['LLLite 条件路径 dropout。推荐范围：0–0.1，默认 0。', 'Dropout on the LLLite condition path. 0-0.1, default 0.'],
  lllite_skip_input_blocks: ['不向 UNet input blocks 注入 LLLite。建议轻量控制时开启减少参数。', 'Skip LLLite injection into input blocks to slim parameters.'],
  lllite_skip_output_blocks: ['不向 output blocks 注入（默认跳过，社区惯例）。建议保持 true。', 'Output-block injection skipped by community convention. Keep true.'],
  anima_controlnet_target_layers: ['Anima ControlNet 注入到 DiT 的哪些 Linear（self_attn_q 等）。建议默认 self_attn_q 单点起步。', 'Which DiT Linears receive Anima-ControlNet injections. Start with the default self_attn_q hook.'],
  anima_controlnet_cond_dim: ['条件图像编码器中间通道宽。推荐范围：64（默认）。', 'Intermediate width of the condition-image encoder. Keep 64.'],
  anima_controlnet_cond_emb_dim: ['共享条件嵌入维度。推荐范围：32（默认）。', 'Shared conditioning embed dimension. Keep 32.'],
  anima_controlnet_cond_resblocks: ['条件主干残差块数量，0 关闭。推荐范围：1（默认）。', 'Residual blocks in the condition trunk; 0 disables. Keep 1.'],
  anima_controlnet_mlp_dim: ['每层 down/mid/up 与 FiLM 隐宽。推荐范围：64（默认）。', 'Hidden width for down/mid/up and FiLM layers. Keep 64.'],
  anima_controlnet_multiplier: ['条件残差整体倍率。推荐范围：0.5–1，默认 1。', 'Global scale on injected condition residuals. Recommended: 0.5-1.'],
  anima_controlnet_dropout: ['mid 后 dropout。推荐范围：0（默认）。', 'Dropout after the mid projection. Keep 0.'],
  anima_controlnet_use_aspp: ['多尺度 ASPP 池化，对 depth/分割类全局结构更有益。建议 depth/分割任务开启，线稿类建议关闭。', 'Multi-scale ASPP pooling helps dense/global structures like depth; skip for line art.'],
  ti_placeholder_token: ['Textual Inversion 的占位符 token（如 <lulu>）。建议用尖括号包裹的独特词，避开分词歧义。', 'Placeholder token for Textual Inversion (e.g. <lulu>); make it unique and bracketed to avoid tokenizer ambiguity.'],
  num_vectors_per_token: ['每个占位符 token 学习的向量数（TI 容量）。推荐范围：1–4；越大越难收敛。', 'Learned vectors per placeholder token (TI capacity). Recommended: 1-4; higher is harder to converge.'],
  concept_edit_mode: ['概念编辑模式（定向增强/削弱某概念）。建议从默认模式开始阅读预检说明。', 'Concept-edit operating mode (strengthen/suppress a concept). Start from the default and read preflight notes.'],
  concept_edit_method: ['概念编辑的具体实现方法选择。建议默认方法起步。', 'Concrete concept-edit algorithm selection. Default first.'],
  concept_edit_use_diff_mask: ['编辑区域使用差分 mask 约束改动范围。建议只想改局部时开启。', 'Constrain edits via difference masks. Enable for localized changes only.'],
  concept_edit_base_model: ['概念编辑参照的基模型路径。建议与训练底模同源。', 'Reference base model for concept editing; same lineage as the training base preferred.'],
  concept_edit_data_dir: ['概念编辑数据目录。结构与训练数据集一致。', 'Dataset folder for concept editing; same layout as training datasets.'],
  concept_edit_diff_alt_ratio: ['差分/交替样本比例。建议 0.2–0.5 试探。', 'Ratio between difference and alternate samples. Probe 0.2-0.5.'],
  concept_edit_fixed_timestep_per_batch: ['同一 batch 固定时间步（减少方差）。建议实验性开启。', 'Fixes the timestep within a batch to cut variance. Experimental.'],
  concept_edit_timestep_curriculum: ['时间步课程式推进。建议长训精修时使用。', 'Curriculum progression over timesteps for long refinement runs.'],
  concept_edit_timestep_curriculum_buckets: ['课程分桶边界定义。建议默认均匀分桶。', 'Bucket boundaries for the timestep curriculum; even buckets work by default.'],

  // ── 杂项布尔/枚举 ──
  allow_tokenizer_only_clip: ['允许加载只有 tokenizer 的不完整 CLIP/Jina 资源（仅分词用途）。建议仅在明确知道后果时开启。', 'Permit tokenizer-only CLIP/Jina resources (tokenization only). Enable only with full awareness of the limitation.'],
  alpha_mask: ['读取 PNG alpha 通道作为 loss mask。建议透明背景素材且只想学前景时开启。', 'Use the PNG alpha channel as the loss mask. Ideal for transparent-background assets focusing on subjects.'],
  freeze_extractors: ['冻结 JTP-3 与 Waifu CLIP 特征提取器。建议保持 true（默认）防辅助分支漂移。', 'Freezes the JTP-3/Waifu CLIP extractors to stop auxiliary drift. Keep true (default).'],
  include_waifu_score: ['启用 Waifu Scorer v3 额外特征分支。建议审美导向任务开启，一般概念训练关闭。', 'Adds the Waifu Scorer v3 aesthetic branch; useful for aesthetics-driven goals, off otherwise.'],
  cls_loss_weight: ['in_domain 二分类损失权重。推荐范围：1（默认）附近。', 'Weight of the in-domain binary classification loss. Recommended: near 1.'],
  enable_base_weight: ['差异炼丹：叠加一个基础权重参照网络。建议实验性玩法，常规训练关闭。', 'Base-weight mixing experiment (difference blending). Novelty feature; keep off normally.'],
  enable_mixed_resolution_training: ['阶段分辨率训练（仅 SDXL）：低分辨率热身高分辨率收尾。建议长训提质时开启。', 'Staged-resolution training (SDXL only): warm up low-res, finish high-res. Good for longer quality runs.'],
  flow_model: ['启用 Rectified Flow / Flow Matching 目标。建议仅在 flow 类底模上开启，UNet 经典底模不要开。', 'Switches to Rectified Flow objectives; pair with flow-based bases only, never classic UNet checkpoints.'],
  flow_uncertainty_weighting_enabled: ['EDM2 式自适应损失权重：学习按 σ 的不确定度 u(σ)。建议实验性开启对比。', 'EDM2-style learnable per-sigma uncertainty weighting u(sigma). Experimental but principled.'],
  flow_uncertainty_weighting_channels: ['Fourier 特征库大小。推荐范围：128（默认）。', 'Fourier feature bank size. Recommended: 128.'],
  flow_uncertainty_weighting_lr: ['不确定度参数学习率。推荐范围：0.01（默认）附近。', 'LR for uncertainty parameters. Recommended: ~0.01.'],
  flow_timestep_distribution: ['RF 时间步采样分布（logit_normal 默认等）。建议 logit_normal。', 'RF timestep distribution; logit_normal is the sane default.'],
  flow_logit_mean: ['logit-normal 均值：正偏高频段采样。建议 0 居中，偏细节给负值。', 'Mean of logit-normal sampling; negative shifts toward detail bands. Keep 0 centered.'],
  flow_logit_std: ['logit-normal 标准差（>0）。越小越集中于均值段。建议 1。', 'Std of logit-normal sampling (>0); smaller concentrates the band. Keep 1.'],
  flow_use_ot: ['按 cosine 最优传输重排 latent 配对。建议小 batch 收敛慢时试验。', 'Re-pairs latents by cosine OT coupling. Try on small-batch slow convergence.'],
  flow_uniform_shift: ['按像素数动态偏移 RF 时间步。建议多分辨率混合训练开启。', 'Shifts RF timesteps dynamically by pixel count; useful for mixed-resolution sets.'],
  flow_uniform_base_pixels: ['分辨率偏移的基准像素数（1024²=1048576）。建议与主分辨率面积一致。', 'Reference pixel count for resolution-aware shifting (1024^2 = 1048576); match your main area.'],
  flow_uniform_static_ratio: ['固定偏移比率，填写后覆盖动态偏移；留空禁用。建议留空走动态。', 'Static shift ratio overriding dynamic logic; empty disables. Prefer dynamic.'],
  discrete_flow_shift: [
    { zh: '离散流采样的 shift 参数：越大越偏向高噪声段。Flux 族推荐范围：3（默认）附近，社区常用 3–4；其他模型族以各自默认为准。', en: 'Discrete-flow sampling shift; higher favors high-noise segments. Flux family: recommended near the default 3, community range 3-4; other model families follow their own default.', only: 'Flux 族' },
    { zh: '离散流采样的 shift 参数：越大越偏向高噪声段。推荐范围：常用 3–4，以模型族默认为准。', en: 'Discrete-flow sampling shift; higher favors high-noise segments. Commonly 3-4; defer to your model family default.' },
  ],
  timestep_sampling: ['扩散时间步采样分布（shift/logit_normal/uniform 等）。建议 shift（默认）对多数 flow 模型最佳。', 'Diffusion timestep distribution (shift/logit_normal/uniform...). shift suits most flow models.'],
  timestep_sampling_mode: ['时间步采样模式的补充开关（disabled 关闭特殊采样）。建议 disabled 默认。', 'Aux switch over timestep-sampling modes; disabled keeps standard behavior.'],
  guidance_scale: ['CFG/Guidance 强度（LCM-LoRA 类低值）。推荐范围：LCM 1.0–2.0 起测；常规蒸馏按教师设定。', 'CFG/guidance strength; start 1.0-2.0 for LCM-style models, otherwise follow your teacher setup.'],
  layered_alpha_enabled: ['按模块类型（attention/MLP）分层设置 alpha。建议精细控容时开启，一般保持关闭。', 'Per-module-type alpha tables for fine capacity control; niche, off by default.'],
  model_to_condition_enabled: ['启用共享条件生成协议（ModelToCondition）。建议相关管线要求时开启。', 'Enables the shared ModelToCondition protocol used by specific pipelines.'],
  native_resume_save_precision: ['原生续训伴生文件精度：float 完整保留 master（默认）。fp16/bf16 省一半体积但续训从舍入值开始。建议 float。', 'Precision of native resume sidecars: float preserves masters exactly (default); half types halve size but resume from rounded weights.'],
  quant_requantize_policy: ['对已量化模型的再量化策略：avoid 退避防二次量化噪声（默认）。建议 avoid。', 'Requantization policy for already-quantized bases; avoid sidesteps double-quantization noise. Keep avoid.'],
  trust_remote_code: ['允许 transformers/diffusers 执行模型仓库自带自定义代码。安全敏感：仅对可信来源开启。', 'Allows repo-provided custom code execution in transformers/diffusers. Security-sensitive: trusted sources only.'],
  cooldown_every_n_epochs: ['每 N 轮插入冷却期让 GPU 降温。推荐范围：2–5；配合温度目标使用。', 'Insert a cooldown every N epochs so the GPU breathes. Recommended: 2-5 with a temperature target.'],
  cooldown_minutes: ['每次冷却至少暂停的分钟数。推荐范围：5–15，视散热条件。', 'Minimum minutes per cooldown pause. Try 5-15 depending on cooling.'],
  cooldown_poll_seconds: ['冷却期温度轮询间隔秒。推荐范围：15（默认）附近。', 'Temperature poll interval during cooldowns. Keep 15.'],
  cooldown_until_temp_c: ['温度降到该值以下才继续训练。推荐范围：60–70℃，视显卡健康目标。', 'Resume only below this temperature. Aim 60-70 C for longevity.'],
  gpu_duty_cycle: ['每个优化步后按比例插入空闲降温（0.2 = 20% 占空比让渡）。推荐范围：0.2–0.5 过热环境。', 'Idle fraction inserted after each step for thermals (0.2 = 20% yield). Use 0.2-0.5 in hot environments.'],
  gpu_lock_clocks_mhz: ['训练前用 nvidia-smi 锁核心频率上限（需管理员权限）。推荐范围：过热环境锁到基准的 80–90%。', 'Locks core clock ceiling via nvidia-smi before training (admin needed). Cap at 80-90% baseline when overheating.'],
  gpu_power_limit_w: ['训练前设置功率墙瓦数。推荐范围：额定值的 70–90%，换温度余量。', 'Sets the power limit in watts before training. 70-90% of rated buys thermal headroom.'],
  gpu_target_temp_c: ['温度闭环目标：超过则自动降低有效占空比。推荐范围：70℃ 附近。', 'Closed-loop temperature target lowering duty cycle past it. 70 C is a common pick.'],
  gpu_circuit_device_index: ['熔断监控轮询的 GPU 索引（NVML 序号）。推荐范围：单卡保持 0。', 'GPU index polled for circuit-breaker monitoring. Recommended: 0 on single-GPU.'],
  gpu_circuit_poll_interval_steps: ['每 N 步轮询一次 GPU 健康。建议 10（默认）。', 'Health-poll cadence in steps. Keep 10.'],
  gpu_circuit_temp_c: ['达到该温度硬熔断（OPEN）。0 关闭温度硬断。建议过热史机器给 85。', 'Hard trip temperature; 0 disables. Consider 85 on heat-troubled rigs.'],
  gpu_circuit_temp_warn_c: ['硬阈之下的警告带温度；0 关闭警告。建议比硬阈低 5–10℃。', 'Warning band below the hard threshold; 0 off. Set 5-10 C under the trip point.'],
  gpu_circuit_trip_on_ecc: ['检测到 ECC 未纠正错误增量立即熔断。建议数据安全优先时保持 true。', 'Trip immediately on ECC uncorrected increments. Keep on to protect data integrity.'],
  gpu_circuit_trip_on_throttle: ['检测到 critical throttle 即熔断。建议长期高温环境开启。', 'Trip on critical throttle events. Worth enabling in hot environments.'],
  gpu_circuit_vram_util_pct: ['显存占用达到该百分比熔断（0 关闭）。建议 98 防雪崩 OOM。', 'Trip at this VRAM utilization percent (0 off). 98 guards against OOM cascades.'],
};
