// SPDX-License-Identifier: LicenseRef-PolyFormNoncommercial-1.0.0
// desc 文案表 —— 预览出图 / 质量评估 / 蒸馏与少步实验。
export default {
  enable_preview: ['训练中定期出预览图观察收敛方向。建议正式训练开启（每轮 1–2 张足够），显存极限时关闭。', 'Generates preview images during training to watch convergence. Enable with 1-2 images per round; disable at extreme VRAM.'],
  sample_every_n_epochs: ['每 N 轮生成一次预览。推荐范围：1（小数据集）～4；0 关闭按轮采样。', 'Preview every N epochs. Recommended: 1-4; 0 disables epoch-based sampling.'],
  sample_every_n_steps: ['每 N 步生成一次预览，比按轮更细。推荐范围：200–1000；0 关闭。', 'Preview every N steps for finer granularity. Recommended: 200-1000; 0 disables.'],
  sample_every: ['后端主频率键：每 N 步生成预览（与 sample_every_n_steps 同义的主入口）。建议二选一填写。', 'Backend primary cadence key: preview every N steps (same intent as sample_every_n_steps). Fill one of them.'],
  sample_at_first: ['训练开始前先生成一张预览确认提示词效果。建议新任务首次开启检查模板正确性。', 'Renders one preview before training starts to validate prompts early. Useful on first runs.'],
  sample_prompts: ['预览提示词列表（每行一条，支持参数后缀）。建议覆盖典型场景+触发词组合各写一条。', 'Preview prompt list (one per line with optional suffix params). Cover typical scenes and trigger combos.'],
  sample_negative: ['预览用负向提示词。建议放通用质量词即可，与最终使用场景保持一致。', 'Negative prompt for previews; keep generic quality terms consistent with your target usage.'],
  sample_cfg: ['预览 CFG 强度。推荐范围：7（默认）附近；LCM 类 1–2。', 'Preview CFG scale. Recommended: ~7 normally; 1-2 for LCM-style models.'],
  sample_steps: ['预览采样步数。推荐范围：24（默认）附近；仅影响预览速度与质量。', 'Preview sampling steps. Recommended: ~24; affects preview speed/quality only.'],
  sample_sampler: ['预览采样器（canonical 命名，旧名为运行时别名）。建议 euler_a 快速看趋势，karras 系看细节。', 'Preview sampler (canonical names; legacy names alias at runtime). euler_a for quick trends, karras variants for detail.'],
  sample_scheduler: ['预览调度器选择。建议留空跟随模型默认。', 'Preview scheduler; empty follows the model default.'],
  sample_seed: ['预览随机种子：固定可横向对比不同 step 的效果。建议固定一个值；0 每次随机。', 'Preview seed; fixing it makes cross-step comparisons fair. 0 randomizes each time.'],
  sample_width: ['预览图宽度（px，64 倍数）。建议与训练分辨率一致或减半提速。', 'Preview width in px (multiple of 64); match training resolution or halve for speed.'],
  sample_height: ['预览图高度。建议与宽度同规则。', 'Preview height in px; same guidance as width.'],
  sample_batch_size: ['每次预览并排出图数量。建议 1–4，过大拖慢训练。', 'Images per preview pass. Recommended: 1-4.'],
  preview_device: ['预览推理设备：gpu 快但占显存；cpu 不占显存慢。建议 gpu（默认），低显存档案自动处理。', 'Device for preview inference: gpu fast, cpu VRAM-free but slow. Keep gpu unless the profile says otherwise.'],
  ephemeral_preview_pipeline: ['每次预览后销毁 pipeline 释放缓存，避免 VAE 常驻占显存。建议低显存环境开启（默认 true）。', 'Destroys the preview pipeline after each render so VAE memory returns. Keep on in tight-VRAM setups (default).'],
  spd_enabled: ['SPD 多分辨率预览采样：只影响预览/推理 sampler，不进训练 loss。建议默认关闭。', 'SPD multi-resolution preview sampling touches only the sampler path, never training loss. Off by default.'],
  spd_resize_mode: ['SPD latent 多分辨率插值方式。建议 bilinear 默认。', 'Latent interpolation mode for SPD. bilinear default is fine.'],
  quality_evaluation_enabled: ['训练结束后跑 FID/CLIP Score 等指标评估。建议重要批次开启做横向比较。', 'Runs FID/CLIP-score style metrics after training for batch-to-batch comparison.'],
  quality_evaluation_metrics: ['评估指标集合选择（FID/CLIP 等）。建议 FID+CLIP 双指标互补。', 'Which metrics to compute (FID/CLIP...). Pair FID with CLIP score for complementary signals.'],
  quality_evaluation_num_samples: ['评估生成样本数。推荐范围：10–64；越多越稳越慢。', 'Samples generated for evaluation. Recommended: 10-64.'],
  quality_evaluation_compare_base: ['用 LoRA 权重 0 与 1 的成对样本生成增量证据。建议开启以区分底模贡献。', 'Generates paired samples at LoRA weight 0 vs 1 to isolate adapter contribution. Keep on.'],
  quality_evaluation_validation_prompts: ['评估用验证提示词集。建议覆盖核心概念+易翻车场景。', 'Validation prompts for evaluation; cover core concepts and known failure modes.'],
  quality_evaluation_validation_seeds: ['评估种子列表，保证可比性。建议固定一组种子复用。', 'Seeds for evaluation runs to keep results comparable. Reuse a fixed set.'],
  quality_evaluation_xy_grid: ['生成 XY 网格图（如权重×种子矩阵）直观对比。建议调参阶段开启。', 'Builds XY grids (e.g. weight x seed matrices) for visual comparison during tuning.'],
  quality_evaluation_metric_weights: ['多指标合成总分时的权重表。建议留空等权，有明确偏好再调。', 'Weights for combining metrics into one score. Equal weights are fine until you have a preference.'],
  quality_evaluation_suite_id: ['评估套件 ID（预设的指标/提示词组合）。建议先用默认套件。', 'Evaluation suite preset id. Start with the default suite.'],
  fid_real_image_dir: ['FID 计算用的真实参考图目录。建议与训练数据分布一致的独立目录。', 'Real-reference folder for FID; use an independent set matching the training distribution.'],

  // ── 蒸馏 / 少步 ──
  real_objective: ['真实短测目标选择：lcm_consistency_prob 用 teacher 生成对齐目标。建议按实验目的选择，默认即可。', 'Objective for true smoke runs (lcm_consistency_prob aligns against teacher targets). Default suits most probes.'],
  lcm_target_stride: ['teacher 一致性跨度 t→t-stride。推荐范围：80（默认）附近。', 'Teacher consistency stride t -> t-stride. Recommended: ~80.'],
  student_scheduler: ['Student 少步采样器。建议 lcm（默认）。', 'Few-step sampler for the student. lcm recommended.'],
  student_steps: ['目标 few-step 步数。推荐范围：4（默认）；1–8 内越少越难对齐。', 'Target few-step count. Recommended: 4; lower is harder to align.'],
  teacher_scheduler: ['Teacher 采样器。建议 dpmpp_2m_karras（默认）高质量。', 'Teacher sampler; dpmpp_2m_karras gives strong targets.'],
  teacher_steps: ['Teacher 推理步数。推荐范围：30（默认）；越大越准越贵。', 'Teacher sampling steps. Recommended: ~30; higher costs more.'],
  teacher_lora_scope: ['Teacher LoRA 加载范围：unet_only 默认。建议保持默认避免 TE 干扰蒸馏目标。', 'Which parts load teacher LoRA weights; unet_only avoids polluting targets via TE.'],
  steps: ['真实蒸馏总步数。推荐范围：与常规 LoRA 同量级（1000 起）再调。', 'Total distillation steps; start at ordinary LoRA scale then tune.'],
  distillation_enabled: ['少步 student 对齐多步 teacher 的蒸馏路线（DP-DMD/AnyFlow）。显著更慢更吃显存，不是加速开关。建议仅在明确要少步产物时开启。', 'Distills a few-step student from a many-step teacher (DP-DMD/AnyFlow): much slower and heavier — not an accelerator. Only for few-step artifacts.'],
  distillation_mode: ['蒸馏模式：dp_dmd_turbo 主少步路径；anyflow flow-matching 一致性蒸馏（非加速开关）。建议 dp_dmd_turbo。', 'dp_dmd_turbo is the main few-step path; anyflow is flow-matching consistency distillation. Prefer dp_dmd_turbo.'],
  distillation_objective: ['与 mode 配对的 objective 记录标识，请与蒸馏模式保持一致。建议不动。', 'Objective label paired with mode; keep them consistent. Leave as-is.'],
  distillation_prediction_type: ['student/teacher 对齐的预测目标类型。建议 velocity 与底模一致。', 'Prediction target both sides align on; match your base model (velocity common).'],
  distillation_guidance_scale: ['teacher 目标 bake 的 CFG 强度；≠1 即启用 bake（DP-DMD 家族判定）。建议 1 保持默认。', 'CFG used when baking teacher targets (non-acceleration). DP-DMD treats non-1 as bake-on. Keep 1.'],
  distillation_student_steps: ['student ODE 步数（常见 1–8）。越少越「少步」也越难对齐。建议 4 起步。', 'Student ODE steps (commonly 1-8). Fewer steps are harder to align. Start at 4.'],
  distillation_teacher_steps: ['teacher ODE 步数（≥ student）。越大越慢越贵。建议 28（默认）附近。', 'Teacher ODE steps (>= student). Recommended: ~28.'],
  dp_dmd_variant: ['DP-DMD 实现分支：lulynx_optimized 历史 teacher-regression；standard 需要真实双 score provider（缺失即 fail-fast）。建议 lulynx_optimized。', 'DP-DMD variant: lulynx_optimized regression path vs standard requiring a dual score provider (fails fast if absent). Prefer lulynx_optimized.'],
  anyflow_student_steps: ['AnyFlow 专用 student 步数，覆盖通用值。建议 4。', 'AnyFlow-specific student steps overriding the generic field. Use 4.'],
  anyflow_teacher_steps: ['AnyFlow 专用 teacher 步数。建议 28 附近。', 'AnyFlow-specific teacher steps. Around 28.'],
  anyflow_cfg_bake: ['AnyFlow 专用 CFG bake 开关。建议实验对照时再开。', 'AnyFlow-specific CFG bake toggle. For controlled comparisons.'],
  anyflow_x0_endpoint_weight: ['x0-endpoint 匹配权重；0 关闭，不用于加速。建议 0。', 'Weight of x0 endpoint matching; 0 off. Not an accelerator. Keep 0.'],
  distillation_diversity_anchor_weight: ['多样性锚损失权重防模式坍缩；0 关闭。建议 0 起步，坍缩迹象再加 0.01 级。', 'Anti-collapse diversity anchor weight; start 0, add ~0.01 if modes collapse.'],
  distillation_fake_critic_weight: ['fake critic 对抗项权重；0 关闭。建议 0 保持稳定。', 'Adversarial fake-critic weight; 0 keeps training stable.'],
  distillation_fake_critic_margin: ['fake critic 的 margin 间隔。建议 0.05（默认）。', 'Margin for the fake critic term. Keep 0.05.'],
  distillation_softrank_weight: ['SoftRank 排序正则权重；0 关闭。建议 0 起步。', 'SoftRank regularization weight; start at 0.'],
  distillation_softrank_k: ['SoftRank top-k 数量。建议 4（默认）。', 'Top-k size for SoftRank. Keep 4.'],
  distillation_softrank_pool_size: ['SoftRank 采样池大小。建议 128（默认）。', 'Sampling pool size for SoftRank. Keep 128.'],
  distillation_softrank_softness: ['排序软化系数。建议 0.25（默认）。', 'Softness coefficient for ranking. Keep 0.25.'],
  distillation_softrank_every_n: ['每 N 步计算一次 SoftRank。建议 1。', 'Compute SoftRank every N steps. Keep 1.'],
  distillation_softrank_warmup_ratio: ['前该比例步数不做 SoftRank。建议 0。', 'Skip SoftRank for this initial fraction of steps. Keep 0.'],

  // ── TurboLoRA / TwinFlow 实验包 ──
  turbo_lora_enabled: ['TurboLoRA Phase-1 草稿契约：仅初始化草稿网络与 teacher packet，主蒸馏/加速尚未接线。建议仅实验观察日志用。', 'TurboLoRA Phase-1 draft contract: initializes the draft net and teacher packet only; full distillation/acceleration is not wired yet. Experimental observation only.'],
  turbo_lora_draft_num_layers: ['草稿 DiT 层数（默认 8）。越小越快。建议 8。', 'Draft DiT depth (default 8); smaller is faster. Keep 8.'],
  turbo_lora_draft_hidden_dim: ['草稿网络隐宽（默认 512 ≈ 目标 1/2）。建议 512。', 'Draft hidden width (~half of target by default). Keep 512.'],
  turbo_lora_draft_steps: ['每次投机的草稿步数。推荐范围：3–5。', 'Speculative draft steps per cycle. Recommended: 3-5.'],
  turbo_lora_acceptance_threshold_low: ['低噪声端马氏距离接受阈值，越小越严。建议 0.02。', 'Acceptance threshold at the low-noise end; smaller is stricter. Keep 0.02.'],
  turbo_lora_acceptance_threshold_high: ['高噪声端接受阈值，越大越宽松。建议 0.5。', 'Acceptance threshold at the high-noise end; larger is looser. Keep 0.5.'],
  turbo_lora_distill_cosine_weight: ['蒸馏余弦方向项权重（0=纯 MSE）。建议 0.1。', 'Cosine-direction term weight in distillation (0 = pure MSE). Keep 0.1.'],
  turbo_lora_distill_trajectory_ratio: ['沿 ODE 轨迹后半程采样的比例。建议 0.5。', 'Fraction sampled along the late ODE trajectory. Keep 0.5.'],
  twinflow_weight: ['TwinFlow 辅助损失总闸：>0 才生效（可试 0.5–1.0）。建议实验路径专用。', 'TwinFlow aux-loss master gate; effective above 0 (try 0.5-1.0). Experimental paths only.'],
  twinflow_target_step_count: ['目标少步数（1–4 叙事元数据，不替换产品采样器）。建议 2。', 'Narrative few-step metadata (does not swap the product sampler). Keep 2.'],
  twinflow_estimate_order: ['RCGM 估计阶；≥2 多一次 teacher 前向。建议 2（默认）。', 'RCGM estimation order; >=2 adds a teacher forward. Keep 2.'],
  twinflow_delta_t: ['递归一致性时间步长 Δt。建议 0.01（默认）。', 'Recursive-consistency timestep delta. Keep 0.01.'],
  twinflow_target_clamp: ['RCGM 目标绝对值 clamp；0 不夹。建议 1。', 'Absolute clamp on RCGM targets; 0 disables clamping. Keep 1.'],
  twinflow_enhanced_ratio: ['CFG 精炼比：MVP 默认 0=关省前向。建议 0。', 'CFG-refine ratio; MVP default 0 skips extra forwards. Keep 0.'],
  twinflow_adversarial_enabled: ['自对抗分支（EMA 一步 fake + L_adv + rectify）：明显更慢更吃前向，无外挂判别器。建议默认关闭。', 'Self-adversarial branch (one-step EMA fake, L_adv, rectify): notably slower, no external discriminator. Off by default.'],
  twinflow_adversarial_weight: ['L_adv 权重：需对抗开且 >0 才进 loss。建议 0 起步。', 'L_adv weight; needs the branch on and >0 to enter loss. Start 0.'],
  twinflow_rectify_weight: ['L_rectify 对齐权重（real detach）。建议 0 起步。', 'Rectify alignment weight (real side detached). Start 0.'],
};
