// SPDX-License-Identifier: LicenseRef-PolyFormNoncommercial-1.0.0
// desc 文案表 —— 显存与速度：梯度检查点、BlockSwap、offload、压缩、缓存释放、编译加速。
// 推荐范围依据：schemaCommon/各家族审计注释（行号证据）、backend configs_performance.py 默认值、wiki 加速条目。
export default {
  // ── 通用显存 ──
  gradient_checkpointing: ['反传时重算激活以省显存（约换 20–30% 速度）。建议除显存富余外保持开启（默认 true）。', 'Recomputes activations in backward to save VRAM at ~20-30% speed cost. Keep on (default) unless VRAM is plentiful.'],
  cpu_offload_checkpointing: ['梯度检查点时把部分张量卸载到 CPU，进一步省显存但更慢。建议极端显存场景才开。', 'Offloads checkpoint tensors to CPU for extra savings at a larger speed cost. Extreme-VRAM cases only.'],
  cpu_offload_checkpointing_mode: ['检查点与 CPU offload 的结合模式：auto 自动判定，full 完整卸载。建议 none 起步，OOM 时 auto。', 'How checkpointing combines with CPU offload: auto decides, full offloads everything. Start none; switch to auto under OOM.'],
  cpu_offload_checkpointing_pool_gb: ['CPU 端检查点内存池大小（GB）。推荐范围：4–16，按物理内存的 1/4 内设置。', 'CPU-side pinned pool for checkpoints in GB. Recommended: 4-16 within a quarter of physical RAM.'],
  enable_sequential_cpu_offload: ['把模型组件逐层顺序卸载到 CPU、用时加载。极省显存但显著变慢。建议仅在无法其他优化时兜底使用。', 'Layer-by-layer sequential CPU offload with on-demand load: minimal VRAM, big slowdown. Last-resort option.'],
  vae_slicing: ['VAE 编码/解码用切片降低峰值显存。建议大分辨率且 VAE 阶段 OOM 时开启。', 'Slices VAE encode/decode to cut peak VRAM. Enable when the VAE stage OOMs at high resolution.'],
  vae_tiling: ['VAE 分块处理超大图像。建议分辨率超过 VAE 设计尺寸（如 SDXL>2048）时开启。', 'Tiles the VAE for very large images. Enable beyond the VAE design size (e.g. >2048 on SDXL).'],
  no_half_vae: ['强制 VAE 用 FP32，修复某些 VAE 半精度发灰/NaN。建议出图异常时开启排查。', 'Forces FP32 VAE to fix gray/NaN outputs from some half-precision VAEs. Try when previews look washed out.'],
  vae_chunk_size: ['VAE 解码分块大小，越小越省显存。推荐范围：2（默认）附近。', 'VAE decode chunk size; smaller saves more VRAM. Recommended: ~2.'],
  lowram: ['低内存模式：权重直接装进显存避免系统内存镜像。建议小内存机器开，配合 mmap 禁用。', 'Low-RAM mode loads weights straight onto GPU without a host mirror. For RAM-constrained machines, pair with disabling mmap.'],
  disable_mmap_load_safetensors: ['禁用 safetensors mmap 加载（改常规读入）。mmap 与低内存模式冲突时开启。', 'Disable mmap loading of safetensors in favor of plain reads. Use when mmap conflicts with low-RAM mode.'],
  pytorch_cuda_expandable_segments: ['训练前设置 PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True 减少碎片 OOM。建议保持开启（默认 true）。', 'Sets expandable_segments allocator config before training to reduce fragmentation OOM. Keep on (default).'],
  memory_reclaim_interval_steps: ['每 N 个优化步做一次 gc+empty_cache 回收碎片。推荐范围：0 关闭；频繁 OOM 给 50–200，过密拖慢训练。', 'Periodic gc+empty_cache every N steps against fragmentation. Recommended: 50-200 only when needed; 0 off.'],
  cuda_cache_release_strategy: ['CUDA 缓存释放策略：oom_only 仅在 OOM 恢复时释放（推荐）；aggressive 每步释放拖慢训练；off 关闭。', 'Cache-release policy: oom_only releases after OOM recovery (recommended); aggressive hurts throughput.'],
  cuda_cache_release_interval: ['允许一次缓存释放的最小间隔（优化 step 数）。推荐范围：1（默认）；调大减少抖动。', 'Minimum steps between cache releases. Recommended: 1; raise to reduce jitter.'],
  oom_skip_batch_enabled: ['自动跳过触发 OOM 的 batch 继续训练。建议长训无人值守开启（默认 true）。', 'Skips batches that trigger OOM so unattended runs survive. Keep on (default).'],
  oom_skip_batch_max_consecutive: ['连续 OOM 达到该次数即停止训练防死循环。推荐范围：3（默认）。', 'Stops the run after this many consecutive OOM skips. Recommended: 3.'],

  // ── 权重压缩 / 激活压缩 ──
  fp8_base: [{ zh: '以 FP8 加载冻结基座省一半底模显存。旧入口：新配置建议改用「权重压缩预设」。推荐范围：24G 下训 SDXL 大 rank 或 Anima 时开启。', en: 'Loads the frozen base in FP8 to halve base-model VRAM (legacy entry; prefer the weight-compression preset). Recommended for large-rank SDXL or Anima on 24 GB.' }],
  fp8_base_unet: ['仅对 U-Net/DiT 用 FP8（TE 保持高精度）。建议文本绑定重要时选此项而非全模型 FP8。', 'FP8 for U-Net/DiT only, keeping TE high precision. Prefer over full-FP8 when text binding matters.'],
  weight_compression_enabled: ['手动启用权重压缩（不走预设时的高级入口）。建议直接选上方预设即可，此项留给精确控制场景。', 'Manual entry for weight compression bypassing presets; use the preset row instead unless fine-tuning knobs.'],
  weight_compression_format: ['压缩格式：fp8_e4m3 原生稳定路径（推荐）；torchao/quanto 需要对应运行库支持。', 'Compression format: fp8_e4m3 is the stable native path; torchao/quanto need their runtimes installed.'],
  weight_compression_target: ['压缩目标范围：backbone 仅主干 / text_encoder 仅 TE / both 全部。建议 backbone 优先保 TE 精度。', 'What gets compressed: backbone, text_encoder, or both. Compress backbone first to protect TE precision.'],
  weight_compression_preset: ['一键压缩预设（自动挑格式/目标/校验）。建议不确定时从预设起步再手动细化。', 'One-click compression preset picking format/target/verify automatically. Start here before manual tuning.'],
  weight_compression_verify: ['压缩后做数值校验（重建误差抽查）。建议首次对某底模启用压缩时开启。', 'Numeric spot-checks after compression (reconstruction error). Enable the first time you compress a given base.'],
  activation_compression_enabled: ['压缩激活张量降低反传显存（fp16/bf16 无损级，fp8 有损）。建议显存临界时先开 bf16 档。', 'Compresses activations during backward (fp16/bf16 near-lossless, fp8 lossy). Start with bf16 when VRAM is marginal.'],
  activation_compression_dtype: ['激活压缩精度：fp16/bf16 较稳；fp8_e4m3 显存减半但有损。建议 bf16 起步。', 'Activation compression dtype: fp16/bf16 safe; fp8_e4m3 halves further but lossy. Start with bf16.'],
  activation_compression_min_tensor_mb: ['只压缩达到该体积（MB）的激活张量，小张量不值得压。推荐范围：1（默认）。', 'Only tensors above this MB get compressed; smaller ones are not worth it. Recommended: 1.'],
  activation_cpu_offload_enabled: ['把大激活搬到 CPU 内存降显存，可与分块检查点组合。建议显存仍不够时的下一档手段。', 'Moves large activations to host RAM; combinable with chunked checkpointing as the next VRAM lever.'],
  activation_cpu_offload_min_tensor_mb: ['只卸载达到该体积的激活张量。推荐范围：1 MB（默认）以上。', 'Offload threshold in MB for activations. Recommended: >=1 MB.'],
  activation_cpu_offload_pool_gb: ['CPU pinned 内存池大小（GB），池内传输走 DMA 更快。推荐范围：1–8。', 'Pinned host pool in GB for faster DMA transfers. Recommended: 1-8.'],
  activation_memory_budget: ['激活显存预算（MB），超出触发压缩/卸载联动。建议留空自动；手动给值需实测基线。', 'Activation VRAM budget in MB triggering compression/offload. Leave empty for automatic; manual values need measured baselines.'],
  quantization_type: ['底模量化后端类型（qlora_nf4 等 QLoRA 家族）。建议 nf4 质量/速度最均衡。', 'Base quantization backend for QLoRA-style loading. nf4 balances quality and speed best.'],
  bnb_4bit_quant_type: ['bitsandbytes 4bit 量化类型：nf4 信息论最优（推荐）；fp4 兼容旧卡。', 'bnb 4-bit type: nf4 is informationally optimal; fp4 for older GPUs.'],
  bnb_4bit_use_double_quant: ['二次量化压缩量化常数本身，再省约 0.4 bit/参数。建议保持开启（默认 true）。', 'Double quantization also compresses quantile constants (~0.4 bits/param saved). Keep on (default).'],
  bnb_4bit_compute_dtype: ['bnb 计算精度：bfloat16 推荐；float16 旧卡。', 'Compute dtype for bnb layers: bfloat16 recommended, float16 for older cards.'],
  bnb_4bit_quant_storage: ['量化权重的存储 dtype。建议 uint8（默认）。', 'Storage dtype for quantized weights. Keep uint8.'],
  quantization_enabled: ['对底模启用量化加载（QLoRA 等），大幅降底模显存。建议显存不足以半精度装载时开启。', 'Quantized base loading (QLoRA family) for major base-VRAM savings when half precision still will not fit.'],
  quantization_legacy_target_tables: ['沿用覆盖率修正前的旧量化目标表，仅为复现旧产物。建议新训练保持关闭。', 'Pre-fix legacy quant target tables for reproducing old artifacts only. Keep off for new runs.'],
  quantization_offload_optimizer_states: ['量化训练时把优化器状态也卸到 CPU。建议显存极限时开，略慢。', 'Also pages optimizer states to CPU in quantized training. Slower but helps at the extreme.'],

  // ── Block Swap / 显存交换 ──
  swap_granularity: ['显存交换模式总开关：选择按 block 还是 layer 粒度把冻结权重在 CPU/GPU 间搬运。建议显存不足先试 block 粒度档位。', 'Master switch for weight swapping between CPU and GPU by block or layer granularity. Try block-level first under VRAM pressure.'],
  swap_ratio: ['按 block 总数比例决定交换多少（0–1）。推荐范围：0.3–0.5 起步试探，配合水线自动调节。', 'Fraction of blocks swapped (0-1). Probe from 0.3-0.5 alongside the watermark control.'],
  swap_count: ['绝对交换数量，大于 0 时优先于比例。建议 0 用比例控制，精确控卡时才给具体数。', 'Absolute swapped-block count overriding ratio when >0. Prefer ratio; set exact counts only for precise control.'],
  blocks_to_swap: ['将 N 个 U-Net/DiT block 卸载到 CPU（0=关闭）。推荐范围：DiT 28–48 层模型从 8–16 起步，每加一档省约一层显存换一点速度。', 'Number of U-Net/DiT blocks kept on CPU (0=off). Recommended: start 8-16 on 28-48 block DiTs; each extra block trades speed for VRAM.'],
  block_swap_strategy: ['BlockSwap 搬运策略：auto 由后端按家族解析最优路径。建议保持 auto。', 'Swap transport strategy; auto resolves the best path per family. Keep auto.'],
  block_merge_size: ['merged_block 模式下每组包含的相邻 block 数（不跨组边界）。推荐范围：2（默认）。', 'Blocks per merged group in merged_block mode. Recommended: 2.'],
  sdxl_block_swap_enabled: ['SDXL U-Net block swap 兜底开关：显存不足时把部分 U-Net block 移到 CPU。建议低显存档案已覆盖时无需手开。', 'Fallback toggle moving some SDXL U-Net blocks to CPU under VRAM pressure. Usually covered by the low-VRAM profile.'],
  sdxl_block_swap_output_blocks: ['交换 U-Net output blocks（推荐第一步尝试，收益/速度比最好）。建议保持 true。', 'Swaps output blocks first: best benefit/speed trade. Keep true.'],
  sdxl_block_swap_middle_block: ['交换 middle block（推荐第二步尝试）。建议保持 true。', 'Swaps the middle block next. Keep true.'],
  sdxl_block_swap_input_blocks: ['交换 input blocks（最后再尝试，收益低速度损失大）。建议默认 false。', 'Input blocks last: low benefit, high slowdown. Keep false by default.'],
  sdxl_block_swap_offload_after_backward: ['反向传播结束后立即卸载已交换 block：更省显存但更慢。建议显存极限才关。', 'Offload swapped blocks right after backward: saves more VRAM, runs slower. Keep on except at the extreme.'],
  sdxl_block_swap_vram_threshold: ['block swap 的软显存水线（%）：低于该占用提前回收。推荐范围：70（默认）附近；0 尽快卸载。', 'Soft VRAM watermark (%) for swap decisions. Recommended: ~70; 0 offloads eagerly.'],
  vram_swap_to_ram: ['让原生 LoRA/LoRA-FA/T-LoRA/VeRA 的可训权重驻留内存按需上卡。建议优化器状态爆显存时试验。', 'Keeps trainable weights of native variants in host RAM, uploading on demand. Try when optimizer state blows past VRAM.'],
  newbie_auto_swap_release: ['显存持续偏低时逐步减少 blocks_to_swap 回收训练速度。建议开启让长训自适应提速。', 'Gradually reduces swap count when VRAM stays low, buying back speed. Enable for long adaptive runs.'],
  newbie_block_residency: ['Newbie 冻结 DiT 权重驻留策略（常驻/block_cpu_pinned 等）。建议默认 block_cpu_pinned 平衡显存与速度。', 'Residency policy for frozen Newbie DiT weights. block_cpu_pinned balances VRAM and speed well.'],
  newbie_block_residency_min_params: ['只托管参数量达到阈值的冻结 Linear，过滤小模块减少搬运开销。推荐范围：0 默认全托管。', 'Only offload frozen Linears above this param count to cut transfer overhead. Keep 0 to include all.'],
  anima_block_residency_min_params: ['Anima 只托管达到该参数量的冻结 Linear，0 不过滤。建议 0。', 'Same threshold for Anima frozen Linears; 0 keeps all eligible. Keep 0.'],
  lulynx_weight_residency: ['SDXL 冻结底座的层级驻留策略。resident 全常驻最快；非 resident 省 VRAM 换 IO。建议显存充足保持 resident。', 'Layer residency for the frozen SDXL base: resident is fastest, others trade IO for VRAM. Keep resident when it fits.'],
  lulynx_weight_residency_min_params: ['只托管参数量达标的 Linear/Conv2d。推荐范围：0 默认。', 'Param-count floor for managed layers. Keep 0.'],
  lulynx_precision_swap_enabled: ['Lulynx 精准交换规划兼容层：按层调度换入换出。建议与其他交换方案二选一，勿叠加。', 'Precision swap planner layer; pick one swap scheme, do not stack them.'],
  lulynx_precision_swap_strategy: ['精准交换的策略名。建议保持默认 standard。', 'Strategy name for precision swap. Keep standard.'],
  sparse_swap_enabled: ['稀疏交换：只搬大张量的冷分块而非整层。建议整层交换粒度过粗时开启。', 'Sparse swap moves cold chunks of big tensors instead of whole layers. Use when layer-granularity is too coarse.'],
  sparse_swap_budget_mb: ['稀疏交换的显存预算（MB）。推荐范围：256–1024 按空闲显存设定。', 'VRAM budget for sparse swap in MB. Recommended: 256-1024 per free headroom.'],
  streaming_block_mode: ['流式 offload 模式：前向中即时换入换出。比驻留式更省但更慢，显存极限时选用。', 'Streaming mode swaps weights mid-forward: leaner but slower. For extreme cases.'],

  // ── DiT 分块检查点/预取（各家族） ──
  anima_block_checkpointing: ['Anima 梯度检查点主力：反传时按 DiT block 重算激活，比通用梯度检查点更省显存。建议显存不足优先开这个而不是通用项。', 'Primary Anima checkpointing: recomputes per-DiT-block in backward, saving more than generic checkpointing. Prefer over the generic knob.'],
  anima_block_checkpointing_interval: ['每隔几个 DiT block 设一个检查点：1 最省显存（每块都重算）；2 显存翻倍换约 13% 提速。推荐范围：16G 以下 1；16G+ 可试 2。', 'Checkpoint density across DiT blocks: 1 recomputes everything (leanest); 2 doubles activation VRAM for ~13% speedup. Use 1 below 16 GB, try 2 above.'],
  newbie_block_checkpointing: ['Newbie 的梯度检查点主力：反传按 DiT block 重算激活降峰值。比通用检查点更省，显存不足优先开。', 'Primary Newbie checkpointing: per-block recompute beats generic checkpointing on VRAM. Prefer it first.'],
  newbie_block_checkpointing_interval: ['每隔 N 个 DiT block 设一个检查点（1=全部重算）。N>1 少重算多占激活显存。推荐范围：1（默认）。', 'Checkpoint every N DiT blocks (1 = all). Larger N recomputes less but holds more activations. Recommended: 1.'],
  newbie_block_checkpointing_mode: ['检查点模式：block 整块重算（推荐）；selective 与 Anima 对齐的可选实现。', 'Checkpointing style: full block recompute (recommended) or selective aligned with Anima.'],
  anima_block_prefetch: ['Anima Block 预取：异步预载后续 block 掩盖换入延迟。建议开了 offload 后配套开启。', 'Asynchronously prefetches upcoming Anima blocks to hide swap latency. Pair with any offload scheme.'],
  anima_block_prefetch_depth: ['向前预取的 block 数。推荐范围：1–2；过大占显存。', 'Blocks to prefetch ahead. Recommended: 1-2; more costs VRAM.'],
  anima_block_prefetch_mode: ['预取模式：original 固定深度（默认）；adaptive 自适应。建议 original 起步。', 'Prefetch style: fixed-depth original or adaptive. Start original.'],
  newbie_block_prefetch: ['Newbie Block 预取开关，配合 offload 掩盖延迟。建议与 offload 同开。', 'Newbie prefetch toggle to hide swap latency alongside offload.'],
  newbie_block_prefetch_depth: ['向前预取几个 block。推荐范围：1–2。', 'Prefetch depth in blocks. Recommended: 1-2.'],
  newbie_block_prefetch_mode: ['预取模式：original 固定深度（默认）；adaptive 自适应深度。建议 original。', 'Fixed-depth vs adaptive prefetch. Keep original.'],
  anima_block_offload_enabled: ['Anima Block LRU Offload：GPU 上保留 N 个槽位滚动换入换出冻结块。建议显存不足且不想重算时用（与检查点互补）。', 'LRU-offload keeps N Anima blocks resident and rotates the rest: complements checkpointing when VRAM-bound without recompute.'],
  anima_block_offload_gpu_slots: ['同时保留在 GPU 的 block 数（当前+前后窗口）。推荐范围：3（默认）起，每减 1 槽省一块显存。', 'Resident block slots on GPU (current + window). Recommended: 3; fewer slots save more VRAM.'],
  anima_block_offload_prefetch_depth: ['前向/反向各异步预取 N 个 block。推荐范围：1（默认）。', 'Async prefetch depth per phase. Recommended: 1.'],
  ltx23_block_offload_ratio: ['参与 offload 的 block 比例（0-100%）。推荐范围：100 全部托管或 0 关闭，部分值意义有限。', 'Share of blocks participating in offload (0-100%). Use 100 or 0; partial values rarely help.'],
  ltx23_block_offload_gpu_slots: ['GPU 上保留的槽位数，显存越紧给越小。推荐范围：22B 建议 2；显存富余可加到 3–4。', 'Resident slots on GPU (2 suggested for 22B); shrink as VRAM tightens.'],
  ltx23_block_offload_pin_memory: ['CPU 侧 pinned 缓存加速 H2D 拷贝。建议内存充足保持 true。', 'Pinned host staging speeds H2D copies. Keep true with enough RAM.'],
  ltx23_block_offload_prefetch_depth: ['异步预取后续 block 数量。推荐范围：1（默认）。', 'Async prefetch depth for later blocks. Recommended: 1.'],
  ltx23_block_offload_min_param_mb: ['小于该参数量（MB）的 block 不 offload，避免小包传输开销。推荐范围：50。', 'Skip offloading blocks below this size (MB) to avoid tiny-transfer overhead. Recommended: 50.'],

  // ── 低显存档案 ──
  sdxl_low_vram_optimization: ['一键低显存优化（≤6GB）：组合 block swap/CPU 驻留/降频预览等。建议 6–8G 卡开启。', 'One-click <=6GB bundle combining swaps, CPU residency, throttled preview. For 6-8 GB cards.'],
  sdxl_low_vram_fixed_block_swap: ['启用 U-Net block swap（低显存档案组件）。建议保持开启（档案默认 true）。', 'U-Net block swap inside the low-VRAM profile. Keep on (profile default).'],
  sdxl_low_vram_component_cpu_residency: ['VAE/TE 只在上卡需要时临时进驻。建议保持开启（档案默认 true）。', 'VAE/TE visit GPU only when needed. Keep on (profile default).'],
  sdxl_low_vram_swap_middle_block: ['交换 middle block：通常比较划算。建议保持 true。', 'Middle-block swap is usually worthwhile. Keep true.'],
  sdxl_low_vram_swap_input_blocks: ['交换 input blocks：显存收益较大但更慢。建议仅仍 OOM 再开。', 'Input-block swap adds savings with real slowdown. Only if still OOM.'],
  sdxl_low_vram_swap_offload_after_backward: ['反向后立即把已交换 block 移回 CPU。更省显存更慢。建议保持 true。', 'Move swapped blocks back right after backward: leaner, slower. Keep true.'],
  sdxl_low_vram_swap_vram_threshold: ['软显存水线 %：0 表示始终尽快卸载。建议 0（档案默认）。', 'Soft VRAM watermark; 0 offloads eagerly (profile default).'],
  sdxl_low_vram_bucket_reso_steps: ['低显存模式桶步长。推荐范围：32。', 'Bucket granularity in low-VRAM mode. Recommended: 32.'],
  sdxl_low_vram_preview_policy: ['低显存下预览频率策略（every_4_epochs 等）。建议保持默认节流档。', 'Preview cadence under low VRAM. Keep the default throttle.'],
  sdxl_low_vram_auto_protection: ['预览 OOM 先降频再自动关闭预览。建议保持开启。', 'On preview OOM: throttle first, then disable preview automatically. Keep on.'],
  sdxl_low_vram_auto_resolution_probe: ['启动前自动预跑探测显存并必要时下调分辨率。建议保持开启。', 'Probes VRAM before launch and steps resolution down if needed. Keep on.'],
  sdxl_low_vram_resolution_mode: ['低显存分辨率模式（是否允许下调基准）。建议 auto。', 'Whether/how resolution may be reduced under low VRAM. Keep auto.'],
  sdxl_low_vram_preview_device: ['预览出图设备。建议 gpu（快）；显存极限选 cpu。', 'Device used for preview sampling. gpu is fast; cpu frees VRAM at the extreme.',
  ],
  dit_low_vram_profile: ['DiT 低显存档案：映射到既有 block residency/module_offload 组合，不是第三套 offload。建议 off 起步，不足再选档。', 'DiT low-VRAM profiles mapping onto existing residency/offload combos (not a third system). Start off; pick a level when needed.'],
  training_vram_profile: ['向提交端声明目标显存档位；是否兑现由后端按家族与实测证据决定，不代表承诺。建议保守选择实际显存档。', 'Declares a target VRAM tier to the submit pipeline; honored per family based on evidence. Pick your actual tier conservatively.'],
  flux_transformer_offload: ['Flux Transformer 卸载档位：off 常驻最快；auto 按显存自选；aggressive 流式卸载最省最慢。建议 auto。', 'Flux transformer offload level: off fastest, auto picks per VRAM, aggressive streams (slowest). Keep auto.'],
  peak_vram_control_enabled: ['显存峰值控制总开关：micro-batch 拆分/启动保护等子项的父开关。建议 OOM 驱动场景才开。', 'Parent switch for peak-VRAM controls (micro-batching, startup guard). Enable for OOM-driven scenarios.'],
  peak_vram_micro_batch_enabled: ['把 batch 拆成多个 micro-batch 执行降峰值。建议 batch>1 且 OOM 时开启。', 'Splits the batch into micro-batches to cut peaks. Useful when batch >1 OOMs.'],
  peak_vram_micro_batch_size: ['每个 micro-batch 的大小。推荐范围：1–2，越小越省越慢。', 'Samples per micro-batch. Recommended: 1-2; smaller leans harder.'],
  peak_vram_target_effective_batch: ['目标等效 batch（供拆分器参考）；0 自动。建议 0。', 'Target effective batch guiding the splitter; 0 auto. Keep 0.'],
  peak_vram_startup_guard_enabled: ['启动阶段峰值保护（首个优化循环前最易 OOM）。建议大模型首训开启观察。', 'Guards the startup window where first-step peaks OOM most often. Enable when trialing big models.'],
  peak_vram_startup_guard_mode: ['保护强度：auto 自动估计档位。建议 auto。', 'Guard intensity; auto estimates the level. Keep auto.'],
  peak_vram_startup_guard_steps: ['保护持续的优化步数。推荐范围：24（默认）附近。', 'Steps the startup guard stays active. Recommended: ~24.'],
  peak_vram_diagnostics_interval: ['每 N 步输出一次显存诊断。建议排查期 25，稳定后关闭。', 'Print VRAM diagnostics every N steps while debugging. Disable once stable.'],
  peak_vram_auto_protection_enabled: ['动态显存自动保护：检测逼近上限自动降载。建议无人值守长训开启。', 'Dynamically sheds load as VRAM approaches the ceiling. Good for unattended runs.'],
  gradient_release_enabled: ['按参数即时释放梯度降低梯度峰值显存（默认 true）。建议保持开启；个别优化器不兼容会自动回退。', 'Frees gradients per-parameter to cut peak grad memory (default on). Keep on; incompatible optimizers fall back safely.'],
  gradient_release_mode: ['梯度释放模式：compatible 为当前唯一档位。建议保持 compatible。', 'Gradient-release mode; compatible is the only tier today. Keep compatible.'],
  gradient_release_grad_clip_mode: ['裁剪档位：exact 精确全局范数（默认，gas=1 约 +183MB）；per_param 近似省显存；report_only 只报告。建议 exact。', 'Clip mode: exact global norm (default, ~+183MB at gas=1), per_param approximate saving memory, report_only observes. Keep exact.'],
  optimizer_state_paging_enabled: ['大优化器状态张量在 step 间停泊到 CPU。建议 AdamW 大 rank 且显存紧时开启。', 'Pages large optimizer states to CPU between steps. Helps big-rank AdamW under VRAM pressure.'],
  optimizer_state_paging_min_tensor_mb: ['仅分页大于该体积的状态张量。推荐范围：1 MB（默认）以上。', 'Page only states above this MB. Recommended: >=1 MB.'],
  optimizer_state_paging_pin_memory: ['持久 pinned 镜像 + 独立拷贝流加速分页。建议内存充足时开启。', 'Persistent pinned mirror with a copy stream speeds paging. Enable with spare RAM.'],
  optimizer_state_paging_storage_device: ['状态驻留设备：cpu 在 step 间释放显存；param 跟随参数设备。建议 cpu。', 'Where paged states live: cpu frees VRAM; param follows parameters. Choose cpu.'],
  optimizer_state_paging_storage_dtype: ['CPU 驻留副本精度：preserve 原样；bf16/fp8 压缩体积。step 前恢复计算精度。建议 preserve 保稳。', 'Host-copy dtype: preserve exact; bf16/fp8 compress. Precision restores before step. Keep preserve.'],
  vram_smart_sensing_enabled: ['智能感知：建立速度基线，变慢时给出候选优化策略报告。建议新环境首跑开启观察建议。', 'Smart sensing builds a speed baseline and proposes candidate optimizations when things slow down. Run it on new setups.'],
  vram_smart_sensing_baseline_steps: ['建立平均速度基线的步数。推荐范围：50（默认）。', 'Steps used to build the speed baseline. Recommended: 50.'],
  vram_smart_sensing_window_steps: ['判断变慢的滑动窗口长度。推荐范围：5（默认）。', 'Sliding window for slow-down detection. Recommended: 5.'],
  vram_smart_sensing_slowdown_ratio: ['慢于基线多少倍触发提示。推荐范围：1.5（慢 50%）。', 'Slow-down multiple that triggers advice. Recommended: 1.5.'],
  vram_smart_sensing_sparse_swap_enabled: ['允许把稀疏交换列为候选策略。建议保持开启。', 'Allow sparse swap among reported candidates. Keep on.'],
  vram_smart_sensing_streaming_enabled: ['允许把流式 offload 列为候选策略。建议保持开启。', 'Allow streaming offload among candidates. Keep on.'],
  vram_smart_sensing_delta_cache_enabled: ['只读识别 PCIe delta/cache 候选，不做分配。建议保持开启获取报告。', 'Read-only detection of PCIe delta/cache candidates; no allocation happens. Keep on for reports.'],
  vram_auto_enhance_enabled: ['显存紧张时自动启用 Block Checkpointing 等增强。建议新手保持开启（默认 true）。', 'Auto-enables block checkpointing and friends when VRAM runs short. Keep on (default) for hands-free relief.'],
  vram_auto_tier: ['低显存自动档 T1–T3：启发式写入压缩与伴生配置，KPI 是能训不 OOM。建议 off 手动管控；应急选 T1 起步。', 'Auto tiers T1-T3 writing compression/companion knobs heuristically; goal is train-without-OOM. Manual first; emergency from T1.'],
  vram_auto_tier_force_extreme: ['允许自动档进 T3 极限档（未勾选时钳制在 T2）。建议确认接受明显减速再勾。', 'Permit tier T3 extremes (otherwise capped at T2). Accept the heavy slowdown before enabling.'],

  // ── 缓存/PCIe/Vortex/Aircon ──
  pcie_transfer_format: ['CPU-pinned 冻结权重的 PCIe 传输格式（off 关闭）。建议 off 起步，带宽瓶颈实测后再选格式。', 'Transfer format for pinned frozen weights over PCIe. Start off; pick a format only after measuring bandwidth limits.'],
  pcie_delta_cache_enabled: ['PCIe Delta/Cache 候选分析：observe 输出候选报告不改变行为。建议诊断期开启。', 'Observation-only candidate report for PCIe delta caching. Diagnostic aid.'],
  pcie_delta_cache_budget_mb: ['GPU 缓存预算 MB；0 表示不启用。推荐范围：256 起步，按空闲显存上调。', 'GPU-side cache budget in MB; start at 256. 0 disables caching.'],
  pcie_delta_cache_mode: ['observe 只读观察；cache_v0 手动启用缓存。建议 observe 先看报告。', 'observe reports only; cache_v0 enables actual caching. Observe first.'],
  vortex_enabled: ['Vortex 显存管理器总开关。建议默认关闭，需要其规划能力时再开。', 'Vortex VRAM manager master switch. Off by default; enable for its planning features.'],
  vortex_mode: ['Vortex 模式：observe/planner 只记录不改训练路径。建议 observe 先看信号。', 'observe/planner modes never alter tensor paths. Start with observe.'],
  vortex_strategy: ['传给 Vortex 管理器的策略名。建议保持 standard 默认。', 'Strategy name handed to Vortex. Keep standard.'],
  vortex_profile: ['Vortex 档位。建议 standard 默认。', 'Vortex performance profile. Keep standard.'],
  vortex_budget_mb: ['Vortex Cache 预算（MB）。推荐范围：256 起步按余量上调。', 'Vortex cache budget in MB; probe upward from 256.'],
  vortex_low_vram_protection_enabled: ['低于水位触发 Vortex 保护判断。建议与 free 水线配套使用。', 'Arms Vortex protection below the free-VRAM watermark. Pair with the threshold field.'],
  vortex_low_vram_protection_mode: ['保护模式：observe 只记录。建议 observe。', 'Protection mode; observe logs only. Keep observe.'],
  vortex_low_vram_min_free_mb: ['触发保护的最低空闲显存（MB）。推荐范围：512–2048 按卡设定。', 'Minimum free VRAM (MB) before protection engages. Recommended: 512-2048 by card size.'],
  adaptive_caching_enabled: ['Aircon：按 block 变化率跳过部分计算。与 sigma 深度调度正交。建议追求速度且容忍近似时试验。', 'Aircon skips blocks by change-rate signals, orthogonal to sigma-depth scheduling. For speed-tolerant experiments.'],
  adaptive_caching_threshold_base: ['变化率基线阈值，越高越少跳过。推荐范围：0.1（默认）附近微调。', 'Baseline change-rate threshold; higher skips less. Tune around 0.1.'],
  adaptive_caching_threshold_decay: ['随时间步衰减阈值（高 σ 更宽松）。建议 0.5。', 'Threshold decay over timesteps (looser at high sigma). Keep 0.5.'],
  adaptive_caching_ema_momentum: ['变化率 EMA 平滑系数。建议 0.9（默认）。', 'EMA smoothing for change rates. Keep 0.9.'],
  adaptive_caching_min_blocks_computed: ['每步至少完整计算的 block 数（稳定护栏）。推荐范围：4（默认）。', 'Hard minimum of fully computed blocks per step. Recommended: 4.'],
};
