// SPDX-License-Identifier: LicenseRef-PolyFormNoncommercial-1.0.0
// desc 文案表 —— 训练主循环 / 优化器 / 学习率 / 保存与日志。
// 值格式：['zh 新文案', 'en 翻译']；复杂键用 { zh, en, only? } 变体数组（only=当前 desc 需包含的子串）。
// 推荐范围依据：backend configs_base.py 默认值、training_config_checks.py 校验域、resources/training_wiki 口径。
export default {
  // ── 学习率与调度 ──
  learning_rate: [
    { zh: '主学习率：每次参数更新的步幅，是影响收敛与稳定性的首要超参。留空时按各子项学习率回退。推荐范围：LoRA 用 1e-4 起步（小数据集可到 5e-5）；全参 finetune 用 1e-6～5e-6；Prodigy/DAdaptation 系设 1.0 让其自适应。', en: 'Base learning rate: the step size of each parameter update and the most important hyperparameter. Recommended: 1e-4 for LoRA (5e-5 for small datasets); 1e-6 to 5e-6 for full finetune; set 1.0 for Prodigy/DAdaptation self-tuning.' },
    { zh: '蒸馏/短测场景的主学习率。推荐范围：LoRA 量级 1e-4 起步；真实蒸馏按教师/学生配置另行调参。', en: 'Base learning rate for distillation/smoke runs. Recommended: start at LoRA scale 1e-4.', only: '蒸馏' },
  ],
  unet_lr: ['U-Net/DiT 主干学习率，覆盖 learning_rate。推荐范围：与主学习率相同（1e-4 量级，LoRA）。', 'U-Net/DiT learning rate override. Recommended: same as base LR (1e-4 scale for LoRA).'],
  text_encoder_lr: ['文本编码器独立学习率。较低值保留预训练语义，同时适配触发词。推荐范围：UNet LR 的 1/2～1/10（后端默认 5e-5），或保持 0 冻结 TE。', 'Standalone text-encoder LR; lower values preserve pretrained semantics while adapting trigger words. Recommended: 1/2 to 1/10 of UNet LR (backend default 5e-5), or 0 to freeze TE.'],
  lr_scheduler: ['学习率随训练进度的变化曲线，影响中后期收敛质量。建议常规 LoRA 选 cosine 或 cosine_with_restarts；不确定时保持默认即可，loss 门控类调度适合想避免余弦过早触底的实验。', 'How LR evolves over training; affects mid/late convergence. For regular LoRA choose cosine or cosine_with_restarts; keep the default when unsure. Loss-gated schedulers suit experiments where an early cosine floor hurts.'],
  lr_warmup_steps: ['训练开始时学习率从 0 线性升到目标值的步数，避免初期大步长破坏稳定。推荐范围：0–500 步（默认 0 即可不预热；大数据集或高 LR 建议 100 左右）。', 'Steps to linearly ramp LR up from 0, protecting early stability. Recommended: 0-500 steps (default 0; use ~100 for large datasets or high LR).'],
  lr_scheduler_num_cycles: ['cosine_with_restarts 的重启次数：每个周期结束学习率回升再衰减。推荐范围：1–4（默认 1；多周期可缓解后期僵化）。', 'Restarts for cosine_with_restarts: LR rises again each cycle. Recommended: 1-4 (default 1).'],
  lr_scheduler_args: ['传给调度器的额外参数（如 min_lr），每行一个 key=value。不认识调度器的参数会被忽略，建议保持为空除非文档明确要求。', 'Extra scheduler args (e.g. min_lr), one key=value per line. Unknown args are ignored; keep empty unless documented.'],

  // ── 训练长度 ──
  max_train_epochs: ['训练遍历整个数据集的次数上限，决定总训练量。推荐范围：小数据集（<50 张）10–30 轮；大数据集 1–5 轮；与 max_train_steps 二选一设置。', 'Max passes over the dataset; sets total training amount. Recommended: 10-30 epochs for small datasets (<50 images), 1-5 for large ones. Set either this or max_train_steps.'],
  epochs: ['训练轮数（蒸馏/短测流程用）。推荐范围：与数据规模匹配的 1–10 轮起步。', 'Training epochs (distillation/smoke flow). Recommended: start with 1-10 epochs matched to dataset size.'],
  max_train_steps: ['按优化器更新步数控制训练长度，比轮数更精确。推荐范围：设 0 表示不启用；启用时常用 1000–5000 步做 LoRA。', 'Controls training length by optimizer updates, more precise than epochs. Recommended: 0 to disable; 1000-5000 steps is typical for LoRA.'],
  train_length_mode: ['选择按最大轮数还是最大步数结束训练，两者只生效一个。建议概念简单的小数据集用轮数，大图库或精确控量用步数。', 'End training by max epochs or max steps; only one applies. Use epochs for small concept sets, steps for precise budgets on larger libraries.'],
  initial_epoch: ['续训时的起始 epoch 编号，推荐范围：保持默认 1；仅 resume 场景为对齐编号才改，且只影响日志/保存命名计数、不跳过训练。', 'Starting epoch number for resumed runs (naming/log counter only, skips nothing). Keep 1 unless aligning with a resumed run.'],
  initial_step: ['续训时的起始 step 编号并覆盖 initial_epoch。推荐范围：普通训练保持 0；配合 skip_until_initial_step 才会真正跳过前面的步数。', 'Starting step number for resumes (overrides initial_epoch). Pair with skip_until_initial_step to actually skip; keep 0 otherwise.'],
  skip_until_initial_step: ['开启后 dataloader 会真正丢弃 initial_step 之前的样本，而不是仅改计数。建议仅在断点续训对齐进度时开启。', 'When on, samples before initial_step are truly skipped instead of just renumbered. Enable only to realign a resumed run.'],

  // ── 批量与梯度 ──
  train_batch_size: ['每次前向/反向同时处理的图片数，直接影响显存与梯度平滑度。推荐范围：显存优先取 1，24G 卡 SDXL 1024px 可到 2；配合梯度累加放大等效 batch。', 'Images processed per forward/backward pass; drives VRAM and gradient smoothness. Recommended: 1 when VRAM-bound, up to 2 for SDXL 1024px on 24 GB; scale effective batch with grad accumulation.'],
  gradient_accumulation_steps: ['累积 N 个 micro-batch 再更新一次参数，等效放大 batch 而不增加峰值显存。推荐范围：1（默认）或 4–8；等效 batch = batch_size × 本值。', 'Accumulate N micro-batches per update, scaling effective batch without extra peak VRAM. Recommended: 1 (default) or 4-8; effective batch = batch_size x this value.'],
  gradient_accumulation_mode: ['梯度累加实现路径：fast 只在真正 optimizer.step 时同步/检查（更快），classic 保留旧逐 micro-batch 检查。建议保持 fast，排查累加相关异常时再切 classic 对照。', 'Grad accumulation implementation: fast syncs/checks only at optimizer steps (faster); classic keeps legacy per-microbatch checks. Keep fast; switch to classic only when debugging accumulation issues.'],
  max_grad_norm: ['梯度裁剪的全局范数上限，防止个别 step 梯度爆炸。推荐范围：保持默认 1.0；LoRA 一般无需改动，全参微调也常用 1.0。', 'Global-norm clip threshold against exploding gradients. Recommended: keep default 1.0 for LoRA and full finetune alike.'],
  gradient_guard_strategy: ['梯度防护策略：none 关闭；agc 按参数范数比例裁剪；centralized/agc_centralized 做集中式范数防护。建议默认 none，出现训练不稳或梯度尖峰时再试 agc。', 'Gradient guard mode: none disables; agc clips per parameter-norm ratio; centralized variants add pooled norm guards. Keep none by default; try agc when training destabilizes.'],
  gradient_guard_agc_clip_factor: ['AGC 把梯度范数限制为参数范数的该比例。推荐范围：0.01（默认）附近，过大失去防护意义。', 'AGC caps grad norm at this fraction of weight norm. Recommended: around default 0.01.'],
  gradient_guard_agc_eps: ['AGC 中参数范数的下限，防止除零。建议保持默认 1e-3。', 'Floor for weight norms in AGC to avoid division by zero. Keep default 1e-3.'],

  // ── 精度 ──
  mixed_precision: [{ zh: '混合精度：前向/反向用低精度计算、保留 FP32 主权重。bf16 数值最稳（RTX30 系+/A100 必选）；fp16 给旧卡但需梯度缩放；no 为全精度调试用。推荐范围：bf16（默认）。', en: "Mixed precision: low-precision compute with FP32 master weights. bf16 is most stable (required on RTX30+/A100); fp16 for older cards; 'no' means full-precision training for debugging. Recommended: bf16." }],
  full_fp16: ['完全 FP16 训练（含主权重），省显存但易溢出出 NaN。建议仅老卡且明确需要时开，日常保持关闭。', 'Full FP16 training including master weights; saves VRAM but risks NaN overflow. Keep off except on old GPUs that truly need it.'],
  full_bf16: ['完全 BF16 训练（含主权重），比 fp16 稳但略损精度。建议 30 系以上显卡且显存吃紧时才开。', 'Full BF16 training including master weights; more stable than fp16 with slight precision cost. Enable on RTX30+ only when VRAM is tight.'],
  dtype: ['底模加载与计算精度。auto 按设备自动选择；建议 auto 或 bf16，fp16 仅用于不支持 bf16 的环境。', 'Base-model load/compute dtype. auto picks per device. Prefer auto or bf16; fp16 only where bf16 is unsupported.'],
  clip_skip: ['CLIP 特征取倒数第 N 层，改变文本条件风格。推荐范围：SD1.5 社区常用 2，SDXL 保持 1（>1 属实验行为，预检会告警）。', 'Which CLIP layer from the top provides text features. Recommended: 2 is common for SD1.5; keep 1 for SDXL (>1 is experimental and warns in preflight).'],
  v2: ['声明底模为 SD 2.x 架构（影响 tokenizer/padding 与 v-pred 判断）。建议仅在确实使用 SD2.x 底模时开启，SD1.5/SDXL 保持 false。', 'Declare the base model as SD 2.x architecture (affects tokenizer/padding and v-prediction). Enable only for actual SD2.x checkpoints; keep false otherwise.'],
  v_parameterization: ['v-prediction 模式：模型预测 v=noise−latent 而非噪声本身，部分 SD2.x/512 底模需要。建议跟随底模说明，不确定时关闭。', 'v-prediction mode: predict v=noise-latent instead of noise; required by some SD2.x checkpoints. Follow your base model; keep off when unsure.'],
  zero_terminal_snr: ['把 SNR 曲线终端置零，改善 v-pred 亮部/暗部对比度。建议仅 v-pred 训练配合使用，eps 训练不要开。', 'Zeroes terminal SNR to improve contrast in v-pred models. Use only with v-prediction training; keep off for eps models.'],

  // ── 噪声与损失加权 ──
  noise_offset: ['在噪声上叠加常数偏移，改善纯黑/纯白等极端明暗的生成。推荐范围：0.05–0.08（甜区），明暗极端的数据可用 0.1；默认 0 关闭。', 'Adds a constant offset to noise, improving very dark/bright generations. Recommended: 0.05-0.08, up to 0.1 for extreme lighting data; 0 disables.'],
  adaptive_noise_scale: ['按 latent 平均绝对值动态追加 noise_offset，亮图正偏移暗图负偏移。推荐范围：noise_offset 的 10%–50%（如 0.01），需先开 noise_offset。', 'Scales extra noise_offset by mean |latent| so bright images get positive offset. Recommended: 10-50% of noise_offset (e.g. 0.01); requires noise_offset > 0.'],
  noise_offset_random_strength: ['噪声偏移强度在 0 到设定值间随机取值，增加多样性。建议常规训练关闭；明暗跨度大的数据集可开。', 'Randomizes offset strength between 0 and the set value for diversity. Keep off normally; consider for wide dynamic-range datasets.'],
  multires_noise_iterations: ['多分辨率金字塔噪声的迭代层数，让不同尺度噪声更平滑。推荐范围：6–10（配 discount 使用），0 关闭。', 'Pyramid-noise iteration count for smoother multi-scale noise. Recommended: 6-10 with discount enabled; 0 disables.'],
  multires_noise_discount: ['金字塔噪声各层的衰减率，越低高频占比越小。推荐范围：0.3–0.8（默认 0.3 附近）。', 'Decay across pyramid-noise layers; lower means less high-frequency energy. Recommended: 0.3-0.8.'],
  min_snr_gamma: ['对高信噪比 timestep 降权，均衡各去噪阶段的学习。推荐范围：5（论文推荐值）；轻度 3；小数据集强调细节可用 8；0/留空关闭。', 'Down-weights high-SNR timesteps to balance learning stages. Recommended: 5 (paper value); 3 mild; 8 for small datasets emphasizing detail; 0/empty disables.'],
  ip_noise_gamma: ['向条件输入注入扰动作为正则，抑制过拟合。推荐范围：0.1 起步小步试探；默认留空关闭。', 'Injects perturbation into conditioning as regularization. Recommended: start at 0.1 cautiously; empty disables.'],
  ip_noise_gamma_random_strength: ['扰动强度在 0 到 gamma 之间随机。建议常规训练关闭，仅实验对比用。', 'Randomizes perturbation strength between 0 and gamma. Keep off for normal runs.'],
  immiscible_diffusion_enabled: ['minibatch 内按度量重排噪声-数据配对，降低噪声与目标互渗。建议数据集小、收敛慢时试验；默认关闭。', 'Re-pairs noise/data within a minibatch by metric to reduce interference. Try on slow-converging small sets; off by default.'],
  immiscible_metric: ['配对距离度量：l2 经典实现，cosine 更接近 flow OT 配对。建议保持默认 lulynx_greedy 对应度量，改动需 A/B 对比。', 'Pairing metric: l2 classic; cosine closer to flow OT. Keep defaults unless A/B testing.'],
  immiscible_assignment_mode: ['配对算法：standard 全局最优 Hungarian（更准更慢）；lulynx_greedy 兼容现有逐行贪心。建议 greedy 起步。', 'Assignment algorithm: standard Hungarian (optimal, slower); lulynx_greedy row-greedy. Start with greedy.'],
  smart_noise_enabled: ['Smart Noise Scheduler：按 logSNR 聚焦特定噪声区间采样，强化该区间学习。建议默认关闭，明确想强化细节/结构某端时再用。', 'Smart Noise Scheduler focuses sampling on a logSNR band. Keep off unless targeting a specific detail/structure band.'],
  smart_noise_logsnr_focus: ['聚焦中心的 logSNR 值。推荐范围：-3～3 内试探，0 为中点。', 'Center of the focus band in logSNR. Recommended: probe within -3..3; 0 is midpoint.'],
  smart_noise_focus_strength: ['聚焦强度 0–1，越大采样越集中于焦点。推荐范围：0.3–0.7。', 'Focus intensity 0-1; higher concentrates sampling. Recommended: 0.3-0.7.'],
  smart_noise_focus_spread: ['焦点高斯的宽度（logSNR 单位标准差）。推荐范围：0.5–5（默认 2）。', 'Width (std) of the Gaussian focus in logSNR units. Recommended: 0.5-5 (default 2).'],
  loss_type: ['损失函数类型（l2/l1/huber 等），决定对离群样本的敏感度。建议保持 l2 默认；标签噪声大时试 huber。', 'Loss function (l2/l1/huber...) controlling outlier sensitivity. Keep l2; try huber for noisy tags.'],
  loss: ['回归损失函数选择。建议保持 mse；数据噪声明显时可换 huber 族。', 'Regression loss choice. Keep mse; huber variants help with noisy data.'],
  huber_c: ['huber/smooth_l1/pseudo_huber 的过渡阈值 delta：小于 c 按 L2、大于按 L1。推荐范围：0.1 附近（默认）。', 'Huber transition threshold: quadratic below c, linear above. Recommended: near default 0.1.'],
  huber_scale: ['Huber 损失整体缩放系数。推荐范围：保持 1，与其他权重轴分开调节。', 'Overall Huber loss scale. Keep 1; adjust dedicated weight axes instead.'],
  huber_schedule: ['Huber 阈值的调度方式：constant 固定；auto 按 batch 分位数自适应。建议 constant 起步，loss 量级漂移明显时用 auto。', 'Huber threshold schedule: constant fixed; auto adapts from batch quantiles. Start constant; use auto when loss scale drifts.'],
  huber_auto_percentile: ['schedule=auto 时估计 delta 的分位数。推荐范围：0.9（默认）附近。', 'Quantile used to estimate delta in auto schedule. Recommended: near default 0.9.'],
  debiased_estimation_loss: ['Debiased Estimation 损失加权，改进低噪段梯度估计。建议实验性开启并与基线对比。', 'Debiased estimation loss weighting for low-noise gradients. Experimental; compare against baseline.'],
  weighted_captions: ['解析 caption 中的 (tag:1.2) 权重语法。建议标注里用了权重语法时开启，否则关闭以免误解析。', 'Parse (tag:1.2) weight syntax in captions. Enable only if captions actually use weighted syntax.'],
  masked_loss: ['只在被遮罩区域计算 loss（配合 mask 图）。建议有区域标注且只想学主体时开启。', 'Compute loss only inside mask regions (requires mask images). Enable for subject-only learning with region annotations.'],
  p2_weighting_mode: ['感知加权模式：p2=(k+SNR)^-γ 论文加权；lulynx_structure/detail 为本仓工程权重；off 恒等。建议默认 off，构图/细节失衡时再试 p2。', 'Perception weighting: p2=(k+SNR)^-gamma paper form; lulynx structure/detail variants; off identity. Keep off unless composition/detail balance skews.'],
  p2_weighting_strength: ['P2 加权强度 γ。推荐范围：0.5–1 起步；0 恒等；收益需同条件 A/B 验证。', 'P2 strength gamma. Recommended: start 0.5-1; 0 disables; validate gains via A/B.'],
  scale_weight_norms: ['对 LoRA 权重做最大范数约束（Spectral Norm 正则），抑制过拟合。推荐范围：1（社区惯例值）；留空/0 关闭。', 'Max-norm (spectral-norm-style) regularization on LoRA weights. Recommended: 1 if used; 0/empty disables.'],
  scale_v_pred_loss_like_noise_pred: ['把 v-pred 损失缩放到 noise-pred 量纲，统一不同预测目标的损失尺度。建议 v-pred 训练保持开启（默认 true）。', 'Rescales v-pred loss to noise-pred magnitude for consistent scale. Keep on (default) for v-pred runs.'],
  fused_backward_grad_clip_mode: ['LOMO/AdaLOMO 单遍反传内更新拿不到全部梯度，此选项选裁剪档位：default 不裁剪最快；full 多一次预反传拿精确范数；per_param 近似裁剪。建议 default。', 'LOMO/AdaLOMO clip mode: default skips clipping (fastest); full adds a pre-pass for exact global norm; per_param approximates. Keep default.'],

  // ── 优化器 ──
  optimizer_type: ['优化器决定如何用梯度更新权重，是稳定性与显存的关键。AdamW8bit 最稳妥省显存；Prodigy/AutoProdigy 自适应步长免调 LR；ScheduleFree 系内置衰减。建议默认 AdamW8bit + cosine。', 'Optimizer controls weight updates and drives stability/VRAM. AdamW8bit is the safe default; Prodigy/AutoProdigy self-tune step size; ScheduleFree variants need no scheduler. Recommended: AdamW8bit + cosine.'],
  optimizer_backend: ['AdamW 的后端实现档位（torch/foreach/fused/bnb 等），数值等价但速度显存有别。建议保持 auto 让后端择优。', 'AdamW backend implementation (torch/foreach/fused/bnb...); numerically equivalent with different speed/memory. Keep auto.'],
  advanced_optimizer_strategy: ['高级优化策略入口：auto 自动判定；lora_plus/rs_lora 等在此叠加。建议 auto，不需要特殊策略时无感。', 'Advanced optimizer strategy hook: auto decides; specific strategies opt in. Keep auto.'],
  optimizer_args: ['传给优化器的额外参数，每行 key=value。建议留空，除非所用优化器文档明确要求（如 Prodigy 的 d_coef 也可走专用字段）。', 'Extra optimizer args, one key=value per line. Leave empty unless the optimizer documents them.'],
  optimizer_preset: ['后端预设组合名（Fast/Stable/Memory-efficient 等）。建议留空走页面配置；填了会覆盖同名项。', 'Backend preset name (Fast/Stable/Memory-efficient...). Empty uses page settings; a value overrides matching items.'],
  blockwise_fused_optimizers: ['把多个优化器 kernel 融合执行以省时。建议保持默认关闭，确认所用优化器支持后再开。', 'Fuse optimizer kernels to cut step time. Keep off until your optimizer is confirmed supported.'],
  fused_optimizer: ['启用融合优化器路径（单 kernel 完成 step）。建议默认关闭；追求极限吞吐且验证过稳定性后再开。', 'Use the fused optimizer path (single-kernel step). Keep off by default; enable after validating stability.'],
  use_lookahead: ['Lookahead 外层慢更新包装，平滑优化轨迹。建议实验性使用，常规训练关闭。', 'Wraps the optimizer with Lookahead slow weights. Experimental; keep off normally.'],
  opt_adan_no_prox: ['禁用 Adan 近端项（weight decay 行为变化）。建议保持默认 false 以贴近论文配置。', 'Disable Adan proximal update (changes decay behavior). Keep false to match the paper.'],
  opt_adan_beta3: ['Adan 第三动量（梯度差分 EMA）系数。推荐范围：0.99（论文值）。', 'Adan third-momentum coefficient for gradient-difference EMA. Recommended: 0.99 (paper value).'],
  opt_ademamix_alpha: ['AdEMAMix 慢速 EMA 混合权重。推荐范围：5.0（默认/论文常用）。', 'AdEMAMix slow-EMA mixing coefficient. Recommended: 5.0.'],
  opt_ademamix_beta3: ['AdEMAMix 慢速 EMA 动量。推荐范围：0.9999（默认）。', 'AdEMAMix slow-EMA momentum. Recommended: 0.9999.'],
  opt_ademamix_t_alpha_beta3: ['alpha/beta3 的线性预热步数，0 表示不预热。建议长训练可给 2000 左右，短训保持 0。', 'Warmup steps ramping alpha/beta3; 0 disables. Consider ~2000 for long runs.'],
  opt_adopt_clip_lambda: ['ADOPT 梯度裁剪系数，防早期爆炸。推荐范围：0.1（默认）附近；0 关闭。', 'ADOPT clip lambda guarding early steps. Recommended: ~0.1; 0 disables.'],
  opt_adopt_eps: ['ADOPT 数值稳定 epsilon。建议保持默认 1e-6。', 'ADOPT numerical-stability epsilon. Keep default 1e-6.'],
  opt_dadapt_d0: ['DAdaptation 初始步长估计。推荐范围：1e-6（默认，小值让其自行爬升）。', 'Initial DAdaptation step-size estimate. Recommended: 1e-6 (lets it self-scale).'],
  opt_dadapt_growth_rate: ['DAdaptation 步长增长上界倍率。建议留空用默认；设置过小会限制自适应速度。', 'Upper bound on DAdaptation growth rate. Leave empty for default; too small throttles adaptation.'],
  opt_lion_use_triton: ['Lion 用 Triton fused kernel 加速。建议仅 NVIDIA 且装好 Triton 时开启，失败会回落。', 'Accelerate Lion with a Triton fused kernel. Enable on NVIDIA with Triton available; falls back on failure.'],
  opt_muon_momentum: ['Muon 动量系数。推荐范围：0.95（默认）。', 'Muon momentum coefficient. Recommended: 0.95.'],
  opt_muon_nesterov: ['Muon 启用 Nesterov 前瞻动量。建议保持开启（通常更优）。', 'Nesterov lookahead momentum for Muon. Keep on (usually better).'],
  opt_sophia_rho: ['SophiaH 更新裁剪系数。推荐范围：0.04（论文值）。', 'SophiaH update clip coefficient. Recommended: 0.04.'],
  opt_sophia_update_period: ['Hessian 对角估计的更新间隔步数。推荐范围：10（默认）；越大越快越粗糙。', 'Steps between Hessian-diagonal estimates. Recommended: 10; larger is faster but coarser.'],
  opt_soap_precondition_frequency: ['SOAP 预条件矩阵更新频率（每 N 步）。推荐范围：10（默认）；增大省时但适应变慢。', 'Steps between SOAP preconditioner updates. Recommended: 10; higher saves time but adapts slower.'],
  opt_soap_shampoo_beta: ['Shampoo 因子 EMA 系数；-1 表示按 beta1 处理。建议保持 -1。', 'Shampoo factor EMA coefficient; -1 follows beta1. Keep -1.'],
  opt_sf_beta: ['Schedule-Free 内置动量 β。推荐范围：0.9（默认）。', 'Schedule-Free built-in momentum beta. Recommended: 0.9.'],
  opt_sf_warmup_steps: ['Schedule-Free 内置预热步数，与外部 lr_warmup 二选一。建议 0 走外部预热或少量 100–500。', 'Schedule-Free internal warmup; prefer this over external warmup, 100-500 steps or 0.'],
  opt_spam_gamma: ['SPAM 动量重置阈值（梯度超 gamma×均值触发）。推荐范围：2（默认）。', 'SPAM momentum-reset threshold relative to mean gradient. Recommended: 2.'],
  opt_spam_density: ['SPAM 动量稀疏化比例，0=不稀疏。建议保持 0（关闭）。', 'Momentum sparsification fraction; 0 keeps dense. Keep 0.'],
  opt_mars_gamma: ['MARS 梯度校正强度。推荐范围：0.025（论文常用）。', 'MARS gradient-correction strength. Recommended: 0.025.'],
  opt_mars_eps: ['MARS 数值稳定 epsilon。建议保持 1e-8。', 'MARS stability epsilon. Keep 1e-8.'],
  opt_mars_cautious: ['MARS cautious 掩码：只保留与梯度同号的更新分量。建议开启尝试提升稳定性。', 'Cautious mask keeps only same-sign update components. Worth enabling for stability.'],
  opt_mars_ams_bound: ['MARS 启用 AMSBound 变体二阶矩。建议默认关闭。', 'AMSBound-style second moment for MARS. Keep off by default.'],
  opt_grok_alpha: ['GrokFast 梯度 EMA 系数。推荐范围：0.98（默认）。', 'GrokFast gradient EMA coefficient. Recommended: 0.98.'],
  opt_grok_lamb: ['GrokFast EMA 混合比例 λ。推荐范围：2.0（默认）。', 'GrokFast EMA mixing lambda. Recommended: 2.0.'],
  opt_kahan8bit_block_size: ['KahanAdamW8bit 分块量化块大小。推荐范围：2048（默认）；必须是 64–4096 的 2 的幂。', 'Block size for KahanAdamW8bit quantization. Recommended: 2048; power-of-two 64..4096.'],
  opt_kahan8bit_min_8bit_size: ['低于该元素数的张量保留 fp32，规避小张量量化噪声。推荐范围：4096（默认）。', 'Tensors below this element count stay fp32 to avoid quantization noise. Recommended: 4096.'],
  opt_kron_precond_update_prob: ['Kron 预条件矩阵随机更新概率（均摊开销）。推荐范围：0.03（默认）。', 'Probability of refreshing Kron preconditioner per step. Recommended: 0.03.'],
  opt_came_eps_group: ['CAME 参数组级 epsilon。建议保持 1e-8。', 'Per-group epsilon for CAME. Keep 1e-8.'],
  opt_came_eps_rho: ['CAME 曲率估计 epsilon。建议保持 1e-6。', 'Curvature epsilon for CAME. Keep 1e-6.'],
  opt_scion_init_scale: ['SCION 初始化缩放。建议保持 1.0。', 'SCION initialization scale. Keep 1.0.'],
  opt_scion_kappa: ['SCION 归一化约束系数。推荐范围：0.01–0.1。', 'SCION normalization constraint coefficient. Recommended: 0.01-0.1.'],
  opt_fadam_p: ['FAdam Fisher 信息幂次。推荐范围：0.5（平方根，论文值）。', 'Fisher-information exponent for FAdam. Recommended: 0.5.'],
  opt_aurora_momentum: ['Aurora 动量系数。推荐范围：0.95（默认）。', 'Aurora momentum. Recommended: 0.95.'],
  opt_aurora_nesterov: ['Aurora 启用 Nesterov 动量。建议保持开启。', 'Nesterov momentum for Aurora. Keep on.'],
  opt_aurora_ns_steps: ['Aurora Newton-Schulz 正交化迭代数。推荐范围：6（默认）；越大越准越慢。', 'Newton-Schulz iterations for Aurora orthogonalization. Recommended: 6.'],
  opt_aurora_pp_iterations: ['Aurora 行范数均衡投影迭代。推荐范围：2（默认）。', 'Leverage-score balancing projections for Aurora. Recommended: 2.'],
  opt_aurora_damping: ['Aurora 行范数均衡强度 0–1。建议 0.5（默认）。', 'Row-norm balancing strength for Aurora, 0-1. Keep 0.5.'],
  opt_riemannion_momentum: ['Riemannion 流形动量。推荐范围：0.9（默认）。', 'Riemannion manifold momentum. Recommended: 0.9.'],
  opt_riemannion_ns_steps: ['Riemannion Newton-Schulz 迭代数。推荐范围：5（默认）。', 'Newton-Schulz iterations for Riemannion. Recommended: 5.'],
  opt_riemannion_orthogonalize: ['对更新做 Newton-Schulz 正交化。建议保持开启以稳定流形步长。', 'Orthogonalize updates via Newton-Schulz. Keep on for stable manifold steps.'],
  opt_riemannion_solve_eps: ['Riemannion 求解阻尼 epsilon。建议保持 1e-6。', 'Numerical damping epsilon for Riemannion. Keep 1e-6.'],
  opt_rose_gradient_centralization: ['Rose 梯度去均值中心化。建议保持开启（常利于泛化）。', 'Gradient centralization for Rose. Keep on; often helps generalization.'],
  opt_rose_stochastic_rounding: ['低精度更新随机取整，减少舍入偏差。建议保持开启。', 'Stochastic rounding for low-precision updates. Keep on to reduce bias buildup.'],
  opt_adafactor_relative_step: ['Adafactor 使用相对步长自适应。建议关闭并用固定 LR 以便复现；开启则忽略 learning_rate。', 'Adafactor relative-step self-scaling. Keep off to train with a fixed LR; on ignores learning_rate.'],
  opt_adafactor_warmup_init: ['relative_step=True 时初始预热。建议保持关闭。', 'Warmup init for Adafactor relative_step. Keep off.'],
  prodigy_d0: ['Prodigy 初始步长估计。推荐范围：1e-6（默认，小值起步最稳）。', 'Prodigy initial step-size estimate. Recommended: 1e-6 (safest start).'],
  prodigy_d_coef: ['Prodigy 步长放大系数。推荐范围：1.0（默认）；>1 更激进易过冲。', 'Prodigy step-size multiplier. Recommended: 1.0; above 1 gets aggressive.'],
  auto_prodigy_d0: ['AutoProdigy 初始步长估计。推荐范围：1e-6（默认）。', 'AutoProdigy initial step estimate. Recommended: 1e-6.'],
  auto_prodigy_d_coef: ['AutoProdigy 步长系数。建议保持 1.0。', 'AutoProdigy step multiplier. Keep 1.0.'],
  auto_prodigy_growth_rate: ['AutoProdigy 步长增长上限倍率。建议保持 1.02。', 'AutoProdigy growth-rate cap. Keep 1.02.'],
  auto_prodigy_damping: ['AutoProdigy 阻尼系数。建议保持 1.0。', 'AutoProdigy damping. Keep 1.0.'],
  auto_prodigy_beta3: ['AutoProdigy 第三动量。建议保持 0.99。', 'AutoProdigy third momentum. Keep 0.99.'],
  auto_prodigy_max_update_rms_ratio: ['更新 RMS 相对权重 RMS 的上限比例。建议保持 0.01。', 'Cap on update RMS relative to weight RMS. Keep 0.01.'],
  auto_prodigy_profile: ['AutoProdigy 档位：safe 小数据集保守；balanced 默认；aggressive 激进。建议 balanced，不稳退 safe。', 'AutoProdigy profile: safe conservative, balanced default, aggressive. Use balanced; drop to safe if unstable.'],
  auto_prodigy_safeguard_warmup: ['预热阶段保护自适应步长不被放大。建议保持开启。', 'Protect the adaptive step during warmup. Keep on.'],
  muon_momentum: ['MuOn 优化器动量（别名入口）。推荐范围：0.95。', 'Muon optimizer momentum alias. Recommended: 0.95.'],

  // ── 权重衰减 ──
  weight_decay: ['AdamW 系 L2 正则强度，抑制权重无限增长。推荐范围：0.01（默认）；Prodigy/DAdaptation 系会自行管理，可设 0。', 'AdamW-family L2 regularization limiting weight growth. Recommended: 0.01 (default); Prodigy/DAdaptation manage their own and accept 0.'],

  // ── 种子 ──
  seed: ['随机种子：固定后数据顺序/初始化/噪声可复现。推荐范围：调试期与正式出包都建议固定（如 1337）便于复现；-1 表示每次随机。', 'Random seed: fixed values make data order/init/noise reproducible; -1 randomizes. Fix during development and for release runs.'],

  // ── 保存 ──
  output_name: ['输出文件名（不含扩展名）。建议用「概念名+版本」命名（如 lulu_v2），同一目录多次训练勿重名以免覆盖。', 'Output filename without extension. Name as concept+version (e.g. lulu_v2) and avoid reusing names in one folder.'],
  output_dir: ['模型输出目录。建议指向专用盘的 models/lora 类目录，避免系统盘；训练缓存与数据集分开存放。', 'Folder where trained models are written. Point to a dedicated drive/folder, separate from caches and datasets.'],
  logging_dir: ['TensorBoard 日志目录。建议保持默认或指向独立的 logs 目录，便于多 run 对比。', 'TensorBoard log directory. Keep default or a dedicated logs folder for run comparison.'],
  log_with: ['训练指标上报渠道。建议 tensorboard（默认）；wandb 需要联网与 API key。', 'Metric reporting backend. tensorboard recommended; wandb needs network and an API key.'],
  wandb_api_key: ['Weights & Biases API key，仅 log_with=wandb 时必填。注意保密，勿提交到仓库。', 'W&B API key, required only when log_with=wandb. Keep secret; never commit.'],
  save_every_n_epochs: ['每 N 轮保存一次模型。推荐范围：1–5；注意与 save_every_n_steps 互斥，同时设置可能导致存储暴涨。', 'Save a checkpoint every N epochs. Recommended: 1-5; mutually exclusive with step-based saving.'],
  save_every_n_steps: ['每 N 步保存一次模型。推荐范围：500–2000；与 epoch 保存互斥。', 'Save every N steps. Recommended: 500-2000; mutually exclusive with epoch saving.'],
  save_n_epoch_ratio: ['整段训练按比例保存 N 份，均匀铺开时间轴便于挑选。推荐范围：2–4。', 'Save N evenly spaced checkpoints across training for later picking. Recommended: 2-4.'],
  save_last_n_epochs: ['滚动只保留最近 N 个按轮保存的模型，防磁盘爆满。推荐范围：1–3。', 'Keep only the latest N epoch checkpoints to protect disk. Recommended: 1-3.'],
  save_last_n_steps: ['滚动只保留最近 N 个按步保存的模型。推荐范围：1–3。', 'Keep only the latest N step checkpoints. Recommended: 1-3.'],
  save_last_n_epochs_state: ['滚动保留最近 N 份「含优化器状态」的训练状态（体积大）。推荐范围：1。', 'Keep the latest N resumable states (large, includes optimizer). Recommended: 1.'],
  save_last_n_steps_state: ['滚动保留最近 N 份按步的训练状态。推荐范围：1。', 'Keep the latest N step-based resumable states. Recommended: 1.'],
  save_state: ['随 checkpoint 一起保存优化器动量等完整状态（体积约为模型 2–3 倍），供 resume 续训。建议长任务开启，短任务关闭省磁盘。', 'Also persist optimizer state for resume (2-3x model size). Enable for long jobs; disable to save disk on short ones.'],
  save_state_on_train_end: ['训练结束时额外保存一份最终状态。建议需要从终点继续微调时开启。', 'Persist a final resumable state at train end. Enable if you may continue from the endpoint.'],
  save_model_as: ['产物容器格式。safetensors 安全且加载快（推荐）；ckpt 兼容旧工具链。此处是 LoRA/dense 容器选择，不是 Comfy INT8 适配器格式。', 'Artifact container format. safetensors is safe and fast (recommended); ckpt for legacy tooling. This is the LoRA/dense container, not Comfy INT8 adapters.'],
  save_precision: ['保存精度：auto 跟随底模/混合精度；float 最通用。INT8/FP8 压缩底模 dequant 后仍输出高精度。建议 auto。', 'Checkpoint precision: auto follows base/mixed precision; float is safest. Compressed bases still export high precision after dequant. Keep auto.'],
  no_metadata: ['不在产物写入训练元数据（提示词等）。建议发布敏感包时开启，一般保持关闭以便追溯。', 'Omit training metadata from artifacts. Enable for sensitive releases; keep off otherwise for traceability.'],
  resume: ['从 save_state 保存的状态目录继续训练（选目录而非文件）。建议只在同版本代码/同配置下 resume，跨版本可能不兼容。', 'Resume from a save-state directory (folder, not file). Resume only with the same code version/config to stay compatible.'],
  network_weights: ['从已有 LoRA 文件继续训练（增量叠加而非重置）。建议 dim/alpha 与原模型一致；换底模时注意域差。', 'Continue training from an existing LoRA (additive, not reset). Match its dim/alpha; mind base-model drift.'],
  thin_svd_export_enabled: ['保存时对 LoRA 做目标秩 SVD 压缩减小体积。建议默认关闭；RS-LoRA 会自动跳过（数学不等价）。', 'Compress LoRA via target-rank SVD at save time. Keep off by default; RS-LoRA skips automatically.'],
  thin_svd_export_rank: ['Thin-SVD 目标秩，必须小于原 network_dim；0/留空不压缩。建议仅存档分发时使用。', 'Target rank for Thin-SVD export, below original dim; 0/empty disables. Use for archival distribution only.'],
  merge_export: ['训练完成后把 LoRA 合并进底模另存 dense 整模（体积大、不可卸载）。建议仅在交付合并版时开启。', 'Bake the LoRA into the base and save a dense model after training. Enable only when delivering merged artifacts.'],

  // ── 验证 ──
  validation_split: ['从训练集切出的验证比例。推荐范围：0.05–0.2（<0.05 后端会提示）；0 关闭验证。', 'Fraction held out for validation. Recommended: 0.05-0.2 (<0.05 warns); 0 disables.'],
  val_ratio: ['未用 split 字段时按比例随机切分验证集。推荐范围：0.1（默认）附近。', 'Validation split when the split field path is unused. Recommended: ~0.1.'],
  eval_batch_size: ['验证批大小；0/留空沿用训练 batch。推荐范围：与训练一致或减半，防验证 OOM。', 'Eval batch size; 0/empty reuses the training batch. Match or halve it to avoid eval OOM.'],
  max_validation_steps: ['每次验证最多处理的批次上限，控制验证耗时。推荐范围：20–100；0/留空不设限。', 'Max batches per validation pass. Recommended: 20-100; 0/empty unlimited.'],
  validate_every_n_epochs: ['每 N 轮跑一次验证。推荐范围：1–5，与保存节奏一致。', 'Run validation every N epochs. Align with saving cadence (1-5).'],
  validate_every_n_steps: ['每 N 步跑一次验证，过密拖慢训练。推荐范围：500–2000。', 'Run validation every N steps. Recommended: 500-2000; too frequent slows runs.'],
  validation_seed: ['验证集切分的随机种子，保证每次切分一致。推荐范围：固定一个任意值便于横向比较。', 'Seed for the validation split so it stays identical across runs. Fix it for comparability.'],

  // ── 分布式 ──
  enable_distributed_training: ['启用 DDP 多卡并行。建议单卡能放下时不开启；开启后 batch 为每卡数值。', 'Enable DDP multi-GPU training. Skip when a single GPU fits; note batch is per-GPU once on.'],
  num_processes: ['本机启动的训练进程数，留空按所选 GPU 数推断。推荐范围：等于 GPU 数。', 'Processes launched on this machine. Recommended: leave empty to infer from GPU count.'],
  num_machines: ['参与训练的机器总数。推荐范围：单机保持 1。', 'Total machines in the job. Recommended: 1 for single-node setups.'],
  machine_rank: ['当前机器编号（主节点为 0）。推荐范围：单机保持 0，多机各设不同编号。', 'This node rank in multi-node jobs. Single-node keeps 0.'],
  main_process_port: ['主节点 rendezvous 端口。推荐范围：默认 29500，冲突时改任意空闲端口。', 'Master rendezvous port. Recommended: default 29500; change only if occupied.'],
  ddp_timeout: ['DDP 集合通信超时秒数；0 用后端默认。推荐范围：慢盘/大模型启动慢时 1800 以上。', 'DDP collective timeout seconds; 0 uses backend default. Raise above 1800 for slow storage/startups.'],
  ddp_gradient_as_bucket_view: ['DDP 用 bucket view 复用梯度内存，更快更省。建议保持开启（后端默认 true）。', 'DDP gradient-as-bucket-view saves memory/time. Keep on (backend default true).'],
  ddp_static_graph: ['声明静态计算图以加速 DDP。仅当图确定不变（无条件分支训练路径）时开启。', 'Declares a static graph for faster DDP. Only for runs with no conditional graph branches.'],
  sync_config_from_main: ['worker 从主节点同步训练配置，避免两边不一致。建议保持开启。', 'Workers pull training config from the master. Keep on.'],
  sync_missing_assets_from_main: ['worker 按需从主节点拉缺失模型/数据。建议共享存储不可用时保持开启。', 'Workers fetch missing models/data from the master on demand. Keep on without shared storage.'],
  sync_ssh_port: ['远程同步 SSH 端口。推荐范围：保持默认 22，服务器特殊配置时再改。', 'SSH port for remote sync. Recommended: keep default 22 unless your server differs.'],
  sync_use_password_auth: ['远程同步用密码认证（否则走密钥）。建议优先密钥，密码方式留意泄露风险。', 'Password auth for remote sync (vs key auth). Prefer keys; beware credential exposure.'],

  // ── Loss 门控调度器（loss_gated_cosine / loss_weighted_annealed_cosine 子项） ──
  loss_scheduler_ema_alpha: ['Loss 门控调度：用 EMA 平滑原始 loss，避免单 batch 抖动误判相位。推荐范围：0.05–0.2（默认 0.1）。', 'EMA smoothing of raw loss so single-batch noise cannot flip phases. Recommended: 0.05-0.2 (default 0.1).'],
  loss_scheduler_min_delta: ['EMA loss 至少下降多少才算「仍在变好」，推进余弦相位。建议 5e-4（默认）附近。', 'Minimum EMA-loss drop counted as progress before the cosine advances. Keep near default 5e-4.'],
  loss_scheduler_relative_delta: ['按最佳 EMA loss 的比例判定有效下降（0-1）。建议 0.001（默认）。', 'Progress judged relative to the best EMA loss. Keep default 0.001.'],
  loss_scheduler_patience: ['连续多少个 optimizer step 无有效下降才继续推进相位。建议 8（默认）。', 'Consecutive stalled steps tolerated before advancing the phase. Keep 8.'],
  loss_scheduler_cooldown: ['有效下降后先忽略多少步平台期判断，减少来回抖动。建议 0–10。', 'Grace steps after progress before plateau checks resume; reduces oscillation.'],
  loss_scheduler_max_hold_steps: ['连续不推进相位的最大步数上限，防永久卡死。建议 0 不设限或给总步数的 10%。', 'Cap on how long the phase may stay held; 0 unlimited or ~10% of total steps.'],
  loss_scheduler_late_gamma: ['Loss 加权退火余弦的后期权重曲线指数。建议 2.0（默认）。', 'Late-phase weighting exponent for annealed cosine. Keep 2.0.'],
  loss_scheduler_lock_weight_threshold: ['Loss 加权退火余弦的锁定权重阈值。建议 0.7（默认）。', 'Lock threshold for weighted-annealed cosine. Keep 0.7.'],
  loss_scheduler_min_advance_ratio: ['最小相位推进速度比例（防长期停滞）。建议 0.25（默认）。', 'Minimum phase-advance rate preventing stalls. Keep 0.25.'],
};
