// SPDX-License-Identifier: LicenseRef-PolyFormNoncommercial-1.0.0
// optimizerParams.js — 优化器专属字段 + 参数模板字典
// 第一层：常用优化器出专属 UI 字段（选中时显示）
// 第二层：其余优化器在 optimizer_args_custom 自动预填参数模板

const isOpt = (...keys) => (cfg) =>
  keys.some((k) => String(cfg.optimizer_type || '').trim().toLowerCase() === k.toLowerCase());

// ── 第一层：专属 UI 字段 ─────────────────────────────────────────────────────

export const OPTIMIZER_SPECIFIC_FIELDS = [

  // ── CAME ──────────────────────────────────────────────────────────────────
  { key: 'opt_came_eps_group', type: 'number', label: 'CAME eps_group',
    desc: 'CAME 参数组级 epsilon。推荐范围：保持 1e-8。',
    defaultValue: 1e-8, min: 0, step: 1e-9,
    visibleWhen: isOpt('came', 'pytorch_optimizer.came') },
  { key: 'opt_came_eps_rho', type: 'number', label: 'CAME eps_rho',
    desc: 'CAME 曲率估计 epsilon。推荐范围：保持 1e-6。',
    defaultValue: 1e-6, min: 0, step: 1e-8,
    visibleWhen: isOpt('came', 'pytorch_optimizer.came') },

  // ── Adan ──────────────────────────────────────────────────────────────────
  { key: 'opt_adan_beta3', type: 'number', label: 'Adan beta3',
    desc: 'Adan 第三动量（梯度差分 EMA）系数。推荐范围：0.99（论文值）。',
    defaultValue: 0.99, min: 0, max: 1, step: 0.001,
    visibleWhen: isOpt('adan', 'pytorch_optimizer.adan') },
  { key: 'opt_adan_no_prox', type: 'boolean', label: 'Adan no_prox',
    desc: '禁用 Adan 近端项（weight decay 行为变化）。建议保持默认 false 以贴近论文配置。',
    defaultValue: false,
    visibleWhen: isOpt('adan', 'pytorch_optimizer.adan') },

  // ── AdEMAMix ──────────────────────────────────────────────────────────────
  { key: 'opt_ademamix_alpha', type: 'number', label: 'AdEMAMix alpha',
    desc: 'AdEMAMix 慢速 EMA 混合权重。推荐范围：5.0（默认/论文常用）。',
    defaultValue: 5.0, min: 0, step: 0.5,
    visibleWhen: isOpt('bitsandbytes.optim.ademamix8bit', 'bitsandbytes.optim.pagedademamix8bit',
      'pytorch_optimizer.ademamix', 'pytorch_optimizer.simplifiedademamix') },
  { key: 'opt_ademamix_beta3', type: 'number', label: 'AdEMAMix beta3',
    desc: 'AdEMAMix 慢速 EMA 动量。推荐范围：0.9999（默认）。',
    defaultValue: 0.9999, min: 0, max: 1, step: 0.0001,
    visibleWhen: isOpt('bitsandbytes.optim.ademamix8bit', 'bitsandbytes.optim.pagedademamix8bit') },
  { key: 'opt_ademamix_t_alpha_beta3', type: 'number', label: 'AdEMAMix T_alpha_beta3',
    desc: 'alpha/beta3 的线性预热步数，0 表示不预热。推荐范围：长训练可给 2000 左右，短训保持 0。',
    defaultValue: 0, min: 0, step: 100,
    visibleWhen: isOpt('bitsandbytes.optim.ademamix8bit', 'bitsandbytes.optim.pagedademamix8bit') },

  // ── Schedule-Free ─────────────────────────────────────────────────────────
  { key: 'opt_sf_warmup_steps', type: 'number', label: 'Schedule-Free warmup_steps',
    desc: 'Schedule-Free 内置预热步数，与外部 lr_warmup 二选一。推荐范围： 0 走外部预热或少量 100–500。',
    defaultValue: 0, min: 0, step: 10,
    visibleWhen: isOpt('adamwschedulefree', 'radamschedulefree', 'sgdschedulefree') },
  { key: 'opt_sf_beta', type: 'number', label: 'Schedule-Free β (beta)',
    desc: 'Schedule-Free 内置动量 β。推荐范围：0.9（默认）。',
    defaultValue: 0.9, min: 0, max: 1, step: 0.01,
    visibleWhen: isOpt('adamwschedulefree', 'radamschedulefree', 'sgdschedulefree') },

  // ── SOAP ──────────────────────────────────────────────────────────────────
  { key: 'opt_soap_precondition_frequency', type: 'number', label: 'SOAP precondition_frequency',
    desc: 'SOAP 预条件矩阵更新频率（每 N 步）。推荐范围：10（默认）；增大省时但适应变慢。',
    defaultValue: 10, min: 1, step: 1,
    visibleWhen: isOpt('soap', 'pytorch_optimizer.soap') },
  { key: 'opt_soap_shampoo_beta', type: 'number', label: 'SOAP shampoo_beta',
    desc: 'Shampoo 因子 EMA 系数；-1 表示按 beta1 处理。推荐范围：保持 -1。',
    defaultValue: -1, min: -1, max: 1, step: 0.01,
    visibleWhen: isOpt('soap', 'pytorch_optimizer.soap') },

  // ── MARS ──────────────────────────────────────────────────────────────────
  // mars_type（adamw/lion/shampoo）为字符串枚举，本 schema 只支持 number/boolean，
  // 需要切换时通过 optimizer_args 传 mars_type=lion。
  { key: 'opt_mars_gamma', type: 'number', label: 'MARS gamma',
    desc: 'MARS 梯度校正强度。推荐范围：0.025（论文常用）。',
    defaultValue: 0.025, min: 0, max: 1, step: 0.005,
    visibleWhen: isOpt('mars', 'pytorch_optimizer.mars') },
  { key: 'opt_mars_eps', type: 'number', label: 'MARS eps',
    desc: 'MARS 数值稳定 epsilon。推荐范围：保持 1e-8。',
    defaultValue: 1e-8, min: 0, step: 1e-9,
    visibleWhen: isOpt('mars', 'pytorch_optimizer.mars') },
  { key: 'opt_mars_optimize_1d', type: 'boolean', label: 'MARS optimize_1d',
    desc: '关闭时 1D 参数（bias/norm）走内置 AdamW；开启则一并用 MARS 更新。',
    defaultValue: false,
    visibleWhen: isOpt('mars', 'pytorch_optimizer.mars') },
  { key: 'opt_mars_ams_bound', type: 'boolean', label: 'MARS ams_bound',
    desc: 'MARS 启用 AMSBound 变体二阶矩。建议默认关闭。',
    defaultValue: false,
    visibleWhen: isOpt('mars', 'pytorch_optimizer.mars') },
  { key: 'opt_mars_cautious', type: 'boolean', label: 'MARS cautious',
    desc: 'MARS cautious 掩码：只保留与梯度同号的更新分量。建议开启尝试提升稳定性。',
    defaultValue: false,
    visibleWhen: isOpt('mars', 'pytorch_optimizer.mars') },

  // ── Lion ──────────────────────────────────────────────────────────────────
  { key: 'opt_lion_use_triton', type: 'boolean', label: 'Lion use_triton',
    desc: 'Lion 用 Triton fused kernel 加速。建议仅 NVIDIA 且装好 Triton 时开启，失败会回落。',
    defaultValue: false,
    visibleWhen: isOpt('lion', 'lion8bit', 'pagedlion8bit') },

  // ── ADOPT / KahanAdamW（frontier 候选）───────────────────────────────────
  { key: 'opt_adopt_clip_lambda', type: 'number', label: 'ADOPT clip_lambda',
    desc: 'ADOPT 梯度裁剪系数，防早期爆炸。推荐范围：0.1（默认）附近；0 关闭。',
    defaultValue: 0.1, min: 0, step: 0.01,
    visibleWhen: isOpt('adopt', 'kahanadamw', 'kahanadamw8bit') },
  { key: 'opt_adopt_eps', type: 'number', label: 'ADOPT eps',
    desc: 'ADOPT 数值稳定 epsilon。推荐范围：保持默认 1e-6。',
    defaultValue: 1e-6, min: 0, step: 1e-8,
    visibleWhen: isOpt('adopt', 'kahanadamw', 'kahanadamw8bit') },

  // ── AdamWBF16（first-party 补偿求和；无额外 knobs，仅提示）────────────────
  { key: 'opt_adamw_bf16_note', type: 'string', label: 'AdamWBF16 说明',
    desc: '仅支持 bf16 训练参数；moments 与 residual 在 fp32。与 TurboCore fused multi-tensor / gradient_release full 不承诺全开组合。lr/betas/wd 走通用字段或 optimizer_args_custom。',
    defaultValue: 'bf16-only + fp32 residual',
    visibleWhen: isOpt('adamwbf16') },

  // ── KahanAdamW8bit ────────────────────────────────────────────────────────
  // 需要 bitsandbytes；矩存 8bit，Kahan 补偿量恒为 fp32（量化它等于丢掉本优化器要留的残差）。
  { key: 'opt_kahan8bit_block_size', type: 'number', label: 'KahanAdamW8bit block_size',
    desc: 'KahanAdamW8bit 分块量化块大小。推荐范围：2048（默认）；必须是 64–4096 的 2 的幂。',
    defaultValue: 2048, min: 64, max: 4096, step: 64,
    visibleWhen: isOpt('kahanadamw8bit') },
  { key: 'opt_kahan8bit_min_8bit_size', type: 'number', label: 'KahanAdamW8bit min_8bit_size',
    desc: '低于该元素数的张量保留 fp32，规避小张量量化噪声。推荐范围：4096（默认）。',
    defaultValue: 4096, min: 0, step: 256,
    visibleWhen: isOpt('kahanadamw8bit') },

  // ── SCION / SCIONLight ────────────────────────────────────────────────────
  { key: 'opt_scion_kappa', type: 'number', label: 'SCION kappa',
    desc: 'SCION 归一化约束系数。推荐范围：0.01–0.1。',
    defaultValue: 0.01, min: 0, step: 0.001,
    visibleWhen: isOpt('scion', 'scionlight', 'pytorch_optimizer.scion', 'pytorch_optimizer.scionlight',
      'stableadamw', 'pytorch_optimizer.stableadamw') },
  { key: 'opt_scion_init_scale', type: 'number', label: 'SCION init_scale',
    desc: 'SCION 初始化缩放。推荐范围：保持 1.0。',
    defaultValue: 1.0, min: 0, step: 0.1,
    visibleWhen: isOpt('scion', 'scionlight', 'pytorch_optimizer.scion', 'pytorch_optimizer.scionlight') },

  // ── Adafactor ─────────────────────────────────────────────────────────────
  { key: 'opt_adafactor_scale_parameter', type: 'boolean', label: 'Adafactor scale_parameter',
    desc: '按参数规模缩放学习率（推荐关闭，自己设 lr）。',
    defaultValue: false,
    visibleWhen: isOpt('adafactor', 'adafactor') },
  { key: 'opt_adafactor_relative_step', type: 'boolean', label: 'Adafactor relative_step',
    desc: 'Adafactor 使用相对步长自适应。建议关闭并用固定 LR 以便复现；开启则忽略 learning_rate。',
    defaultValue: false,
    visibleWhen: isOpt('adafactor', 'adafactor') },
  { key: 'opt_adafactor_warmup_init', type: 'boolean', label: 'Adafactor warmup_init',
    desc: 'relative_step=True 时初始预热。建议保持关闭。',
    defaultValue: false,
    visibleWhen: isOpt('adafactor', 'adafactor') },

  // ── GrokFastAdamW ─────────────────────────────────────────────────────────
  { key: 'opt_grok_alpha', type: 'number', label: 'GrokFast alpha',
    desc: 'GrokFast 梯度 EMA 系数。推荐范围：0.98（默认）。',
    defaultValue: 0.98, min: 0, max: 1, step: 0.01,
    visibleWhen: isOpt('pytorch_optimizer.grokfastadamw') },
  { key: 'opt_grok_lamb', type: 'number', label: 'GrokFast lamb',
    desc: 'GrokFast EMA 混合比例 λ。推荐范围：2.0（默认）。',
    defaultValue: 2.0, min: 0, step: 0.1,
    visibleWhen: isOpt('pytorch_optimizer.grokfastadamw') },

  // ── SophiaH ───────────────────────────────────────────────────────────────
  { key: 'opt_sophia_rho', type: 'number', label: 'SophiaH rho',
    desc: 'SophiaH 更新裁剪系数。推荐范围：0.04（论文值）。',
    defaultValue: 0.04, min: 0, step: 0.005,
    visibleWhen: isOpt('pytorch_optimizer.sophiah') },
  { key: 'opt_sophia_update_period', type: 'number', label: 'SophiaH update_period',
    desc: 'Hessian 对角估计的更新间隔步数。推荐范围：10（默认）；越大越快越粗糙。',
    defaultValue: 10, min: 1, step: 1,
    visibleWhen: isOpt('pytorch_optimizer.sophiah') },

  // ── Kron (SOAP 变种) ──────────────────────────────────────────────────────
  { key: 'opt_kron_precond_update_prob', type: 'number', label: 'Kron precond_update_prob',
    desc: 'Kron 预条件矩阵随机更新概率（均摊开销）。推荐范围：0.03（默认）。',
    defaultValue: 0.03, min: 0, max: 1, step: 0.01,
    visibleWhen: isOpt('pytorch_optimizer.kron') },

  // ── SPAM ──────────────────────────────────────────────────────────────────
  { key: 'opt_spam_gamma', type: 'number', label: 'SPAM gamma',
    desc: 'SPAM 动量重置阈值（梯度超 gamma×均值触发）。推荐范围：2（默认）。',
    defaultValue: 2.0, min: 0, step: 0.1,
    visibleWhen: isOpt('pytorch_optimizer.spam', 'pytorch_optimizer.stablespam') },
  { key: 'opt_spam_density', type: 'number', label: 'SPAM density',
    desc: 'SPAM 动量稀疏化比例，0=不稀疏。推荐范围：保持 0（关闭）。',
    defaultValue: 0.0, min: 0, max: 1, step: 0.01,
    visibleWhen: isOpt('pytorch_optimizer.spam', 'pytorch_optimizer.stablespam') },

  // ── FAdam ─────────────────────────────────────────────────────────────────
  { key: 'opt_fadam_p', type: 'number', label: 'FAdam p',
    desc: 'FAdam Fisher 信息幂次。推荐范围：0.5（平方根，论文值）。',
    defaultValue: 0.5, min: 0.1, max: 1, step: 0.05,
    visibleWhen: isOpt('pytorch_optimizer.fadam') },

  // ── DAdapt 系列 ───────────────────────────────────────────────────────────
  { key: 'opt_dadapt_growth_rate', type: 'number', label: 'DAdapt growth_rate',
    desc: 'DAdaptation 步长增长上界倍率。推荐范围：留空用默认；设置过小会限制自适应速度。',
    defaultValue: '', step: 0.1,
    visibleWhen: isOpt('dadaptation', 'dadaptadam', 'dadaptadampreprint', 'dadaptlion', 'dadaptsgd',
      'dadaptadagrad', 'dadaptadan', 'dadaptadanip') },
  { key: 'opt_dadapt_d0', type: 'number', label: 'DAdapt d0',
    desc: 'DAdaptation 初始步长估计。推荐范围：1e-6（默认，小值让其自行爬升）。',
    defaultValue: 1e-6, min: 0, step: 1e-7,
    visibleWhen: isOpt('dadaptation', 'dadaptadam', 'dadaptadampreprint', 'dadaptlion', 'dadaptsgd',
      'dadaptadagrad', 'dadaptadan', 'dadaptadanip') },

  // ── Muon（frontier 候选） ─────────────────────────────────────────────────
  { key: 'opt_muon_momentum', type: 'number', label: 'Muon momentum',
    desc: 'Muon 动量系数。推荐范围：0.95（默认）。',
    defaultValue: 0.95, min: 0, max: 1, step: 0.01,
    visibleWhen: isOpt('muon', 'pytorch_optimizer.muon', 'distributedmuon') },
  { key: 'opt_muon_nesterov', type: 'boolean', label: 'Muon nesterov',
    desc: 'Muon 启用 Nesterov 前瞻动量。建议保持开启（通常更优）。',
    defaultValue: true,
    visibleWhen: isOpt('muon', 'pytorch_optimizer.muon', 'distributedmuon') },

  // ── Riemannion ────────────────────────────────────────────────────────────
  { key: 'opt_riemannion_momentum', type: 'number', label: 'Riemannion momentum',
    desc: 'Riemannion 流形动量。推荐范围：0.9（默认）。',
    defaultValue: 0.9, min: 0, max: 1, step: 0.01,
    visibleWhen: isOpt('riemannion') },
  { key: 'opt_riemannion_orthogonalize', type: 'boolean', label: 'Riemannion orthogonalize',
    desc: '对更新做 Newton-Schulz 正交化。建议保持开启以稳定流形步长。',
    defaultValue: true,
    visibleWhen: isOpt('riemannion') },
  { key: 'opt_riemannion_ns_steps', type: 'number', label: 'Riemannion ns_steps',
    desc: 'Riemannion Newton-Schulz 迭代数。推荐范围：5（默认）。',
    defaultValue: 5, min: 1, step: 1,
    visibleWhen: isOpt('riemannion') },
  { key: 'opt_riemannion_solve_eps', type: 'number', label: 'Riemannion solve_eps',
    desc: 'Riemannion 求解阻尼 epsilon。推荐范围：保持 1e-6。',
    defaultValue: 1e-6, min: 0, step: 1e-7,
    visibleWhen: isOpt('riemannion') },

  // ── Rose ──────────────────────────────────────────────────────────────────
  { key: 'opt_rose_gradient_centralization', type: 'boolean', label: 'Rose gradient_centralization',
    desc: 'Rose 梯度去均值中心化。建议保持开启（常利于泛化）。',
    defaultValue: true,
    visibleWhen: isOpt('rose') },
  { key: 'opt_rose_stochastic_rounding', type: 'boolean', label: 'Rose stochastic_rounding',
    desc: '低精度更新随机取整，减少舍入偏差。建议保持开启。',
    defaultValue: true,
    visibleWhen: isOpt('rose') },

  // ── Aurora ────────────────────────────────────────────────────────────────
  { key: 'opt_aurora_momentum', type: 'number', label: 'Aurora momentum',
    desc: 'Aurora 动量系数。推荐范围：0.95（默认）。',
    defaultValue: 0.95, min: 0, max: 1, step: 0.01,
    visibleWhen: isOpt('aurora') },
  { key: 'opt_aurora_nesterov', type: 'boolean', label: 'Aurora nesterov',
    desc: 'Aurora 启用 Nesterov 动量。建议保持开启。',
    defaultValue: true,
    visibleWhen: isOpt('aurora') },
  { key: 'opt_aurora_ns_steps', type: 'number', label: 'Aurora ns_steps',
    desc: 'Aurora Newton-Schulz 正交化迭代数。推荐范围：6（默认）；越大越准越慢。',
    defaultValue: 6, min: 1, step: 1,
    visibleWhen: isOpt('aurora') },
  { key: 'opt_aurora_pp_iterations', type: 'number', label: 'Aurora pp_iterations',
    desc: 'Aurora 行范数均衡投影迭代。推荐范围：2（默认）。',
    defaultValue: 2, min: 1, step: 1,
    visibleWhen: isOpt('aurora') },
  { key: 'opt_aurora_damping', type: 'number', label: 'Aurora damping',
    desc: 'Aurora 行范数均衡强度 0–1。推荐范围： 0.5（默认）。',
    defaultValue: 0.5, min: 0, max: 1, step: 0.05,
    visibleWhen: isOpt('aurora') },
];

// ── 第二层：参数模板字典 ──────────────────────────────────────────────────────
// key = optimizer_type.trim().toLowerCase()
// value = 预填到 optimizer_args_custom 的模板字符串（key=value 每行一个）

export const OPTIMIZER_ARG_TEMPLATES = {
  // pytorch_optimizer 系列（选中后自动预填常用参数）
  'pytorch_optimizer.adan':         'beta1=0.98\nbeta2=0.92\nbeta3=0.99\neps=1e-8\nno_prox=False',
  'pytorch_optimizer.adabelief':    'eps=1e-16\nbeta1=0.9\nbeta2=0.999\nrectify=True',
  'pytorch_optimizer.adabound':     'final_lr=0.1\nbeta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.adahessian':   'hessian_power=1.0\nbeta1=0.9\nbeta2=0.999\nblock_length=512',
  'pytorch_optimizer.adanorm':      'beta1=0.9\nbeta2=0.999\neps=1e-8\nv_type=exp',
  'pytorch_optimizer.adapnm':       'beta1=0.9\nbeta2=0.999\nbeta3=0.9999\neps=1e-8',
  'pytorch_optimizer.adashift':     'beta1=0.9\nbeta2=0.999\nsteps_per_window=10',
  'pytorch_optimizer.adatam':       'beta1=0.9\nbeta2=0.999\neps=1e-8\ntam_power=0.5',
  'pytorch_optimizer.aggmo':        'betas=[0.0,0.9,0.99]\nk=3',
  'pytorch_optimizer.apollo':       'rank=1\nscale_type=channel\nupdate_proj_gap=200\neps=1e-8',
  'pytorch_optimizer.apollodqn':    'rank=1\nscale_type=channel\nupdate_proj_gap=200',
  'pytorch_optimizer.avagrad':      'weight_decay=0.0\neps=1e-3',
  'pytorch_optimizer.came':         'eps_group=1e-8\neps_rho=1e-6\nbeta1=0.9\nbeta2=0.999\nbeta3=0.9999',
  'pytorch_optimizer.conda':        'beta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.dadaptadagrad':'growth_rate=1.02\nd0=1e-6',
  'pytorch_optimizer.dadaptadam':   'growth_rate=1.02\nd0=1e-6\ndecouple=True',
  'pytorch_optimizer.dadaptadan':   'growth_rate=1.02\nd0=1e-6',
  'pytorch_optimizer.dadaptlion':   'growth_rate=1.02\nd0=1e-6',
  'pytorch_optimizer.dadaptsgd':    'growth_rate=1.02\nd0=1e-6\nmomentum=0.0',
  'pytorch_optimizer.demo':         'beta1=0.9\nbeta2=0.999\neps=1e-8\nchunk_size=256',
  'pytorch_optimizer.diffgrad':     'beta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.dualatam':     'beta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.exadam':       'beta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.emofact':      'beta1=0.9\nbeta2=0.999',
  'pytorch_optimizer.emolynx':      'beta1=0.9\nbeta2=0.999',
  'pytorch_optimizer.fadam':        'p=0.5\nbeta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.fira':         'rank=1\nupdate_proj_gap=200\nscale_type=channel',
  'pytorch_optimizer.fromage':      'p=1e-2',
  'pytorch_optimizer.galore':       'rank=128\nupdate_proj_gap=200\nalpha=0.25\nscale_type=channel',
  'pytorch_optimizer.grams':        'beta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.gravity':      'alpha=0.01\nbeta=0.9',
  'pytorch_optimizer.grokfastadamw':'alpha=0.98\nlamb=2.0\nbeta1=0.9\nbeta2=0.999',
  'pytorch_optimizer.kate':         'beta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.kron':         'precond_update_prob=0.03\nmax_size_triangular=8192\nmin_ndim_triangular=2',
  'pytorch_optimizer.lars':         'momentum=0.9\nweight_decay=0.0\neps=1e-8\neta=1e-3',
  'pytorch_optimizer.laprop':       'beta1=0.9\nbeta2=0.999\neps=1e-8\nstepsizecontrol=1.0',
  'pytorch_optimizer.lamb':         'beta1=0.9\nbeta2=0.999\neps=1e-6\nweight_decay=0.01',
  'pytorch_optimizer.lbfgs':        'max_iter=20\nhistory_size=100\nline_search_fn=strong_wolfe',
  'pytorch_optimizer.lomo':         'clip_grad_norm=1.0\nclip_grad_value=None',
  'pytorch_optimizer.adalomo':      'clip_grad_norm=1.0',
  'pytorch_optimizer.madgrad':      'momentum=0.9\neps=1e-6\nweight_decay=0.0',
  'pytorch_optimizer.msvag':        'beta=0.9',
  'pytorch_optimizer.nero':         'beta=0.999\neps=1e-8',
  'pytorch_optimizer.muon':         'momentum=0.95\nnesterov=True',
  'pytorch_optimizer.novograd':     'beta1=0.95\nbeta2=0.0\neps=0.0\nweight_decay=0.0',
  'pytorch_optimizer.padam':        'p=0.1\nbeta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.pid':          'momentum=0.9\nsaturation=1.0\ndelta=0.01',
  'pytorch_optimizer.pnm':          'beta1=0.9\nbeta2=1.0\nnoise_factor=1.0',
  'pytorch_optimizer.qhadam':       'qs=1.0\nbeta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.qhm':          'momentum=0.9\nnu=0.7',
  'pytorch_optimizer.racs':         'beta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.radam':        'beta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.ranger':       'alpha=0.5\nbeta1=0.95\nbeta2=0.999\neps=1e-5',
  'pytorch_optimizer.ranger21':     'beta1=0.9\nbeta2=0.999\neps=1e-8\nnum_warmup_iterations=5',
  'pytorch_optimizer.ranger25':     'beta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.schedulefreeadamw': 'warmup_steps=0\nbeta=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.schedulefreeradam': 'warmup_steps=0\nbeta=0.9\nbeta2=0.999',
  'pytorch_optimizer.schedulefreesgd':   'warmup_steps=0\nbeta=0.9\nmomentum=0.0',
  'pytorch_optimizer.sgdp':         'momentum=0.9\nnesterov=True\neps=1e-8',
  'pytorch_optimizer.sgdsai':       'momentum=0.9\neps=1e-8',
  'pytorch_optimizer.sgdw':         'momentum=0.9\nnesterov=False\nweight_decay=0.01',
  'pytorch_optimizer.sm3':          'momentum=0.0\nbeta=0.0\neps=1e-8',
  'pytorch_optimizer.soap':         'precondition_frequency=10\nshampoo_beta=-1\nbeta1=0.95\nbeta2=0.95',
  'pytorch_optimizer.sophiah':      'rho=0.04\nupdate_period=10\nbeta1=0.96\nbeta2=0.999',
  'pytorch_optimizer.spam':         'gamma=2.0\ndensity=0.0\nbeta1=0.9\nbeta2=0.999',
  'pytorch_optimizer.stablespam':   'gamma=2.0\nbeta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.splus':        'beta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.srmm':         'beta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.swats':        'beta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.scalableshampoo': 'start_preconditioning_step=25\npreconditioning_compute_steps=10',
  'pytorch_optimizer.signsdd':      'beta=0.9',
  'pytorch_optimizer.stableadamw':  'kappa=0.01\nbeta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.scion':        'kappa=0.01\ninit_scale=1.0',
  'pytorch_optimizer.scionlight':   'kappa=0.01\ninit_scale=1.0',
  'pytorch_optimizer.tam':          'beta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.tiger':        'beta1=0.965\nbeta2=0.99\neps=1e-8',
  'pytorch_optimizer.vsgd':         'beta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.yogi':         'beta1=0.9\nbeta2=0.999\neps=1e-3\ninitial_accumulator=1e-6',
  'pytorch_optimizer.spectralsphere': 'beta1=0.9\nbeta2=0.999',
  'pytorch_optimizer.aida':         'beta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.alig':         'max_lr=1.0\nepochs=None',
  'pytorch_optimizer.alice':        'beta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.amos':         'beta=0.999\neps=1e-8',
  'pytorch_optimizer.ano':          'beta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.bcos':         'beta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.bsam':         'rho=0.05\nbeta1=0.9\nbeta2=0.999',
  'pytorch_optimizer.focus':        'beta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.ftrl':         'alpha=0.5\nbeta=0.0\nl1=0.0\nl2=0.0',
  'pytorch_optimizer.adagc':        'beta1=0.9\nbeta2=0.999\neps=1e-8\nmax_norm=1.0',
  'pytorch_optimizer.adago':        'beta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.adai':         'beta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.adalite':      'beta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.adamc':        'beta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.adamg':        'beta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.adammini':     'verbose=False',
  'pytorch_optimizer.adamp':        'delta=0.1\nbeta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.adams':        'beta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.adamwsn':      'beta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.adafactor':    'scale_parameter=False\nrelative_step=False\nwarmup_init=False',
  'pytorch_optimizer.adamax':       'beta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.adamod':       'beta1=0.9\nbeta2=0.999\nbeta3=0.999\neps=1e-8',
  'pytorch_optimizer.adagrad':      'lr_decay=0\nweight_decay=0\ninitial_accumulator_value=0',
  'pytorch_optimizer.adamsmooth':   'beta1=0.9\nbeta2=0.999\neps=1e-8',
  'pytorch_optimizer.adamwsai':     'beta1=0.9\nbeta2=0.999\neps=1e-8',
  // bitsandbytes 系列
  'bitsandbytes.optim.ademamix8bit':      'alpha=5.0\nbeta3=0.9999\nt_alpha_beta3=0',
  'bitsandbytes.optim.pagedademamix8bit': 'alpha=5.0\nbeta3=0.9999\nt_alpha_beta3=0',
  // BASE_OPTIMIZERS 里有参考意义的
  'singularityawareadamw':          'eps=1e-8\nweight_decay=0.01\ngamma=0.01',
  'dadaptation':                    'd0=1e-6\ndecouple=True\ngrowth_rate=1.02',
  'dadaptadampreprint':             'd0=1e-6\ngrowth_rate=1.02\ndecouple=True',
  'dadaptadam':                     'd0=1e-6\ndecouple=True\ngrowth_rate=1.02',
  'dadaptadagrad':                  'd0=1e-6\ngrowth_rate=1.02',
  'dadaptadan':                     'd0=1e-6\ngrowth_rate=1.02',
  'dadaptadanip':                   'd0=1e-6\ngrowth_rate=1.02',
  'dadaptlion':                     'd0=1e-6\ngrowth_rate=1.02',
  'dadaptsgd':                      'd0=1e-6\nmomentum=0.0\ngrowth_rate=1.02',
  'adafactor':                      'scale_parameter=False\nrelative_step=False\nwarmup_init=False',
};

// opt_* → backend arg name 映射，供 normalizeOptimizerArgs 组装 optimizer_args
export const OPT_FIELD_ARG_KEYS = {
  opt_came_eps_group:              'eps_group',
  opt_came_eps_rho:                'eps_rho',
  opt_adan_beta3:                  'beta3',
  opt_adan_no_prox:                'no_prox',
  opt_ademamix_alpha:              'alpha',
  opt_ademamix_beta3:              'beta3',
  opt_ademamix_t_alpha_beta3:      'T_alpha_beta3',
  opt_sf_warmup_steps:             'warmup_steps',
  opt_sf_beta:                     'beta',
  opt_soap_precondition_frequency: 'precondition_frequency',
  opt_soap_shampoo_beta:           'shampoo_beta',
  opt_lion_use_triton:             'use_triton',
  opt_adopt_clip_lambda:           'clip_lambda',
  opt_adopt_eps:                   'eps',
  opt_scion_kappa:                 'kappa',
  opt_scion_init_scale:            'init_scale',
  opt_adafactor_scale_parameter:   'scale_parameter',
  opt_adafactor_relative_step:     'relative_step',
  opt_adafactor_warmup_init:       'warmup_init',
  opt_grok_alpha:                  'alpha',
  opt_grok_lamb:                   'lamb',
  opt_sophia_rho:                  'rho',
  opt_sophia_update_period:        'update_period',
  opt_kron_precond_update_prob:    'precond_update_prob',
  opt_spam_gamma:                  'gamma',
  opt_spam_density:                'density',
  opt_fadam_p:                     'p',
  opt_dadapt_growth_rate:          'growth_rate',
  opt_dadapt_d0:                   'd0',
  opt_muon_momentum:               'momentum',
  opt_muon_nesterov:               'nesterov',
  opt_riemannion_momentum:         'momentum',
  opt_riemannion_orthogonalize:    'orthogonalize',
  opt_riemannion_ns_steps:         'ns_steps',
  opt_riemannion_solve_eps:        'solve_eps',
  opt_rose_gradient_centralization:'gradient_centralization',
  opt_rose_stochastic_rounding:    'stochastic_rounding',
  opt_aurora_momentum:             'momentum',
  opt_aurora_nesterov:             'nesterov',
  opt_aurora_ns_steps:             'ns_steps',
  opt_aurora_pp_iterations:        'pp_iterations',
  opt_aurora_damping:              'damping',
  opt_mars_gamma:                  'gamma',
  opt_mars_eps:                    'eps',
  opt_mars_optimize_1d:            'optimize_1d',
  opt_mars_ams_bound:              'ams_bound',
  opt_mars_cautious:               'cautious',
  opt_kahan8bit_block_size:        'block_size',
  opt_kahan8bit_min_8bit_size:     'min_8bit_size',
};
